[phases.setup]
nixPkgs = ["jdk21"]

[phases.install]
cmds = ["chmod +x mvnw", "./mvnw -B dependency:go-offline"]

[phases.build]
cmds = ["./mvnw -DskipTests -B clean package"]

[start]
cmd = "java -Dserver.port=$PORT -jar target/*.jar"
