const { q, writeSubject } = require('./qgen_helper');

const chapters = [
  ["Dermatology General", [
    q("A primary skin lesion that is flat, nonpalpable, and characterized solely by a change in skin color (e.g., a freckle) is called a:", "Macule", "Papule", "Nodule", "Plaque", "A", "Macules are less than 1 cm in diameter; patches are greater than 1 cm.", "EASY", "Textbook", "Skin Morphology"),
    q("A solid, elevated, palpable lesion strictly less than 1 cm in diameter is a:", "Papule", "Macule", "Vesicle", "Bulla", "A", "If it enlarges or coalesces to be greater than 1 cm, it is termed a plaque.", "EASY", "Textbook", "Skin Morphology"),
    q("The hallmark sign of an acute allergic contact dermatitis (Type IV hypersensitivity) is the presence of:", "Erythematous, intensely pruritic papules and vesicles often in linear arrays", "Painless, non-pruritic, large tense bullae", "Silvery scaly plaques on the extensor surfaces", "Targetoid lesions with central blistering", "A", "Poison ivy classically causes streaks of vesicles. It is mediated by memory T-cells.", "EASY", "Textbook", "Eczema/Dermatitis"),
    q("A sharply demarcated, erythematous plaque covered by a silvery-white scale, classically appearing symmetrically on the elbows, knees, and scalp, is highly characteristic of:", "Psoriasis", "Atopic dermatitis", "Seborrheic dermatitis", "Lichen planus", "A", "Removal of the scale produces pinpoint bleeding (Auspitz sign).", "EASY", "Textbook", "Papulosquamous Diseases"),
    q("Intensely pruritic, purple, polygonal, planar papules and plaques commonly found on the flexor surfaces of the wrists and forearms define:", "Lichen planus", "Pityriasis rosea", "Guttate psoriasis", "Molluscum contagiosum", "A", "The '6 Ps' of Lichen planus: Pruritic, Purple, Polygonal, Planar, Papules, and Plaques.", "MEDIUM", "Textbook", "Papulosquamous Diseases"),
    q("A young adult presents with a single, large, oval, scaly 'herald patch' on the trunk, followed a week later by a generalized eruption of smaller scaly macules distributed in a 'Christmas tree' pattern. Diagnosis?", "Pityriasis rosea", "Tinea corporis", "Secondary syphilis", "Atopic dermatitis", "A", "Self-limiting condition, likely viral in origin. Resolves spontaneously in 6-8 weeks.", "EASY", "Textbook", "Papulosquamous Diseases"),
    q("Which autoimmune blistering disease is characterized pathophysiologically by autoantibodies directed against desmoglein 1 and 3 in the epidermis, leading to flaccid bullae that easily rupture?", "Pemphigus vulgaris", "Bullous pemphigoid", "Dermatitis herpetiformis", "Erythema multiforme", "A", "Loss of cell-to-cell adhesion (acantholysis) causes a positive Nikolsky sign.", "HARD", "Textbook", "Vesiculobullous Diseases"),
    q("Bullous pemphigoid classically presents in the elderly and differs from pemphigus vulgaris in that its bullae are:", "Tense, subepidermal, and negative for Nikolsky sign", "Flaccid, intraepidermal, and positive for Nikolsky sign", "Confined exclusively to the oral mucosa", "Associated with severe gluten sensitivity", "A", "Autoantibodies against hemidesmosomes (BP180, BP230) separate the entire epidermis from the dermis.", "MEDIUM", "Textbook", "Vesiculobullous Diseases"),
    q("Intensely pruritic, grouped vesicles appearing on the elbows, knees, and buttocks, strongly associated with Celiac disease (gluten-sensitive enteropathy), is called:", "Dermatitis herpetiformis", "Pemphigus foliaceus", "Herpes zoster", "Bullous impetigo", "A", "IgA deposits in the dermal papillae cause this skin manifestation of Celiac disease. Treat with Dapsone and gluten-free diet.", "MEDIUM", "Textbook", "Vesiculobullous Diseases"),
    q("The most common, locally destructive but rarely metastasizing, form of skin cancer directly linked to chronic sun exposure and appearing as a 'pearly' nodule with telangiectasias is:", "Basal Cell Carcinoma (BCC)", "Squamous Cell Carcinoma (SCC)", "Melanoma", "Kaposi sarcoma", "A", "BCC is the most common human malignancy overall, primarily found on the sun-exposed face and nose.", "EASY", "Textbook", "Cutaneous Tumors")
  ]]
]

writeSubject("Dermatology", chapters, "dermatology.json");
