const { q, writeSubject } = require('./qgen_helper');

const chapters = [
  ["Upper Limb", [
    q("The nerve most commonly injured in fracture of shaft of humerus is:", "Radial nerve", "Ulnar nerve", "Median nerve", "Axillary nerve", "A", "Radial nerve lies in spiral groove of humerus.", "MEDIUM", "Textbook", "Radial nerve"),
    q("Erb's palsy involves injury to nerve roots:", "C5, C6", "C7, C8", "C8, T1", "C4, C5", "A", "Erb-Duchenne palsy results from upper trunk (C5-C6) injury.", "MEDIUM", "Textbook", "Brachial plexus"),
    q("Klumpke's paralysis is due to injury to:", "C8, T1", "C5, C6", "C6, C7", "C7, C8", "A", "Klumpke's palsy involves lower trunk (C8-T1).", "MEDIUM", "Textbook", "Brachial plexus"),
    q("Anatomical snuffbox contains which artery?", "Radial artery", "Ulnar artery", "Brachial artery", "Anterior interosseous artery", "A", "Radial artery crosses the floor of anatomical snuffbox.", "EASY", "Textbook", "Snuffbox"),
    q("Claw hand deformity is caused by injury to:", "Ulnar nerve", "Median nerve", "Radial nerve", "Musculocutaneous nerve", "A", "Ulnar nerve injury causes claw hand.", "MEDIUM", "Textbook", "Ulnar nerve"),
    q("Nerve passing through carpal tunnel:", "Median nerve", "Ulnar nerve", "Radial nerve", "Posterior interosseous nerve", "A", "Median nerve passes through carpal tunnel.", "EASY", "Textbook", "Carpal tunnel"),
    q("Winging of scapula is due to paralysis of:", "Serratus anterior", "Trapezius", "Rhomboids", "Levator scapulae", "A", "Long thoracic nerve supplies serratus anterior.", "MEDIUM", "Textbook", "Serratus anterior"),
    q("Saturday night palsy involves which nerve?", "Radial nerve", "Ulnar nerve", "Median nerve", "Long thoracic nerve", "A", "Compression of radial nerve causes wrist drop.", "EASY", "Textbook", "Radial nerve"),
    q("Ape thumb deformity is caused by injury to:", "Median nerve", "Ulnar nerve", "Radial nerve", "Posterior interosseous nerve", "A", "Median nerve injury causes loss of thenar apex.", "MEDIUM", "Textbook", "Median nerve"),
    q("The rotator cuff muscle NOT attached to greater tubercle:", "Subscapularis", "Supraspinatus", "Infraspinatus", "Teres minor", "A", "Subscapularis inserts on lesser tubercle.", "MEDIUM", "Textbook", "Rotator cuff"),
    q("Axillary nerve injury occurs in fracture of:", "Surgical neck of humerus", "Anatomical neck of humerus", "Shaft of humerus", "Lateral epicondyle", "A", "Axillary nerve winds around surgical neck.", "MEDIUM", "Textbook", "Axillary nerve"),
    q("Cubitus valgus with ulnar nerve palsy is seen in:", "Lateral condyle fracture", "Medial epicondyle fracture", "Supracondylar fracture", "Olecranon fracture", "A", "Non-union of lateral condyle leads to tardy ulnar nerve palsy.", "HARD", "Textbook", "Cubitus valgus"),
    q("Hand of benediction is seen in injury to:", "Median nerve at elbow", "Ulnar nerve at wrist", "Radial nerve at arm", "Posterior interosseous nerve", "A", "High median nerve lesion causes hand of benediction.", "HARD", "Textbook", "Median nerve"),
    q("Froment's sign is positive in lesion of:", "Ulnar nerve", "Median nerve", "Radial nerve", "Musculocutaneous nerve", "A", "Froment's sign tests adductor pollicis.", "MEDIUM", "Textbook", "Ulnar nerve"),
    q("The dermatome of the thumb is:", "C6", "C7", "C5", "C8", "A", "C6 dermatome covers the thumb.", "EASY", "Textbook", "Dermatomes")
  ]],
  ["Lower Limb", [
    q("Nerve injured in fracture neck of fibula:", "Common peroneal nerve", "Tibial nerve", "Saphenous nerve", "Sural nerve", "A", "Common peroneal nerve winds around neck of fibula.", "MEDIUM", "Textbook", "Peroneal nerve"),
    q("Trendelenburg test is positive when which muscle is paralyzed?", "Gluteus medius", "Gluteus maximus", "Iliopsoas", "Quadriceps", "A", "Gluteus medius is the chief hip abductor.", "MEDIUM", "Textbook", "Gluteal muscles"),
    q("Foot drop is caused by injury to:", "Common peroneal nerve", "Tibial nerve", "Femoral nerve", "Obturator nerve", "A", "Common peroneal nerve supplies ankle dorsiflexors.", "EASY", "Textbook", "Foot drop"),
    q("Femoral nerve injury causes loss of:", "Knee extension", "Hip extension", "Ankle dorsiflexion", "Knee flexion", "A", "Femoral nerve supplies quadriceps femoris.", "EASY", "Textbook", "Femoral nerve"),
    q("Great saphenous vein drains into:", "Femoral vein", "Popliteal vein", "External iliac vein", "Internal iliac vein", "A", "Great saphenous vein drains into femoral vein.", "EASY", "Textbook", "Veins"),
    q("The nerve of the medial compartment of thigh:", "Obturator nerve", "Femoral nerve", "Sciatic nerve", "Tibial nerve", "A", "Obturator nerve (L2-L4) supplies adductor group.", "MEDIUM", "Textbook", "Obturator nerve"),
    q("Injury to superior gluteal nerve affects:", "Gluteus medius and minimus", "Gluteus maximus", "Piriformis", "Obturator internus", "A", "Superior gluteal nerve supplies gluteus medius/minimus.", "MEDIUM", "Textbook", "Gluteal nerves"),
    q("The structure passing through adductor canal:", "Femoral artery", "Profunda femoris", "Obturator artery", "LCF artery", "A", "Femoral artery passes through adductor canal.", "MEDIUM", "Textbook", "Adductor canal"),
    q("Locking of knee joint is caused by injury to:", "Meniscus", "ACL", "PCL", "LCL", "A", "Torn meniscus fragment can cause mechanical locking.", "MEDIUM", "Textbook", "Knee joint"),
    q("Anterior drawer test is positive in injury to:", "ACL", "PCL", "MCL", "LCL", "A", "Anterior drawer test assesses ACL integrity.", "MEDIUM", "Textbook", "ACL"),
    q("The muscle that unlocks the knee joint:", "Popliteus", "Gastrocnemius", "Soleus", "Plantaris", "A", "Popliteus laterally rotates femur to unlock knee.", "MEDIUM", "Textbook", "Popliteus"),
    q("The artery at risk in supracondylar fracture of femur:", "Popliteal artery", "Femoral artery", "Anterior tibial artery", "Posterior tibial artery", "A", "Popliteal artery is closely related to posterior distal femur.", "HARD", "Textbook", "Popliteal artery"),
    q("Dorsalis pedis artery is a continuation of:", "Anterior tibial artery", "Posterior tibial artery", "Peroneal artery", "Popliteal artery", "A", "Anterior tibial artery continues as dorsalis pedis.", "EASY", "Textbook", "Arteries"),
    q("Nerve supply of adductor magnus:", "Obturator and sciatic", "Femoral only", "Obturator only", "Sciatic only", "A", "Adductor magnus has dual nerve supply.", "HARD", "Textbook", "Adductor magnus"),
    q("The ligament preventing posterior dislocation of tibia:", "PCL", "ACL", "MCL", "Popliteal", "A", "PCL prevents posterior displacement of tibia.", "MEDIUM", "Textbook", "PCL")
  ]],
  ["Thorax", [
    q("Sternal angle (angle of Louis) is at level of:", "T4-T5 disc", "T2-T3 disc", "T3-T4 disc", "T5-T6 disc", "A", "Sternal angle marks T4-T5 disc level.", "EASY", "Textbook", "Sternal angle"),
    q("Right recurrent laryngeal nerve hooks around:", "Right subclavian artery", "Arch of aorta", "Brachiocephalic trunk", "Right common carotid", "A", "Right RLN hooks around right subclavian artery.", "MEDIUM", "Textbook", "RLN"),
    q("Oblique fissure of lung corresponds to:", "T3 spine to 6th CCJ", "T4 spine to 2nd rib", "Sternal angle to 4th rib", "Clavicle to 8th rib", "A", "Oblique fissure runs from T3 spine to 6th costochondral junction.", "MEDIUM", "Textbook", "Lung fissures"),
    q("The structure crossing arch of aorta:", "Left phrenic nerve", "Right phrenic nerve", "Left vagus nerve", "Right vagus nerve", "A", "Left phrenic nerve crosses arch anteriorly.", "HARD", "Textbook", "Aorta relations"),
    q("Thoracic duct drains into:", "Left subclavian-IJV", "Right subclavian", "SVC", "Left brachiocephalic", "A", "Thoracic duct drains into left venous angle.", "EASY", "Textbook", "Thoracic duct"),
    q("Bronchopulmonary segment supplied by:", "Tertiary bronchus", "Secondary bronchus", "Primary bronchus", "Terminal bronchiole", "A", "Segment is supplied by a tertiary bronchus.", "MEDIUM", "Textbook", "Bronchus"),
    q("Commonest site of foreign body impaction in esophagus:", "Cricopharyngeus", "Aortic arch", "Left bronchus", "Diaphragmatic hiatus", "A", "Cricopharyngeus is the narrowest site.", "MEDIUM", "Textbook", "Esophagus"),
    q("Surface marking of apex of heart:", "Left 5th ICS, MCL", "Left 4th ICS", "Right 5th ICS", "Left 6th ICS", "A", "Apex beat is at left 5th ICS, midclavicular line.", "EASY", "Textbook", "Heart surface anatomy"),
    q("Right coronary artery supplies:", "SA node in 60%", "Left ventricle entirely", "Anterior septum", "Left atrium", "A", "RCA supplies SA node in 60% of cases.", "MEDIUM", "Textbook", "Coronary arteries"),
    q("Coarctation of aorta most commonly occurs:", "Distal to left subclavian", "Proximal to left subclavian", "At arch of aorta", "Descending aorta", "A", "Coarctation typically occurs distal to left subclavian.", "MEDIUM", "Textbook", "Coarctation"),
    q("Azygos vein drains into:", "SVC", "IVC", "Right brachiocephalic", "Right atrium", "A", "Azygos vein drains into the SVC.", "EASY", "Textbook", "Azygos vein"),
    q("All are posterior mediastinum contents EXCEPT:", "Heart", "Esophagus", "Thoracic duct", "Descending aorta", "A", "Heart is in the middle mediastinum.", "MEDIUM", "Textbook", "Mediastinum"),
    q("Needle thoracocentesis for tension pneumothorax done at:", "2nd ICS, MCL", "5th ICS, MAL", "4th ICS, MCL", "7th ICS, posterior", "A", "Emergency decompression at 2nd ICS, midclavicular line.", "MEDIUM", "Textbook", "Thoracocentesis"),
    q("First rib has groove for:", "Subclavian vessels", "Axillary vessels", "Brachial plexus", "Internal jugular", "A", "First rib has grooves for subclavian vessels.", "EASY", "Textbook", "Ribs"),
    q("Diaphragm main nerve supply:", "Phrenic (C3,4,5)", "Intercostal (T7-11)", "Subcostal (T12)", "Vagal", "A", "Phrenic nerve provides motor and sensory supply.", "EASY", "Textbook", "Diaphragm")
  ]],
  ["Abdomen", [
    q("McBurney's point is at:", "Junction of lat 1/3 and med 2/3 of ASIS-umbilicus line", "Midpoint of umbilicus-pubis", "Junction of med 1/3 and lat 2/3 of inguinal ligament", "2 inches above umbilicus", "A", "McBurney's point is surface marking for appendix base.", "EASY", "Textbook", "Appendix"),
    q("Hesselbach's triangle bounded by all EXCEPT:", "Inguinal ligament laterally", "Rectus abdominis medially", "Inferior epigastric laterally", "Conjoint tendon superiorly", "A", "Inguinal ligament is the inferior boundary.", "HARD", "Textbook", "Inguinal canal"),
    q("Direct inguinal hernia occurs:", "Medial to inferior epigastric", "Lateral to inferior epigastric", "Through deep ring", "Through femoral canal", "A", "Direct hernia passes medial to inferior epigastric vessels.", "MEDIUM", "Textbook", "Hernia"),
    q("Portal vein formed by union of:", "SMV and splenic vein", "IMV and splenic vein", "SMV and IMV", "Splenic and left gastric", "A", "Portal vein forms behind neck of pancreas.", "EASY", "Textbook", "Portal vein"),
    q("Calot's triangle contains:", "Cystic artery", "Common hepatic artery", "Portal vein", "Right hepatic duct", "A", "Calot's triangle contains cystic artery.", "MEDIUM", "Textbook", "Gallbladder"),
    q("Transpyloric plane of Addison is level of:", "L1 vertebra", "L2 vertebra", "L3 vertebra", "T12 vertebra", "A", "Transpyloric plane is at L1 level.", "MEDIUM", "Textbook", "Abdominal planes"),
    q("Porto-systemic anastomosis at lower esophagus involves:", "Left gastric and esophageal veins", "Superior and middle rectal", "Paraumbilical and superficial epigastric", "Colic and retroperitoneal", "A", "This causes esophageal varices.", "HARD", "Textbook", "Varices"),
    q("Meckel's diverticulum is remnant of:", "Vitello-intestinal duct", "Urachus", "Allantois", "Notochord", "A", "Meckel's is a remnant of the vitello-intestinal duct.", "EASY", "Textbook", "Meckel's"),
    q("Narrowest part of male urethra:", "External meatus", "Membranous", "Prostatic", "Navicular fossa", "A", "External urethral meatus is the narrowest part.", "HARD", "Textbook", "Urethra"),
    q("Pouch of Douglas is:", "Rectouterine pouch", "Vesicouterine pouch", "Rectovesical pouch", "Hepatorenal pouch", "A", "Rectouterine pouch is the most dependent peritoneal recess.", "EASY", "Textbook", "Peritoneum"),
    q("Blood supply of stomach along greater curvature:", "Gastroepiploic arteries", "Gastric arteries", "Short gastric", "Splenic", "A", "Supplied by right and left gastroepiploic arteries.", "MEDIUM", "Textbook", "Stomach"),
    q("Structures through aortic hiatus (T12):", "Aorta, thoracic duct, azygos", "Aorta, vagus, esophagus", "IVC, phrenic", "Aorta, sympathetic", "A", "Aortic hiatus transmits aorta, thoracic duct, azygos vein.", "MEDIUM", "Textbook", "Diaphragm"),
    q("Kidney related posteriorly to all EXCEPT:", "Liver", "Diaphragm", "Psoas major", "Quadratus lumborum", "A", "Liver is related anteriorly to right kidney.", "MEDIUM", "Textbook", "Kidney"),
    q("Spleen related to ribs EXCEPT:", "8th rib", "9th rib", "10th rib", "11th rib", "A", "Spleen is related to 9th, 10th, 11th ribs.", "MEDIUM", "Textbook", "Spleen"),
    q("Epiploic foramen anterior boundary:", "Free margin of lesser omentum", "IVC", "Caudate lobe", "First part of duodenum", "A", "Anterior boundary contains portal triad.", "HARD", "Textbook", "Omentum")
  ]],
  ["Head and Neck", [
    q("Middle meningeal artery enters skull through:", "Foramen spinosum", "Foramen ovale", "Foramen rotundum", "Foramen lacerum", "A", "Enters via foramen spinosum.", "EASY", "Textbook", "Skull foramina"),
    q("Facial nerve exits skull through:", "Stylomastoid foramen", "Foramen ovale", "Jugular foramen", "Foramen spinosum", "A", "Exits via stylomastoid foramen.", "EASY", "Textbook", "Facial nerve"),
    q("Bell's palsy is lesion of:", "LMN facial nerve", "UMN facial nerve", "Trigeminal nerve", "Glossopharyngeal", "A", "Bell's palsy is idiopathic LMN facial palsy.", "MEDIUM", "Textbook", "Bell's palsy"),
    q("Parotid duct opens opposite:", "Upper 2nd molar", "Lower 2nd molar", "Upper 1st molar", "Lower 1st molar", "A", "Opens into vestibule opposite upper 2nd molar.", "EASY", "Textbook", "Parotid gland"),
    q("Dangerous area of face drains into:", "Cavernous sinus", "Transverse sinus", "Sigmoid sinus", "Superior sagittal", "A", "Drains to cavernous sinus via ophthalmic veins.", "MEDIUM", "Textbook", "Cavernous sinus"),
    q("Tongue muscles supplied by hypoglossal EXCET:", "Palatoglossus", "Styloglossus", "Genioglossus", "Hyoglossus", "A", "Palatoglossus is supplied by vagus.", "MEDIUM", "Textbook", "Tongue"),
    q("Trotter's triad seen in:", "Nasopharyngeal carcinoma", "Laryngeal carcinoma", "Thyroid carcinoma", "Maxillary sinusitis", "A", "Triad: deafness, palatal palsy, trigeminal neuralgia.", "HARD", "Textbook", "Trotter's triad"),
    q("Taste from anterior 2/3 of tongue via:", "Chorda tympani", "Glossopharyngeal", "Lingual", "Hypoglossal", "A", "Chorda tympani carries taste.", "MEDIUM", "Textbook", "Taste"),
    q("Frey syndrome is complication of surgery on:", "Parotid gland", "Submandibular gland", "Thyroid gland", "Sublingual gland", "A", "Frey syndrome is gustatory sweating.", "HARD", "Textbook", "Frey syndrome"),
    q("External carotid artery branches:", "8", "6", "5", "10", "A", "ECA has 8 branches.", "MEDIUM", "Textbook", "ECA"),
    q("Muscle opening the jaw:", "Lateral pterygoid", "Medial pterygoid", "Masseter", "Temporalis", "A", "Lateral pterygoid depresses mandible.", "MEDIUM", "Textbook", "Mastication"),
    q("Cavernous sinus contains EXCEPT:", "V2 (Maxillary)", "ICA", "CN III", "CN IV", "A", "V2 is in the lateral wall, not sinus itself.", "HARD", "Textbook", "Cavernous sinus"),
    q("Killian's dehiscence located in:", "Inferior constrictor", "Middle constrictor", "Superior constrictor", "Cricopharyngeus", "A", "Gap in inferior constrictor.", "HARD", "Textbook", "Pharynx"),
    q("Thyroid gland develops from:", "Foramen cecum", "1st pouch", "2nd arch", "3rd pouch", "A", "Develops from foramen cecum via thyroglossal duct.", "MEDIUM", "Textbook", "Thyroid"),
    q("Nerve supply of platysma:", "Cervical branch of facial", "Great auricular", "Transverse cervical", "Marginal mandibular", "A", "Supplied by cervical branch of facial nerve.", "MEDIUM", "Textbook", "Facial nerve")
  ]],
  ["Neuroanatomy", [
    q("Cerebrospinal fluid is produced primarily by:", "Choroid plexus", "Arachnoid granulations", "Pia mater", "Dura mater", "A", "Choroid plexus in the ventricles produces CSF.", "EASY", "Textbook", "CSF pathway"),
    q("Broca's area is located in the:", "Inferior frontal gyrus", "Superior temporal gyrus", "Precentral gyrus", "Postcentral gyrus", "A", "Broca's motor speech area is in the inferior frontal gyrus of the dominant hemisphere.", "MEDIUM", "Textbook", "Cerebral cortex"),
    q("The primary visual cortex is located in the:", "Occipital lobe", "Temporal lobe", "Parietal lobe", "Frontal lobe", "A", "Area 17 is located in the occipital lobe around the calcarine fissure.", "EASY", "Textbook", "Visual cortex"),
    q("Wernicke's aphasia results from damage to the:", "Superior temporal gyrus", "Inferior frontal gyrus", "Angular gyrus", "Supramarginal gyrus", "A", "Wernicke's sensory speech area is in the posterior part of the superior temporal gyrus.", "MEDIUM", "Textbook", "Aphasia"),
    q("The decussation of the pyramids occurs in the:", "Medulla oblongata", "Pons", "Midbrain", "Spinal cord", "A", "Motor fibers cross at the pyramidal decussation in the lower medulla.", "EASY", "Textbook", "Medulla"),
    q("Which cranial nerve emerges from the dorsal aspect of the brainstem?", "Trochlear nerve (CN IV)", "Trigeminal nerve (CN V)", "Oculomotor nerve (CN III)", "Abducens nerve (CN VI)", "A", "Only the trochlear nerve emerges from the dorsal surface of the midbrain.", "MEDIUM", "Textbook", "Cranial nerves"),
    q("The major relay station for sensory information to the cerebral cortex is:", "Thalamus", "Hypothalamus", "Basal ganglia", "Cerebellum", "A", "The thalamus relays all sensory modalities except olfaction to the cortex.", "EASY", "Textbook", "Thalamus"),
    q("Parkinson's disease is associated with degeneration of neurons in the:", "Substantia nigra", "Subthalamic nucleus", "Globus pallidus", "Red nucleus", "A", "Dopaminergic depletion from pars compacta of substantia nigra causes Parkinson's.", "MEDIUM", "Textbook", "Basal ganglia"),
    q("The artery usually involved in an epidural hematoma is the:", "Middle meningeal artery", "Middle cerebral artery", "Anterior cerebral artery", "Bridging veins", "A", "Rupture of MMA at the pterion causes epidural hematoma.", "MEDIUM", "Textbook", "Meninges"),
    q("The representation of the lower limb in the motor homunculus is supplied by:", "Anterior cerebral artery", "Middle cerebral artery", "Posterior cerebral artery", "Anterior choroidal artery", "A", "ACA supplies the medial surface where lower limb represents.", "HARD", "Textbook", "Cerebral circulation")
  ]],
  ["Embryology General", [
    q("Fertilization usually occurs in the:", "Ampulla of the uterine tube", "Infundibulum", "Isthmus", "Uterine cavity", "A", "Ampulla is the widest part where fertilization typically occurs.", "EASY", "Textbook", "Fertilization"),
    q("The notochord induces the formation of the:", "Neural plate", "Somites", "Endoderm", "Gut tube", "A", "Notochord signals the overlying ectoderm to form the neural plate.", "MEDIUM", "Textbook", "Neurulation"),
    q("The first germ layer to form during gastrulation is:", "Endoderm", "Mesoderm", "Ectoderm", "Neuroectoderm", "A", "Epiblast cells displace hypoblast to form definitive endoderm first.", "MEDIUM", "Textbook", "Gastrulation"),
    q("Meckel's cartilage is a derivative of which pharyngeal arch?", "First arch", "Second arch", "Third arch", "Fourth arch", "A", "First arch cartilage forms malleus, incus, and sphenomandibular ligament.", "MEDIUM", "Textbook", "Pharyngeal arches"),
    q("The thyroid gland develops mainly from the:", "Foramen cecum", "Second pharyngeal pouch", "Third pharyngeal pouch", "Neural crest", "A", "An endodermal downgrowth from the foramen cecum forms the thyroid.", "EASY", "Textbook", "Thyroid development"),
    q("Tetralogy of Fallot is a defect in the development of the:", "Aorticopulmonary septum", "Atrial septum", "Ventricular muscular septum", "Endocardial cushions", "A", "Anterior displacement of the conotruncal septum causes TOF.", "HARD", "Textbook", "Heart development"),
    q("The paramesonephric (Mullerian) ducts in females develop into all EXCEPT:", "Lower 1/3 of vagina", "Uterus", "Fallopian tubes", "Upper 2/3 of vagina", "A", "Lower 1/3 of vagina develops from the urogenital sinus.", "MEDIUM", "Textbook", "Genital ducts"),
    q("Cleft lip is caused by failure of fusion of:", "Maxillary and medial nasal prominences", "Two medial nasal prominences", "Maxillary and lateral nasal prominences", "Mandibular prominences", "A", "Failure of fusion causes anterior cleft anomalies.", "MEDIUM", "Textbook", "Facial development"),
    q("The kidney (metanephros) begins to produce urine by:", "Week 12", "Week 4", "Week 8", "Week 20", "A", "Urine production starts around weeks 10-12 to contribute to amniotic fluid.", "MEDIUM", "Textbook", "Renal development"),
    q("Which structure is a derivative of the midgut?", "Appendix", "Spleen", "Stomach", "Descending colon", "A", "Appendix, cecum, ascending colon are midgut derivatives.", "EASY", "Textbook", "Gut development")
  ]],
  ["Histology", [
    q("Transitional epithelium (urothelium) is characteristically found in the:", "Urinary bladder", "Trachea", "Esophagus", "Epidermis", "A", "Urothelium lines the urinary tract from renal calyces to proximal urethra.", "EASY", "Textbook", "Epithelium"),
    q("Pseudostratified ciliated columnar epithelium lines the:", "Trachea", "Small intestine", "Vagina", "Blood vessels", "A", "Respiratory epithelium lines most of the conducting airways.", "EASY", "Textbook", "Epithelium"),
    q("Which of the following cells produce myelin in the central nervous system?", "Oligodendrocytes", "Schwann cells", "Astrocytes", "Microglia", "A", "Oligodendrocytes myelinate CNS axons; Schwann cells myelinate PNS axons.", "MEDIUM", "Textbook", "Neuroglia"),
    q("The functional unit of compact bone is the:", "Osteon (Haversian system)", "Trabecula", "Lacuna", "Canaliculus", "A", "The osteon consists of concentric lamellae around a central canal.", "EASY", "Textbook", "Bone histology"),
    q("Features of cardiac muscle include all EXCEPT:", "Multinucleated cells", "Intercalated discs", "Striations", "Branching fibers", "A", "Cardiac muscle cells typically have a single central nucleus.", "MEDIUM", "Textbook", "Muscle histology"),
    q("Nissl bodies in neurons represent:", "Rough endoplasmic reticulum", "Mitochondria", "Lysosomes", "Golgi apparatus", "A", "Nissl substance is granular RER involved in protein synthesis.", "MEDIUM", "Textbook", "Neuron structure"),
    q("The principal cell type responsible for producing the extracellular matrix of cartilage is the:", "Chondrocyte", "Osteoblast", "Fibroblast", "Macrophage", "A", "Chondrocytes secrete and maintain the cartilage matrix.", "EASY", "Textbook", "Cartilage"),
    q("Stratified squamous non-keratinized epithelium is found in the:", "Esophagus", "Skin epidermis", "Stomach", "Urinary bladder", "A", "Moist surfaces subject to friction like the esophagus and vagina have this.", "MEDIUM", "Textbook", "Epithelium"),
    q("Which formed element of blood lacks a nucleus?", "Mature erythrocyte", "Lymphocyte", "Monocyte", "Neutrophil", "A", "RBCs lose their nucleus during maturation to maximize hemoglobin content.", "EASY", "Textbook", "Blood"),
    q("Hassall's corpuscles are a histological feature of the:", "Thymus", "Spleen", "Lymph node", "Tonsil", "A", "Hassall's corpuscles are found in the thymic medulla.", "HARD", "Textbook", "Lymphatic organs")
  ]],
  ["Osteology", [
    q("The longest and heaviest bone in the body is the:", "Femur", "Tibia", "Humerus", "Fibula", "A", "The femur is the longest and strongest bone.", "EASY", "Textbook", "General osteology"),
    q("Which of the following is a sesamoid bone?", "Patella", "Pisiform", "Both A and B", "Neither", "A", "Patella (largest) and pisiform are sesamoid bones developing within tendons.", "MEDIUM", "Textbook", "Bone types"),
    q("The primary ossification center for long bones typically appears in the:", "Diaphysis", "Epiphysis", "Metaphysis", "Articular cartilage", "A", "Primary ossification occurs in the diaphysis during fetal life.", "MEDIUM", "Textbook", "Ossification"),
    q("The lateral malleolus is a feature of which bone?", "Fibula", "Tibia", "Talus", "Calcaneus", "A", "The distal end of the fibula forms the lateral malleolus.", "EASY", "Textbook", "Lower limb bones"),
    q("The odontoid process (dens) is a distinguishing feature of the:", "Axis (C2)", "Atlas (C1)", "Vertebra prominens (C7)", "Occipital bone", "A", "The dens projects upward from the body of the axis.", "EASY", "Textbook", "Vertebrae"),
    q("Which bones form the hard palate?", "Maxilla and Palatine", "Maxilla and Sphenoid", "Palatine and Vomer", "Maxilla and Zygomatic", "A", "Palatine process of maxilla and horizontal plate of palatine bone.", "MEDIUM", "Textbook", "Skull"),
    q("The acetabulum is formed by the union of:", "Ilium, ischium, and pubis", "Ilium and ischium only", "Ischium and pubis only", "Ilium and sacrum", "A", "All three innominate bones contribute to the acetabulum.", "EASY", "Textbook", "Pelvic bone"),
    q("The coracoid process is a feature of the:", "Scapula", "Clavicle", "Humerus", "Ulna", "A", "The coracoid process projects anteriorly from the scapula.", "EASY", "Textbook", "Upper limb bones"),
    q("Fracture of the surgical neck of the humerus endangers the:", "Axillary nerve", "Radial nerve", "Ulnar nerve", "Median nerve", "A", "Axillary nerve and posterior circumflex humeral artery lie here.", "MEDIUM", "Textbook", "Humerus fractures"),
    q("The pterion is an important landmark on the skull. It overlies the:", "Anterior branch of middle meningeal artery", "Superior sagittal sinus", "Transverse sinus", "Middle cerebral artery main trunk", "A", "The pterion overlies the anterior division of the MMA.", "MEDIUM", "Textbook", "Skull landmarks")
  ]],
  ["Genetics and Molecular Biology", [
    q("Down syndrome is most commonly caused by:", "Trisomy 21", "Trisomy 18", "Trisomy 13", "Monosomy X", "A", "Trisomy 21 due to meiotic nondisjunction is the most common cause.", "EASY", "Textbook", "Chromosomal disorders"),
    q("Klinefelter syndrome has the karyotype:", "47, XXY", "45, X", "47, XYY", "47, XXX", "A", "47, XXY is the classic karyotype for Klinefelter syndrome.", "EASY", "Textbook", "Sex chromosome disorders"),
    q("In DNA, adenine pairs with thymine via:", "Two hydrogen bonds", "Three hydrogen bonds", "Phosphodiester bonds", "Covalent bonds", "A", "A-T base pairing involves 2 hydrogen bonds; G-C involves 3.", "MEDIUM", "Textbook", "DNA structure"),
    q("The process of synthesizing RNA from a DNA template is called:", "Transcription", "Translation", "Replication", "Reverse transcription", "A", "Transcription is RNA synthesis catalyzed by RNA polymerase.", "EASY", "Textbook", "Central dogma"),
    q("A missense mutation results in:", "A different amino acid", "A premature stop codon", "No change in amino acid", "A frameshift", "A", "Missense mutations substitute one amino acid for another.", "MEDIUM", "Textbook", "Mutations"),
    q("Which phase of the cell cycle involves DNA replication?", "S phase", "G1 phase", "G2 phase", "M phase", "A", "DNA synthesis occurs during the S (synthetic) phase.", "EASY", "Textbook", "Cell cycle"),
    q("Turner syndrome usually presents with which karyotype?", "45, X", "47, XXY", "46, XX", "47, XXX", "A", "Monosomy X is the hallmark of Turner syndrome.", "EASY", "Textbook", "Chromosomal disorders"),
    q("The anticodon is found on which molecule?", "tRNA", "mRNA", "rRNA", "DNA", "A", "tRNA has an anticodon that base pairs with the mRNA codon.", "MEDIUM", "Textbook", "Translation"),
    q("Huntington's disease exhibits a genetic phenomenon where the age of onset decreases in successive generations. This is called:", "Anticipation", "Imprinting", "Incomplete penetrance", "Pleiotropy", "A", "Trinucleotide repeat expansion causes anticipation.", "HARD", "Textbook", "Genetics principles"),
    q("Prader-Willi and Angelman syndromes are classic examples of:", "Genomic imprinting", "Mitochondrial inheritance", "X-linked recessive inheritance", "Trinucleotide repeat expansion", "A", "Imprinting involves differential expression depending on the parent of origin.", "HARD", "Textbook", "Epigenetics")
  ]]
];

writeSubject("Anatomy", chapters, "anatomy.json");
