const { q, writeSubject } = require('./qgen_helper');

const chapters = [
  ["Ear", [
    q("The most common cause of conductive hearing loss in children is:", "Otitis Media with Effusion (Glue Ear)", "Otosclerosis", "Impacted cerumen", "Congenital cholesteatoma", "A", "Chronic fluid behind the tympanic membrane dampens sound transmission.", "EASY", "Textbook", "Hearing Loss"),
    q("A 30-year-old female presents with bilateral, slowly progressive, pure conductive hearing loss. She has a strong family history of deafness. Tympanic membrane is normal. Diagnosis?", "Otosclerosis", "Presbycusis", "Meniere's disease", "Acoustic Neuroma", "A", "Fixation of the stapes footplate to the oval window causes this inherited condition.", "MEDIUM", "Textbook", "Hearing Loss"),
    q("A classic Weber test finding in a patient with a unilateral right-sided conductive hearing loss (e.g., impacted wax) is:", "Sound lateralizes to the right (affected) ear", "Sound lateralizes to the left (normal) ear", "Sound is heard equally in both ears", "No sound is heard at all", "A", "Conductive loss in the affected ear prevents ambient noise masking, making bone conduction louder.", "EASY", "Textbook", "Tuning Fork Tests"),
    q("A patient with Meniere's disease classically presents with the triad of:", "Episodic vertigo, fluctuating sensorineural hearing loss, and tinnitus", "Constant vertigo, conductive hearing loss, and ear discharge", "Facial palsy, vertigo, and otalgia", "Conductive hearing loss, tinnitus, and a normal tympanic membrane", "A", "Endolymphatic hydrops causes these hallmark recurrent symptoms.", "EASY", "Textbook", "Vertigo"),
    q("A patient presents with sudden onset of severe, continuous vertigo, nausea, and vomiting without any hearing loss or tinnitus occurring days after a viral upper respiratory infection. Diagnosis?", "Vestibular Neuritis", "Meniere's Disease", "Acoustic Neuroma", "Benign Paroxysmal Positional Vertigo (BPPV)", "A", "Vestibular neuritis selectively affects the vestibular nerve without involving the cochlea.", "MEDIUM", "Textbook", "Vertigo"),
    q("The Dix-Hallpike maneuver is used to diagnose:", "Benign Paroxysmal Positional Vertigo (BPPV)", "Meniere's disease", "Vestibular Schwannoma", "Otosclerosis", "A", "It provokes diagnostic torsional nystagmus by stimulating the posterior semicircular canal.", "EASY", "Textbook", "Vertigo"),
    q("Which of the following is a dangerous, locally destructive lesion in the middle ear characterized by stratified squamous epithelium and keratin debris?", "Cholesteatoma", "Glomus tumor", "Otosclerosis", "Tympanosclerosis", "A", "Cholesteatomas can erode the ossicles, facial nerve, and even the skull base.", "EASY", "Textbook", "Middle Ear Disease"),
    q("A foul-smelling, scanty, purulent ear discharge associated with a marginal perforation of the tympanic membrane strongly suggests:", "Atticoantral chronic suppurative otitis media (with cholesteatoma)", "Tubotympanic chronic suppurative otitis media (safe type)", "Acute otitis media", "Otitis externa", "A", "The 'unsafe' type involves bone destruction and requires surgical management.", "MEDIUM", "Textbook", "Middle Ear Disease"),
    q("Acoustic neuromas (Vestibular Schwannomas) most commonly arise from the:", "Vestibular division of the 8th cranial nerve", "Cochlear division of the 8th cranial nerve", "Facial nerve (7th cranial nerve)", "Trigeminal nerve (5th cranial nerve)", "A", "They cause unilateral sensorineural hearing loss, tinnitus, and eventual facial/trigeminal symptoms.", "EASY", "Textbook", "Tumors"),
    q("Bilateral acoustic neuromas are a hallmark finding of which genetic condition?", "Neurofibromatosis Type 2 (NF2)", "Neurofibromatosis Type 1 (NF1)", "Tuberous Sclerosis", "Von Hippel-Lindau disease", "A", "NF2 is characterized by multi-system tumors, primarily bilateral vestibular schwannomas.", "EASY", "Textbook", "Genetic Syndromes")
  ]],
  ["Nose and Paranasal Sinuses", [
    q("The most common site of severe, anterior epistaxis (nosebleed) is:", "Little's Area (Kiesselbach's plexus)", "Woodruff's plexus", "Sphenopalatine artery directly", "Ethmoidal arteries", "A", "This highly vascular area on the anterior nasal septum is prone to digital trauma.", "EASY", "Textbook", "Epistaxis"),
    q("A posterior epistaxis in an elderly, hypertensive patient is most likely to originate from:", "Woodruff's plexus (sphenopalatine artery branches)", "Little's Area", "Anterior ethmoidal artery", "Superior labial artery", "A", "Posterior bleeds arterial and severe, requiring posterior packing or embolization.", "MEDIUM", "Textbook", "Epistaxis"),
    q("The most frequently involved paranasal sinus in acute bacterial rhinosinusitis in adults is the:", "Maxillary sinus", "Ethmoid sinus", "Frontal sinus", "Sphenoid sinus", "A", "Its ostium drains superiorly against gravity in the upright position, making it susceptible to stasis.", "EASY", "Textbook", "Sinusitis"),
    q("A teenage boy presents with recurrent, severe, unprovoked epistaxis and a progressively enlarging nasal mass causing obstruction. The likely diagnosis is:", "Juvenile Nasopharyngeal Angiofibroma", "Nasal polyp", "Inverted papilloma", "Squamous cell carcinoma", "A", "JNA is a highly vascular, locally aggressive benign tumor almost exclusive to adolescent males.", "EASY", "Textbook", "Nasal Tumors"),
    q("Unilateral, foul-smelling, purulent nasal discharge in a young child strongly suggests:", "A foreign body in the nasal cavity", "Acute viral rhinitis", "Allergic rhinitis", "Adenoid hypertrophy", "A", "Always suspect a foreign body when discharge is unilateral and foul-smelling in a child.", "EASY", "Textbook", "Pediatric ENT"),
    q("Nasal polyps are typically benign inflammatory outgrowths that appear classically as:", "Pale, semi-translucent, non-tender, 'peeled-grape' masses", "Red, painful, highly vascular masses", "Hard, bony outgrowths from the septum", "Ulcerated, bleeding lesions on the turbinates", "A", "Polyps lack sensory innervation (not painful to probe) and are often bilateral in chronic rhinosinusitis.", "EASY", "Textbook", "Nasal Polyps"),
    q("Samter's Triad includes nasal polyps, asthma, and a severe hypersensitivity to:", "Aspirin (salicylates)", "Penicillin", "Peanuts", "Dust mites", "A", "Aspirin-Exacerbated Respiratory Disease (AERD) causes severe rhinitis/asthma attacks upon NSAID ingestion.", "MEDIUM", "Textbook", "Nasal Polyps"),
    q("The characteristic symptom of an antrochoanal polyp (which arises from the maxillary sinus and prolapses into the choana) is:", "Sided, progressively worsening, marked nasal obstruction often alternating with side but primarily unilateral", "Severe recurrent epistaxis", "Anosmia without obstruction", "Massive cheek swelling and facial pain", "A", "Unlike allergic ethmoidal polyps, antrochoanal polyps grow remarkably large, causing unilateral mechanical blockage.", "HARD", "Textbook", "Nasal Polyps"),
    q("In a patient with suspected CSF rhinorrhea following a base of skull fracture, the presence of which specific marker in the nasal fluid confirms it is cerebrospinal fluid?", "Beta-2 transferrin", "Glucose", "High protein concentration", "Amylase", "A", "Beta-2 transferrin is highly unique and specific to CSF and perilymph.", "MEDIUM", "Textbook", "Trauma"),
    q("The 'danger area of the face' (from the upper lip to the nasion) communicates intracranially, posing a significant risk for:", "Cavernous sinus thrombosis", "Meningitis directly across the cribriform plate", "Brain abscess exclusively via arterial spread", "Epidural hematoma", "A", "Infections here can spread retrogradely via valveless facial veins into the cavernous sinus.", "MEDIUM", "Textbook", "Anatomy/Infections")
  ]],
  ["Throat", [
    q("The most common cause of acute pharyngotonsillitis in children (excluding viral causes) is:", "Group A Beta-Hemolytic Streptococcus (S. pyogenes)", "Staphylococcus aureus", "Haemophilus influenzae", "Neisseria gonorrhoeae", "A", "Strep throat requires antibiotic treatment (usually Penicillin) to prevent rheumatic fever.", "EASY", "Textbook", "Pharyngitis"),
    q("A young adult presents with extremely severe sore throat, odynophagia (pain on swallowing), a 'hot potato' voice, and trismus (inability to open mouth). Examination shows unilateral tonsillar swelling shifting the uvula across the midline. Diagnosis?", "Peritonsillar Abscess (Quinsy)", "Acute Epiglottitis", "Infectious Mononucleosis", "Retropharyngeal Abscess", "A", "A collection of pus between the tonsil capsule and the superior constrictor muscle.", "EASY", "Textbook", "Infections"),
    q("Which childhood condition prevents acute respiratory distress characterized by drooling, dysphagia, distress, and a 'thumb sign' on a lateral neck X-ray?", "Acute Epiglottitis", "Croup (Laryngotracheobronchitis)", "Bacterial Tracheitis", "Foreign body aspiration", "A", "Classically caused by H. influenzae type B; true medical emergency requiring airway protection.", "MEDIUM", "Textbook", "Pediatric Emergencies"),
    q("The most common benign neoplastic cause of hoarseness in adult singers or public speakers (bilateral professional voice users) is:", "Vocal cord nodules ('Singer's nodules')", "Vocal cord polyps", "Laryngeal papillomatosis", "Squamous cell carcinoma of the true cord", "A", "Nodules form at the junction of the anterior 1/3 and posterior 2/3 of the vocal cords due to chronic trauma.", "EASY", "Textbook", "Voice Disorders"),
    q("A unilateral vocal cord polyp is typically the result of:", "A single episode of acute vocal trauma or hemorrhage", "Chronic, long-term voice abuse resulting in bilateral friction", "Human Papillomavirus (HPV) infection", "Smoking and heavy alcohol use over decades", "A", "Unlike nodules, polyps are usually unilateral and stem from distinct traumatic events.", "MEDIUM", "Textbook", "Voice Disorders"),
    q("The most reliable early symptom of laryngeal cancer (especially glottic carcinoma) is:", "Progressive hoarseness of voice persisting for more than 2-3 weeks", "Severe dysphagia and weight loss", "Hemoptysis", "A rapidly enlarging, tender neck mass", "A", "Any adult (especially a smoker) with persistent hoarseness needs a laryngoscopy to rule out cancer.", "EASY", "Textbook", "Head and Neck Cancer"),
    q("Nasopharyngeal carcinoma (NPC) is uniquely strongly associated with which viral infection?", "Epstein-Barr Virus (EBV)", "Human Papillomavirus (HPV)", "Hepatitis C Virus", "Cytomegalovirus (CMV)", "A", "NPC is very common in certain populations (e.g., southern China) and EBV DNA is found in the tumor.", "EASY", "Textbook", "Head and Neck Cancer"),
    q("A 35-year-old male from Southeast Asia presents with unilateral hearing loss, tinnitus, a painless enlarged cervical lymph node, and epistaxis. A mass is found in the Fossa of Rosenmüller. Diagnosis is most likely:", "Nasopharyngeal Carcinoma", "Acoustic Neuroma", "Otosclerosis", "Juvenile Nasopharyngeal Angiofibroma", "A", "The 'Fossa of Rosenmüller' is the most common site of origin for NPC.", "MEDIUM", "Textbook", "Head and Neck Cancer"),
    q("Ludwig's Angina is a rapidly spreading, potentially life-threatening cellulitis classically involving the:", "Submandibular, sublingual, and submental spaces bilaterally", "Retropharyngeal space", "Peritonsillar space unilaterally", "Pretracheal space", "A", "Usually originates from an infected lower molar tooth, pushing the tongue back and risking asphyxiation.", "MEDIUM", "Textbook", "Neck Infections"),
    q("During a total thyroidectomy, the recurrent laryngeal nerve is inadvertently severed unilaterally. The patient will immediately present with:", "Hoarseness", "Stridor and severe respiratory distress", "Aphonia (complete loss of voice)", "Inability to swallow liquids", "A", "The unaffected cord compensates partially, but voice remains weak/breathy. Bilateral section causes stridor.", "EASY", "Textbook", "Surgical Complications")
  ]]
];

writeSubject("ENT", chapters, "ent.json");
