const { q, writeSubject } = require('./qgen_helper');

const chapters = [
  ["General Physiology", [
    q("The primary active transport mechanism in most mammalian cells is the:", "Na+/K+ ATPase", "Ca2+ ATPase", "H+/K+ ATPase", "ABC transporter", "A", "Na+/K+ ATPase maintains the resting membrane potential and cell volume.", "EASY", "Textbook", "Membrane transport"),
    q("In a normal resting cell, the cell membrane is most permeable to:", "Potassium", "Sodium", "Calcium", "Chloride", "A", "Resting membrane is 50-100 times more permeable to K+ due to leak channels.", "EASY", "Textbook", "Resting membrane potential"),
    q("Secondary active transport typically relies on the electrochemical gradient of:", "Sodium", "Potassium", "Calcium", "Hydrogen", "A", "The Na+ gradient created by Na+/K+ ATPase drives most secondary active transport.", "MEDIUM", "Textbook", "Membrane transport"),
    q("The Gibbs-Donnan effect helps explain the uneven distribution of:", "Diffusible ions across a membrane containing non-diffusible proteins", "Water molecules across a semipermeable membrane", "Lipid-soluble substances", "Gases in blood", "A", "Non-diffusible negatively charged proteins limit the diffusion of other ions.", "HARD", "Textbook", "Gibbs-Donnan"),
    q("Apoptosis is characterized by all EXCEPT:", "Inflammatory response", "Cell shrinkage", "Chromatin condensation", "Phagocytosis of apoptotic bodies", "A", "Apoptosis is programmed cell death and typically does not elicit inflammation.", "MEDIUM", "Textbook", "Cell death"),
    q("Which of the following cellular junctions prevents paracellular transport?", "Tight junctions (Zonula occludens)", "Gap junctions", "Desmosomes", "Hemidesmosomes", "A", "Tight junctions seal adjacent cells together.", "EASY", "Textbook", "Cell junctions"),
    q("The Nernst equation is used to calculate:", "Equilibrium potential for a single ion", "Resting membrane potential for all ions", "Osmotic pressure", "Action potential amplitude", "A", "Nernst equation determines the potential at which there is no net movement of a specific ion.", "MEDIUM", "Textbook", "Nernst equation"),
    q("Facilitated diffusion differs from simple diffusion because it:", "Exhibits saturation kinetics (Vmax)", "Requires ATP", "Moves substances against their gradient", "Does not require a carrier", "A", "Carrier proteins in facilitated diffusion can become saturated.", "EASY", "Textbook", "Membrane transport"),
    q("The major intracellular cation is:", "Potassium", "Sodium", "Calcium", "Magnesium", "A", "Potassium is the most abundant intracellular cation.", "EASY", "Textbook", "Body fluids"),
    q("Which receptor type is characterized by 7 transmembrane domains?", "G-protein coupled receptors", "Tyrosine kinase receptors", "Ligand-gated ion channels", "Nuclear receptors", "A", "GPCRs classically have 7 transmembrane alpha helices.", "MEDIUM", "Textbook", "Receptors")
  ]],
  ["Nerve Muscle Physiology", [
    q("The absolute refractory period of a nerve action potential is primarily due to:", "Inactivation of voltage-gated Na+ channels", "Opening of voltage-gated K+ channels", "Activity of the Na+/K+ pump", "Depletion of extracellular Na+", "A", "Inactivated Na+ channels cannot open regardless of stimulus strength.", "MEDIUM", "Textbook", "Action potential"),
    q("Myelin increases the conduction velocity of nerve fibers by:", "Increasing membrane resistance and decreasing capacitance", "Decreasing membrane resistance", "Increasing intracellular resistance", "Increasing membrane capacitance", "A", "Myelin insulates the axon, reducing current leak and capacitance.", "HARD", "Textbook", "Saltatory conduction"),
    q("In skeletal muscle, the calcium binding protein that initiates contraction is:", "Troponin C", "Calmodulin", "Tropomyosin", "Myosin light chain kinase", "A", "Calcium binds to Troponin C, moving tropomyosin away from myosin-binding sites.", "EASY", "Textbook", "Muscle contraction"),
    q("The neurotransmitter released at the neuromuscular junction is:", "Acetylcholine", "Norepinephrine", "Dopamine", "Serotonin", "A", "Ach is the universally used neurotransmitter at the mammalian NMJ.", "EASY", "Textbook", "NMJ"),
    q("Miniature end-plate potentials (MEPPs) represent the:", "Release of a single quantum of acetylcholine", "Threshold potential for an action potential", "Summation of multiple action potentials", "Action of cholinesterase", "A", "MEPPs are subthreshold depolarizations from spontaneous release of Ach vesicles.", "MEDIUM", "Textbook", "Synaptic transmission"),
    q("In smooth muscle, calcium binds to which protein to initiate contraction?", "Calmodulin", "Troponin C", "Tropomyosin", "Actin", "A", "Smooth muscle lacks troponin; Ca2+ binds calmodulin to activate MLCK.", "MEDIUM", "Textbook", "Smooth muscle"),
    q("The A-band of a sarcomere contains:", "Both thick and thin filaments", "Only thick filaments", "Only thin filaments", "Z-discs", "A", "The A-band corresponds to the entire length of the myosin thick filaments, overlapping with actin.", "MEDIUM", "Textbook", "Sarcomere"),
    q("Tetanus in skeletal muscle occurs due to:", "Temporal summation of twitches", "Spatial summation of motor units", "Exhaustion of ATP", "Depletion of acetylcholine", "A", "High frequency stimulation prevents relaxation between twitches.", "MEDIUM", "Textbook", "Tetanus"),
    q("Rigor mortis occurs after death because of:", "Lack of ATP to detach myosin from actin", "Massive release of calcium from SR", "Depletion of acetylcholine", "Denaturation of muscle proteins", "A", "ATP is required for the detachment of the cross-bridge cycle.", "EASY", "Textbook", "Cross-bridge cycle"),
    q("Which nerve fiber type has the fastest conduction velocity?", "A-alpha", "A-beta", "B fibers", "C fibers", "A", "A-alpha fibers are the largest and heavily myelinated (e.g., motor to skeletal muscle).", "EASY", "Textbook", "Nerve fibers")
  ]],
  ["Blood", [
    q("The most abundant plasma protein is:", "Albumin", "Globulin", "Fibrinogen", "Prothrombin", "A", "Albumin constitutes about 60% of total plasma protein and maintains oncotic pressure.", "EASY", "Textbook", "Plasma proteins"),
    q("Iron is transported in the blood bound to:", "Transferrin", "Ferritin", "Hemosiderin", "Haptoglobin", "A", "Transferrin transports iron, while ferritin is the primary intracellular storage form.", "MEDIUM", "Textbook", "Iron metabolism"),
    q("The lifespan of a normal red blood cell is approximately:", "120 days", "60 days", "10 days", "30 days", "A", "RBCs live for about 120 days before being destroyed by the spleen.", "EASY", "Textbook", "Erythrocytes"),
    q("Which blood type is considered the universal donor for packed RBCs?", "O negative", "AB positive", "O positive", "AB negative", "A", "Type O negative lacks A, B, and Rh antigens on the red cell surface.", "EASY", "Textbook", "Blood groups"),
    q("Erythropoietin is primarily produced by the:", "Kidneys", "Liver", "Bone marrow", "Spleen", "A", "Peritubular interstitial cells of the kidney produce EPO in response to hypoxia.", "EASY", "Textbook", "Erythropoiesis"),
    q("The extrinsic pathway of the coagulation cascade is initiated by:", "Tissue factor (Factor III)", "Contact activation", "Factor XII", "Factor VIII", "A", "Tissue trauma exposes Tissue Factor which binds Factor VII.", "MEDIUM", "Textbook", "Coagulation"),
    q("Vitamin K is required for the synthesis of which coagulation factors?", "II, VII, IX, X", "I, II, V, VIII", "VIII, IX, XI, XII", "XI, XII, Prekallikrein", "A", "Vitamin K is a cofactor for gamma-carboxylation of factors 2, 7, 9, 10, Protein C, and S.", "EASY", "Textbook", "Coagulation"),
    q("Plasminogen is converted to active plasmin by:", "Tissue plasminogen activator (tPA)", "Thrombin", "Factor XIII", "Fibrin", "A", "tPA is the physiological activator of the fibrinolytic system.", "MEDIUM", "Textbook", "Fibrinolysis"),
    q("Which leukocyte is the most abundant in a normal peripheral blood smear?", "Neutrophil", "Lymphocyte", "Monocyte", "Eosinophil", "A", "Neutrophils make up 50-70% of circulating WBCs in adults.", "EASY", "Textbook", "Leukocytes"),
    q("Hemolytic disease of the newborn (Erythroblastosis fetalis) usually involves:", "Rh negative mother and Rh positive fetus", "Rh positive mother and Rh negative fetus", "ABO incompatibility", "Rh positive mother and Rh positive fetus", "A", "Maternal anti-D antibodies cross the placenta and destroy fetal Rh+ RBCs.", "MEDIUM", "Textbook", "Blood groups")
  ]],
  ["Cardiovascular System", [
    q("The normal pacemaker of the heart is the:", "Sinoatrial (SA) node", "Atrioventricular (AV) node", "Bundle of His", "Purkinje fibers", "A", "The SA node has the fastest intrinsic rate of spontaneous depolarization.", "EASY", "Textbook", "Cardiac conduction"),
    q("In an ECG, the QRS complex represents:", "Ventricular depolarization", "Atrial depolarization", "Ventricular repolarization", "Atrial repolarization", "A", "The QRS complex corresponds to the spread of electrical impulse through the ventricles.", "EASY", "Textbook", "ECG"),
    q("The first heart sound (S1) is caused by the closure of:", "Atrioventricular (Mitral and Tricuspid) valves", "Semilunar (Aortic and Pulmonary) valves", "Foramen ovale", "Ductus arteriosus", "A", "S1 marks the beginning of ventricular systole.", "EASY", "Textbook", "Cardiac cycle"),
    q("Cardiac output is the product of:", "Heart rate and stroke volume", "Blood pressure and heart rate", "Stroke volume and peripheral resistance", "Heart rate and ejection fraction", "A", "CO = HR x SV (Normal resting CO is approx. 5 L/min).", "EASY", "Textbook", "Cardiac output"),
    q("According to the Frank-Starling law of the heart, an increase in end-diastolic volume leads to:", "An increase in stroke volume", "A decrease in contractility", "A decrease in heart rate", "An increase in peripheral resistance", "A", "Increased stretch of ventricular muscle fibers increases the force of contraction.", "MEDIUM", "Textbook", "Cardiac mechanics"),
    q("The dicrotic notch on the aortic pressure curve marks the closure of the:", "Aortic valve", "Mitral valve", "Pulmonary valve", "Tricuspid valve", "A", "Closure of the aortic valve marks the end of ventricular ejection (systole).", "MEDIUM", "Textbook", "Cardiac cycle"),
    q("Which of the following causes vasodilation in most vascular beds?", "Nitric oxide", "Endothelin-1", "Angiotensin II", "Vasopressin", "A", "Nitric oxide (EDRF) is a potent endothelium-derived vasodilator.", "EASY", "Textbook", "Vascular tone"),
    q("The phase 0 (upstroke) of the action potential in ventricular myocytes is due to the influx of:", "Sodium", "Calcium", "Potassium", "Chloride", "A", "Rapid opening of voltage-gated Na+ channels causes phase 0 depolarization in working myocardium.", "MEDIUM", "Textbook", "Cardiac action potential"),
    q("The phase 0 (upstroke) of the action potential in SA node pacemaker cells is primarily due to the influx of:", "Calcium", "Sodium", "Potassium", "Chloride", "A", "In nodal cells, the upstroke is driven by L-type Ca2+ channels, not fast Na+ channels.", "MEDIUM", "Textbook", "Cardiac action potential"),
    q("Ejection fraction is normally about:", "55-65%", "30-40%", "10-20%", "90-100%", "A", "Normal EF is above 50-55%. EF = SV / EDV.", "MEDIUM", "Textbook", "Cardiac mechanics")
  ]],
  ["Respiratory System", [
    q("The volume of air inspired or expired with each normal breath is the:", "Tidal volume", "Inspiratory reserve volume", "Vital capacity", "Residual volume", "A", "Normal tidal volume is approximately 500 mL in an adult.", "EASY", "Textbook", "Lung volumes"),
    q("Which of the following cannot be measured by simple spirometry?", "Residual volume", "Tidal volume", "Vital capacity", "Inspiratory reserve volume", "A", "RV remains in the lungs after maximal expiration and requires helium dilution or plethysmography.", "MEDIUM", "Textbook", "Lung volumes"),
    q("Surfactant is produced by which cells in the alveoli?", "Type II pneumocytes", "Type I pneumocytes", "Alveolar macrophages", "Goblet cells", "A", "Type II pneumocytes synthesize and secrete pulmonary surfactant.", "EASY", "Textbook", "Lung histology"),
    q("The primary function of pulmonary surfactant is to:", "Decrease alveolar surface tension", "Increase airway resistance", "Promote gas diffusion", "Phagocytize bacteria", "A", "Surfactant reduces surface tension, preventing alveolar collapse (atelectasis).", "MEDIUM", "Textbook", "Respiratory mechanics"),
    q("Most oxygen in the blood is transported:", "Bound to hemoglobin", "Dissolved in plasma", "As bicarbonate", "Bound to plasma proteins", "A", "Approximately 98% of oxygen is carried bound to iron in hemoglobin.", "EASY", "Textbook", "Gas transport"),
    q("Most carbon dioxide in the blood is transported as:", "Bicarbonate ions (HCO3-)", "Carbaminohemoglobin", "Dissolved CO2", "Carbonic acid", "A", "About 70% of CO2 is carried as bicarbonate formed in the RBC by carbonic anhydrase.", "MEDIUM", "Textbook", "Gas transport"),
    q("A rightward shift of the oxygen-hemoglobin dissociation curve means:", "Decreased affinity of Hb for oxygen", "Increased affinity of Hb for oxygen", "Decreased P50", "Increased blood pH", "A", "A right shift facilitates oxygen unloading to tissues (e.g., in acidosis, hypercapnia, fever).", "MEDIUM", "Textbook", "Oxygen dissociation curve"),
    q("The central chemoreceptors in the medulla are primarily stimulated by:", "An increase in H+ concentration in the CSF", "A decrease in arterial PO2", "An increase in arterial pH", "A decrease in arterial PCO2", "A", "CO2 crosses the blood-brain barrier, forms H+, which stimulates the central chemoreceptors.", "HARD", "Textbook", "Respiratory control"),
    q("The peripheral chemoreceptors (carotid and aortic bodies) are most sensitive to:", "Decreased arterial PO2", "Increased arterial PO2", "Decreased arterial PCO2", "Increased arterial pH", "A", "Only peripheral chemoreceptors respond to hypoxia (especially when PaO2 < 60 mmHg).", "MEDIUM", "Textbook", "Respiratory control"),
    q("In a forced expiratory volume (FEV1) test, a normal FEV1/FVC ratio is approximately:", "80%", "50%", "100%", "30%", "A", "A healthy person can exhale about 80% of their vital capacity in the first second.", "MEDIUM", "Textbook", "Pulmonary function tests")
  ]],
  ["Renal Physiology", [
    q("The functional unit of the kidney is the:", "Nephron", "Glomerulus", "Renal pelvis", "Loop of Henle", "A", "Each kidney contains about 1 million nephrons.", "EASY", "Textbook", "Renal anatomy"),
    q("Most of the filtered sodium and water is reabsorbed in the:", "Proximal convoluted tubule", "Loop of Henle", "Distal convoluted tubule", "Collecting duct", "A", "About 65% of filtered Na+ and H2O is reabsorbed in the PCT.", "MEDIUM", "Textbook", "Renal reabsorption"),
    q("Glucose is normally completely reabsorbed in the proximal tubule via:", "Secondary active transport with sodium (SGLT)", "Simple diffusion", "Primary active transport", "Facilitated diffusion independently", "A", "SGLT2 (and SGLT1) cotransport glucose with Na+ on the apical membrane.", "MEDIUM", "Textbook", "Glucose reabsorption"),
    q("Renin is secreted by the:", "Juxtaglomerular (JG) cells", "Macula densa", "Principal cells", "Mesangial cells", "A", "JG cells in the afferent arteriole secrete renin in response to low BP, sympathetic tone, or low NaCl.", "EASY", "Textbook", "RAAS"),
    q("Antidiuretic hormone (ADH) primarily acts on which part of the nephron to increase water reabsorption?", "Collecting duct", "Proximal tubule", "Thick ascending limb", "Bowman's capsule", "A", "ADH inserts aquaporin-2 channels into the principal cells of the collecting duct.", "MEDIUM", "Textbook", "Water handling"),
    q("Aldosterone acts to:", "Increase sodium reabsorption and potassium secretion", "Increase sodium and potassium secretion", "Decrease sodium reabsorption", "Increase calcium reabsorption", "A", "Aldosterone acts on principal cells in the late distal tubule and collecting duct.", "MEDIUM", "Textbook", "RAAS"),
    q("The macula densa senses changes in:", "NaCl load in the distal tubule", "Blood pressure in the afferent arteriole", "Oxygen tension in the blood", "Calcium levels", "A", "Macula densa cells monitor NaCl delivery and mediate tubuloglomerular feedback.", "HARD", "Textbook", "Tubuloglomerular feedback"),
    q("Which segment of the loop of Henle is impermeable to water but actively reabsorbs NaCl?", "Thick ascending limb", "Thin descending limb", "Thin ascending limb", "Vasa recta", "A", "The thick ascending limb is the 'diluting segment' and has the Na-K-2Cl cotransporter.", "MEDIUM", "Textbook", "Loop of Henle"),
    q("Inulin clearance is used to clinical estimate:", "Glomerular Filtration Rate (GFR)", "Renal Plasma Flow (RPF)", "Renal Blood Flow", "Filtration fraction", "A", "Inulin is freely filtered, and neither reabsorbed nor secreted.", "MEDIUM", "Textbook", "Clearance"),
    q("Para-aminohippuric acid (PAH) clearance is used to estimate:", "Renal Plasma Flow (RPF)", "Glomerular Filtration Rate (GFR)", "Tubular maximum for glucose", "Urine concentrating ability", "A", "PAH is completely cleared from the plasma by filtration and active secretion.", "MEDIUM", "Textbook", "Clearance")
  ]],
  ["GI Physiology", [
    q("The enteric nervous system plexus primarily responsible for regulating GI motility is the:", "Myenteric (Auerbach's) plexus", "Submucosal (Meissner's) plexus", "Celiac plexus", "Vagal plexus", "A", "Auerbach's plexus controls motility, while Meissner's controls secretion and blood flow.", "MEDIUM", "Textbook", "Enteric nervous system"),
    q("Gastric acid (HCl) is secreted by which cells of the stomach?", "Parietal (oxyntic) cells", "Chief cells", "G cells", "Mucous neck cells", "A", "Parietal cells secrete HCl and intrinsic factor.", "EASY", "Textbook", "Gastric secretion"),
    q("Pepsinogen is secreted by which cells of the stomach?", "Chief cells", "Parietal cells", "G cells", "Enterochromaffin-like (ECL) cells", "A", "Chief cells secrete pepsinogen, the inactive precursor of the protease pepsin.", "EASY", "Textbook", "Gastric secretion"),
    q("Gastrin is primarily secreted by G cells located in the:", "Gastric antrum", "Gastric fundus", "Duodenum", "Pancreas", "A", "G cells in the antrum secrete gastrin in response to amino acids and distention.", "MEDIUM", "Textbook", "GI hormones"),
    q("Which hormone strongly stimulates gallbladder contraction and pancreatic enzyme secretion?", "Cholecystokinin (CCK)", "Secretin", "Gastrin", "Motilin", "A", "I cells in the duodenum and jejunum secrete CCK in response to fats and proteins.", "MEDIUM", "Textbook", "GI hormones"),
    q("Secretin is released in response to acid in the duodenum and causes:", "Secretion of bicarbonate-rich pancreatic juice", "Contraction of the gallbladder", "Increased gastric acid secretion", "Increased gastric emptying", "A", "S cells release secretin to neutralize the acid chyme via pancreatic bicarbonate.", "MEDIUM", "Textbook", "GI hormones"),
    q("Vitamin B12 is absorbed primarily in the:", "Terminal ileum", "Duodenum", "Stomach", "Ascending colon", "A", "Vitamin B12-intrinsic factor complex is absorbed by specific receptors in the terminal ileum.", "EASY", "Textbook", "Intestinal absorption"),
    q("Bile salts are essential for the digestion and absorption of:", "Lipids (fats)", "Proteins", "Carbohydrates", "Nucleic acids", "A", "Bile salts emulsify dietary fats, increasing the surface area for pancreatic lipase.", "EASY", "Textbook", "Lipid digestion"),
    q("The primary location for the absorption of most nutrients is the:", "Jejunum", "Stomach", "Ileum", "Colon", "A", "Most carbohydrate, protein, and lipid absorption occurs in the duodenum and jejunum.", "EASY", "Textbook", "Intestinal absorption"),
    q("Iron is primarily absorbed in which part of the GI tract?", "Duodenum", "Terminal ileum", "Stomach", "Colon", "A", "Iron is absorbed in the duodenum (Fe2+ state).", "MEDIUM", "Textbook", "Intestinal absorption")
  ]],
  ["Endocrine System", [
    q("Which of the following hormones is synthesized in the hypothalamus and released from the posterior pituitary?", "Antidiuretic hormone (ADH)", "Thyroid-stimulating hormone (TSH)", "Growth hormone (GH)", "Prolactin", "A", "ADH (vasopressin) and oxytocin are made in the hypothalamus and stored in the posterior pituitary.", "EASY", "Textbook", "Pituitary gland"),
    q("Iodine is essential for the synthesis of hormones from the:", "Thyroid gland", "Adrenal cortex", "Parathyroid gland", "Pancreas", "A", "T3 and T4 require dietary iodine for synthesis.", "EASY", "Textbook", "Thyroid gland"),
    q("The primary regulator of blood calcium levels, acting to increase serum calcium, is:", "Parathyroid hormone (PTH)", "Calcitonin", "Vitamin D (active form)", "Aldosterone", "A", "PTH raises serum Ca2+ by bone resorption, renal reabsorption, and activating Vitamin D.", "EASY", "Textbook", "Calcium homeostasis"),
    q("Cortisol is secreted by which zone of the adrenal cortex?", "Zona fasciculata", "Zona glomerulosa", "Zona reticularis", "Adrenal medulla", "A", "Cortex zones: G (aldosterone), F (cortisol), R (androgens).", "MEDIUM", "Textbook", "Adrenal gland"),
    q("The catecholamines (epinephrine and norepinephrine) are produced in the:", "Adrenal medulla", "Adrenal cortex", "Thyroid gland", "Anterior pituitary", "A", "Chromaffin cells in the adrenal medulla secrete catecholamines.", "EASY", "Textbook", "Adrenal gland"),
    q("Insulin is produced by which cells of the pancreatic islets?", "Beta cells", "Alpha cells", "Delta cells", "PP cells", "A", "Beta cells produce insulin; alpha cells produce glucagon.", "EASY", "Textbook", "Pancreas"),
    q("Which hormone acts primarily to lower blood glucose levels?", "Insulin", "Glucagon", "Cortisol", "Growth hormone", "A", "Insulin promotes glucose uptake into cells.", "EASY", "Textbook", "Glucose regulation"),
    q("Aldosterone secretion is primarily stimulated by:", "Angiotensin II and High serum Potassium", "ACTH", "Low serum Potassium", "High serum Sodium", "A", "Angiotensin II (due to low volume/BP) and hyperkalemia are the main secretagogues.", "MEDIUM", "Textbook", "Adrenal gland"),
    q("Acromegaly in adults is caused by hypersecretion of:", "Growth hormone", "Thyroxine", "Cortisol", "Testosterone", "A", "Excess GH after epiphyseal closure leads to acromegaly.", "MEDIUM", "Textbook", "Pituitary disorders"),
    q("Which hormone is responsible for the maintenance of the corpus luteum during early pregnancy?", "Human chorionic gonadotropin (hCG)", "Progesterone", "Luteinizing hormone (LH)", "Estrogen", "A", "The developing placenta secretes hCG which mimics LH.", "MEDIUM", "Textbook", "Reproductive endocrinology")
  ]],
  ["Neurophysiology", [
    q("The major inhibitory neurotransmitter in the brain is:", "Gamma-aminobutyric acid (GABA)", "Glutamate", "Acetylcholine", "Dopamine", "A", "GABA is the principal inhibitory neurotransmitter in the central nervous system.", "EASY", "Textbook", "Neurotransmitters"),
    q("The major excitatory neurotransmitter in the brain is:", "Glutamate", "Glycine", "Serotonin", "GABA", "A", "Glutamate mediates most fast excitatory synaptic transmission in the brain.", "EASY", "Textbook", "Neurotransmitters"),
    q("Which sensory pathway crosses to the contralateral side in the medulla (decussation of medial lemniscus)?", "Dorsal column-medial lemniscal pathway", "Spinothalamic tract", "Corticospinal tract", "Spinocerebellar tract", "A", "Fine touch, proprioception, and vibration cross in the medulla.", "HARD", "Textbook", "Sensory pathways"),
    q("Pain and temperature sensation are carried by the:", "Lateral spinothalamic tract", "Dorsal columns", "Anterior spinothalamic tract", "Corticospinal tract", "A", "The lateral spinothalamic tract carries pain and temperature and crosses at the spinal cord level.", "MEDIUM", "Textbook", "Sensory pathways"),
    q("Damage to the cerebellum typically results in:", "Ataxia and intention tremor", "Resting tremor and rigidity", "Paralysis", "Loss of sensation", "A", "Cerebellar lesions cause ipsilateral incoordination (ataxia).", "MEDIUM", "Textbook", "Motor control"),
    q("The sleep-wake cycle and circadian rhythms are primarily regulated by the:", "Suprachiasmatic nucleus of the hypothalamus", "Thalamus", "Pineal gland alone", "Medulla oblongata", "A", "The SCN is the master biological clock.", "MEDIUM", "Textbook", "Circadian rhythms"),
    q("Rapid Eye Movement (REM) sleep is characterized by all EXCEPT:", "High muscle tone", "Dreaming", "EEG resembling wakefulness (beta/sawtooth waves)", "Rapid eye movements", "A", "REM sleep features profound loss of muscle tone (atonia).", "MEDIUM", "Textbook", "Sleep"),
    q("Sensory aphasia (inability to understand written or spoken language) is characteristic of a lesion in:", "Wernicke's area", "Broca's area", "Prefrontal cortex", "Primary auditory cortex", "A", "Wernicke's area is crucial for language comprehension.", "EASY", "Textbook", "Cortical functions"),
    q("The deep tendon reflex (e.g., knee jerk) is an example of a:", "Monosynaptic stretch reflex", "Polysynaptic reflex", "Withdrawal reflex", "Crossed extensor reflex", "A", "The afferent 1a fiber synapses directly onto the alpha motor neuron.", "EASY", "Textbook", "Reflexes"),
    q("Which part of the brain is crucial for consolidating short-term memory into long-term memory?", "Hippocampus", "Amygdala", "Basal ganglia", "Cerebellum", "A", "Bilateral hippocampal lesions cause profound anterograde amnesia.", "MEDIUM", "Textbook", "Memory")
  ]],
  ["Reproductive Physiology", [
    q("Ovulation is triggered by a surge in which hormone?", "Luteinizing hormone (LH)", "Follicle-stimulating hormone (FSH)", "Estrogen", "Progesterone", "A", "The LH surge, caused by positive feedback from estrogen, induces ovulation.", "EASY", "Textbook", "Menstrual cycle"),
    q("The primary source of progesterone during the secretory phase of the menstrual cycle is the:", "Corpus luteum", "Developing follicle", "Adrenal cortex", "Placenta", "A", "After ovulation, the remnant follicle becomes the corpus luteum and secretes progesterone.", "MEDIUM", "Textbook", "Menstrual cycle"),
    q("Spermatogenesis takes place in the:", "Seminiferous tubules", "Epididymis", "Prostate gland", "Seminal vesicles", "A", "Spermatogenesis occurs in the seminiferous tubules of the testes.", "EASY", "Textbook", "Male reproduction"),
    q("Testosterone is secreted by which cells in the testes?", "Leydig cells", "Sertoli cells", "Spermatogonia", "Prostate cells", "A", "Leydig (interstitial) cells secrete testosterone in response to LH.", "EASY", "Textbook", "Male reproduction"),
    q("Sertoli cells are stimulated primarily by:", "FSH", "LH", "Testosterone alone", "GnRH", "A", "FSH acts on Sertoli cells to support spermatogenesis and secrete inhibin.", "MEDIUM", "Textbook", "Male reproduction"),
    q("Fertilization normally occurs in the:", "Ampulla of the fallopian tube", "Uterine cavity", "Ovary", "Cervix", "A", "The ampulla is the widest part of the tube where sperm typically meets the egg.", "EASY", "Textbook", "Pregnancy"),
    q("The hormone primarily responsible for milk production (lactogenesis) is:", "Prolactin", "Oxytocin", "Estrogen", "Progesterone", "A", "Prolactin stimulates milk synthesis, while oxytocin stimulates let-down.", "EASY", "Textbook", "Lactation"),
    q("The hormone primarily responsible for milk ejection (let-down reflex) is:", "Oxytocin", "Prolactin", "Estrogen", "Progesterone", "A", "Oxytocin causes contraction of myoepithelial cells in the breast.", "EASY", "Textbook", "Lactation"),
    q("Menopause is characterized endocrinologically by:", "High FSH and LH, low estrogen", "Low FSH and LH, low estrogen", "High estrogen, low FSH", "Normal hormones but ovarian resistance", "A", "Loss of ovarian follicles removes negative feedback, leading to elevated gonadotropins.", "MEDIUM", "Textbook", "Menopause"),
    q("The acrosome reaction is necessary for:", "Sperm penetration of the zona pellucida", "Sperm capacitation", "Sperm motility", "Prevention of polyspermy", "A", "Enzymes released from the acrosome allow the sperm to digest the zona pellucida.", "HARD", "Textbook", "Fertilization")
  ]]
];

writeSubject("Physiology", chapters, "physiology.json");
