const { q, writeSubject } = require('./qgen_helper');

const chapters = [
  ["Ophthalmology General", [
    q("The most common cause of preventable blindness worldwide is:", "Trachoma", "Cataract", "Glaucoma", "Diabetic Retinopathy", "A", "A neglected tropical disease caused by repeated infections with Chlamydia trachomatis.", "EASY", "Textbook", "Global Health"),
    q("A painful, tender, red, localized swelling at the margin of the eyelid resulting from an acute staphylococcal infection of an eyelash follicle is a:", "Hordeolum (Stye)", "Chalazion", "Xanthelasma", "Blepharitis", "A", "An external stye is an acute, painful bacterial infection.", "EASY", "Textbook", "Eyelids"),
    q("A painless, firm, distinctly nodular swelling in the eyelid, caused by chronic granulomatous inflammation of a Meibomian gland, is a:", "Chalazion", "Hordeolum (Stye)", "Dacryocystitis", "Pinguecula", "A", "Unlike a stye, a chalazion is sterile and slow-growing.", "EASY", "Textbook", "Eyelids"),
    q("A patient working in agriculture presents with severe eye pain, photophobia, and an ulcer on the cornea with a white, fluffy, 'feathery' border and satellite lesions. The likely cause is:", "Fungal keratitis (e.g., Aspergillus or Fusarium)", "Bacterial keratitis (e.g., Pseudomonas)", "Viral keratitis (Herpes Simplex)", "Acanthamoeba keratitis", "A", "Trauma with vegetative matter strongly suggests a fungal etiology.", "MEDIUM", "Textbook", "Cornea"),
    q("A dendritic (branching) corneal ulcer that stains brightly with fluorescein dye is pathognomonic for:", "Herpes Simplex Virus (HSV) keratitis", "Acanthamoeba keratitis", "Fungal keratitis", "Bacterial keratitis", "A", "Steroids are severely contraindicated as they exacerbate the replication of HSV and worsen the ulcer.", "EASY", "Textbook", "Cornea"),
    q("The classic sign of acute angle-closure glaucoma includes all of the following EXCEPT:", "An open, normal-appearing anterior chamber angle on gonioscopy", "Severe eye pain and ipsilateral headache", "A mid-dilated, fixed, unreactive pupil", "Halos seen around lights", "A", "The angle is structurally narrow/closed, blocking aqueous outflow and sharply raising Intraocular Pressure (IOP).", "EASY", "Textbook", "Glaucoma"),
    q("The primary pathophysiological mechanism of primary open-angle glaucoma (POAG) is:", "Increased resistance to aqueous outflow through the trabecular meshwork", "Excessive production of aqueous humor by the ciliary body", "Pupillary block pushing the iris anteriorly", "Obstruction of the episcleral veins", "A", "POAG is painless and progressive, causing peripheral visual field loss ('tunnel vision').", "MEDIUM", "Textbook", "Glaucoma"),
    q("A painless, progressive, profound reduction in visual acuity characterized by an opacity of the crystalline lens is a:", "Cataract", "Macular Degeneration", "Retinal Detachment", "Optic Neuritis", "A", "Cataract acts as a physical barrier to light entering the eye.", "EASY", "Textbook", "Lens"),
    q("The hallmark finding of proliferative diabetic retinopathy, distinguishing it from non-proliferative retinopathy, is:", "Neovascularization (growth of new, fragile blood vessels)", "Microaneurysms", "Hard exudates", "Cotton wool spots", "A", "Ischemia drives VEGF release, causing new, weak vessels to grow, leading to vitreous hemorrhage.", "EASY", "Textbook", "Retina"),
    q("A highly myopic young man presents complaining of a sudden onset of 'flashing lights' (photopsia) and multiple new 'floaters', followed by a dark shadow moving like a 'curtain' over his vision. Diagnosis?", "Rhegmatogenous Retinal Detachment", "Central Retinal Artery Occlusion", "Acute Angle-Closure Glaucoma", "Optic Neuritis", "A", "A retinal tear allows fluid to separate the neurosensory retina from the underlying epithelium.", "EASY", "Textbook", "Retina")
  ]]
]

writeSubject("Ophthalmology", chapters, "ophthalmology.json");
