const { q, writeSubject } = require('./qgen_helper');

const chapters = [
  ["Chemistry of Carbohydrates", [
    q("Which of the following is an aldohexose?", "Glucose", "Fructose", "Ribose", "Erythrose", "A", "Glucose is a 6-carbon sugar with an aldehyde group.", "EASY", "Textbook", "Monosaccharides"),
    q("The most abundant carbohydrate in nature is:", "Cellulose", "Starch", "Glycogen", "Sucrose", "A", "Cellulose is the structural component of plant cell walls.", "EASY", "Textbook", "Polysaccharides"),
    q("Which glycosaminoglycan does not contain uronic acid?", "Keratan sulfate", "Hyaluronic acid", "Chondroitin sulfate", "Heparin", "A", "Keratan sulfate contains galactose instead of uronic acid.", "HARD", "Textbook", "GAGs"),
    q("Mutarotation is characteristic of:", "Reducing sugars", "Non-reducing sugars", "Polysaccharides", "Glycoproteins", "A", "Reducing sugars have a free anomeric carbon that can interconvert between alpha and beta forms.", "MEDIUM", "Textbook", "Carbohydrate properties"),
    q("Maltose is composed of:", "Two glucose molecules linked by alpha(1->4) bond", "Glucose and fructose linked by alpha(1->2) bond", "Glucose and galactose linked by beta(1->4) bond", "Two galactose molecules", "A", "Maltose is a disaccharide of two glucoses.", "EASY", "Textbook", "Disaccharides"),
    q("The epimer of glucose at C-4 is:", "Galactose", "Mannose", "Fructose", "Ribose", "A", "Galactose and glucose differ only at the C-4 position.", "MEDIUM", "Textbook", "Epimers"),
    q("Which of the following is an example of a heteropolysaccharide?", "Hyaluronic acid", "Starch", "Glycogen", "Cellulose", "A", "GAGs like hyaluronic acid consist of repeating disaccharide units.", "MEDIUM", "Textbook", "Polysaccharides"),
    q("Sucrose is a non-reducing sugar because:", "Both anomeric carbons are involved in the glycosidic bond", "It lacks a ketone group", "It forms a cyclic structure", "It does not undergo mutarotation", "A", "The anomeric carbons of glucose and fructose are linked alpha(1->2).", "MEDIUM", "Textbook", "Disaccharides"),
    q("The storage form of carbohydrate in animals is:", "Glycogen", "Starch", "Cellulose", "Inulin", "A", "Glycogen is a highly branched polymer of glucose stored in liver and muscle.", "EASY", "Textbook", "Polysaccharides"),
    q("O-linked glycosylation of proteins typically occurs on which amino acids?", "Serine or Threonine", "Asparagine", "Lysine", "Tyrosine", "A", "O-linked sugars attach to the hydroxyl group of Ser or Thr.", "HARD", "Textbook", "Glycoproteins")
  ]],
  ["Chemistry of Lipids", [
    q("Which of the following is an essential fatty acid?", "Linoleic acid", "Palmitic acid", "Stearic acid", "Oleic acid", "A", "Humans cannot introduce double bonds past C-9, making linoleic acid (18:2) essential.", "EASY", "Textbook", "Fatty acids"),
    q("The most abundant class of lipids in cell membranes is:", "Phospholipids", "Triglycerides", "Cholesterol", "Sphingolipids", "A", "Glycerophospholipids form the lipid bilayer of cell membranes.", "EASY", "Textbook", "Membrane lipids"),
    q("Which phospholipid is predominantly found in the inner leaflet of the plasma membrane and involved in apoptosis signaling?", "Phosphatidylserine", "Phosphatidylcholine", "Sphingomyelin", "Phosphatidylethanolamine", "A", "PS flips to the outer leaflet as an 'eat me' signal during apoptosis.", "HARD", "Textbook", "Phospholipids"),
    q("Cholesterol is a precursor for all of the following EXCEPT:", "Thyroid hormones", "Bile acids", "Vitamin D", "Steroid hormones", "A", "Thyroid hormones are derived from tyrosine, not cholesterol.", "MEDIUM", "Textbook", "Cholesterol derivatives"),
    q("The basic structural unit of sphingolipids is:", "Ceramide", "Glycerol", "Phosphatidic acid", "Cholesterol", "A", "Ceramide (sphingosine + fatty acid) forms the core of sphingolipids.", "MEDIUM", "Textbook", "Sphingolipids"),
    q("Which lipid contains an ether bond?", "Plasmalogen", "Lecithin", "Cephalin", "Cardiolipin", "A", "Plasmalogens (e.g., in myelin and heart) have an ether-linked alkenyl chain at C-1.", "HARD", "Textbook", "Ether lipids"),
    q("Arachidonic acid is a precursor for:", "Prostaglandins", "Sphingomyelin", "Bile salts", "Steroid hormones", "A", "Arachidonic acid (20:4) is the main precursor for eicosanoids.", "EASY", "Textbook", "Eicosanoids"),
    q("High levels of which lipoprotein are inversely associated with the risk of coronary artery disease?", "HDL", "LDL", "VLDL", "Chylomicrons", "A", "High-Density Lipoprotein (HDL) mediates reverse cholesterol transport.", "EASY", "Textbook", "Lipoproteins"),
    q("Cardiolipin is characteristically found in the:", "Inner mitochondrial membrane", "Plasma membrane outer leaflet", "Golgi apparatus", "Lysosomes", "A", "Cardiolipin is unique to mitochondria and essential for ETC function.", "MEDIUM", "Textbook", "Phospholipids"),
    q("A fatty acid with the nomenclature 18:2(delta 9,12) is:", "Linoleic acid", "Linolenic acid", "Oleic acid", "Arachidonic acid", "A", "Linoleic acid has 18 carbons and two double bonds at positions 9 and 12.", "MEDIUM", "Textbook", "Fatty acid nomenclature")
  ]],
  ["Chemistry of Proteins", [
    q("Which amino acid is achiral?", "Glycine", "Alanine", "Valine", "Proline", "A", "Glycine has hydrogen as its R-group, so the alpha carbon is not chiral.", "EASY", "Textbook", "Amino acids"),
    q("Which amino acid contains an indole ring in its side chain?", "Tryptophan", "Phenylalanine", "Tyrosine", "Histidine", "A", "Tryptophan has a bulky, bicyclic indole side chain.", "MEDIUM", "Textbook", "Side chains"),
    q("The peptide bond is characterized by all EXCEPT:", "Freedom of rotation", "Partial double bond character", "Coplanar atoms", "Trans configuration", "A", "The partial double bond nature restricts rotation around the C-N bond.", "MEDIUM", "Textbook", "Peptide bond"),
    q("The alpha-helix and beta-pleated sheet represent which level of protein structure?", "Secondary", "Primary", "Tertiary", "Quaternary", "A", "Secondary structure involves local folding stabilized by hydrogen bonds between backbone atoms.", "EASY", "Textbook", "Protein structure"),
    q("Which amino acid disrupts the alpha-helix due to its strict cyclic structure?", "Proline", "Glycine", "Leucine", "Alanine", "A", "Proline lacks an amide hydrogen to donate to an H-bond and causes a 'kink'.", "EASY", "Textbook", "Secondary structure"),
    q("The isoelectric point (pI) of a protein is the pH at which:", "It has no net electrical charge", "It is most soluble", "It moves fastest in an electric field", "It denatures", "A", "At the pI, the net charge is zero (zwitterion predominates).", "MEDIUM", "Textbook", "Isoelectric point"),
    q("Disulfide bonds, which stabilize tertiary structure, are formed between residues of:", "Cysteine", "Methionine", "Serine", "Proline", "A", "Cysteine thiol groups can oxidize to form a covalent disulfide cystine bond.", "EASY", "Textbook", "Protein structure"),
    q("Hemoglobin is an example of a protein with:", "Quaternary structure", "Only primary structure", "Only secondary structure", "Only tertiary structure", "A", "Hemoglobin is a tetramer composed of four polypeptide subunits.", "EASY", "Textbook", "Protein structure"),
    q("In collagen, every third amino acid is typically:", "Glycine", "Proline", "Hydroxyproline", "Lysine", "A", "Glycine's small size allows the tight packing of the collagen triple helix.", "MEDIUM", "Textbook", "Fibrous proteins"),
    q("Which amino acid acts as a major physiological buffer due to its pKa being close to physiological pH?", "Histidine", "Arginine", "Lysine", "Glutamine", "A", "The imidazole side chain of histidine has a pKa around 6.0.", "HARD", "Textbook", "Amino acids")
  ]],
  ["Enzymes", [
    q("Enzymes increase the rate of chemical reactions by:", "Lowering the activation energy", "Changing the equilibrium constant", "Increasing the free energy of products", "Lowering the temperature", "A", "Enzymes stabilize the transition state, reducing the energy barrier.", "EASY", "Textbook", "Enzyme kinetics"),
    q("The Michaelis constant (Km) represents the:", "Substrate concentration at half-maximal velocity (Vmax/2)", "Maximum velocity of the reaction", "Turnover number", "Affinity of the enzyme for its inhibitor", "A", "Km is inversely related to the enzyme's affinity for its substrate.", "EASY", "Textbook", "Enzyme kinetics"),
    q("In competitive inhibition:", "Vmax is unchanged, Km is increased", "Vmax is decreased, Km is unchanged", "Both Vmax and Km are decreased", "Both Vmax and Km are increased", "A", "The inhibitor competes for the active site; high substrate can overcome it.", "MEDIUM", "Textbook", "Enzyme inhibition"),
    q("In non-competitive inhibition:", "Vmax is decreased, Km is unchanged", "Vmax is unchanged, Km is increased", "Both Vmax and Km are decreased", "Both Vmax and Km are increased", "A", "The inhibitor binds somewhere other than the active site, reducing functional enzyme concentration.", "MEDIUM", "Textbook", "Enzyme inhibition"),
    q("Allosteric enzymes typically exhibit a kinetics curve that is:", "Sigmoidal", "Hyperbolic", "Linear", "Exponential", "A", "Cooperativity between subunits causes a sigmoidal velocity vs. substrate curve.", "MEDIUM", "Textbook", "Allosteric regulation"),
    q("An apoenzyme combined with its necessary cofactor is termed a(n):", "Holoenzyme", "Zymogen", "Proenzyme", "Isozyme", "A", "Holoenzyme refers to the active, complete enzyme-cofactor complex.", "EASY", "Textbook", "Enzyme structure"),
    q("Isozymes are:", "Enzymes that catalyze the same reaction but differ in structure and properties", "Inactive precursors of enzymes", "Enzymes that require the same cofactor", "Enzymes involved in the same metabolic pathway", "A", "E.g., LDH has different isozymes in heart vs. muscle.", "MEDIUM", "Textbook", "Isozymes"),
    q("Which of the following classes of enzymes catalyze the cleavage of bonds by the addition of water?", "Hydrolases", "Lyases", "Transferases", "Oxidoreductases", "A", "Hydrolases (like digestive enzymes) use water to break bonds.", "EASY", "Textbook", "Enzyme classification"),
    q("The lineweaver-Burk plot (double reciprocal) yields a y-intercept that corresponds to:", "1/Vmax", "-1/Km", "Km/Vmax", "Vmax/Km", "A", "The y-intercept represents 1/Vmax.", "MEDIUM", "Textbook", "Enzyme kinetics"),
    q("Suicide inhibition is an example of:", "Irreversible enzyme inhibition", "Competitive inhibition", "Non-competitive inhibition", "Uncompetitive inhibition", "A", "The enzyme converts the inhibitor into a reactive intermediate that covalently modifies the active site.", "HARD", "Textbook", "Enzyme inhibition")
  ]],
  ["Carbohydrate Metabolism", [
    q("Glycolysis conceptually occurs in which subcellular compartment?", "Cytosol", "Mitochondrial matrix", "Lysosome", "Endoplasmic reticulum", "A", "The enzymes of the glycolytic pathway are localized in the cytoplasm.", "EASY", "Textbook", "Glycolysis"),
    q("The rate-limiting and committed step of glycolysis is catalyzed by:", "Phosphofructokinase-1 (PFK-1)", "Hexokinase", "Pyruvate kinase", "Glucokinase", "A", "PFK-1 converts fructose-6-P to fructose-1,6-bisP and is tightly regulated.", "MEDIUM", "Textbook", "Glycolysis"),
    q("In anaerobic conditions, pyruvate is converted to lactate to regenerate:", "NAD+", "NADH", "ATP", "FAD", "A", "Lactate dehydrogenase uses NADH to reduce pyruvate, regenerating NAD+ for glycolysis to continue.", "MEDIUM", "Textbook", "Anaerobic glycolysis"),
    q("Which enzyme is unique to gluconeogenesis?", "Phosphoenolpyruvate carboxykinase (PEPCK)", "Pyruvate kinase", "Phosphofructokinase-1", "Hexokinase", "A", "PEPCK circumvents the irreversible pyruvate kinase step of glycolysis.", "MEDIUM", "Textbook", "Gluconeogenesis"),
    q("The major site for gluconeogenesis is the:", "Liver", "Skeletal muscle", "Brain", "Adipose tissue", "A", "The liver uses non-carbohydrate precursors to maintain blood glucose.", "EASY", "Textbook", "Gluconeogenesis"),
    q("The key regulatory enzyme of glycogenesis (glycogen synthesis) is:", "Glycogen synthase", "Glycogen phosphorylase", "Branching enzyme", "Glucokinase", "A", "Glycogen synthase adds glucose residues via alpha(1->4) linkages.", "EASY", "Textbook", "Glycogen metabolism"),
    q("Insulin promotes which of the following processes?", "Glycogenesis", "Glycogenolysis", "Gluconeogenesis", "Lipolysis", "A", "Insulin is an anabolic hormone that promotes storage of glucose as glycogen.", "EASY", "Textbook", "Hormonal regulation"),
    q("The pentose phosphate pathway is important for generating ribose-5-phosphate and:", "NADPH", "NADH", "ATP", "FADH2", "A", "NADPH is needed for reductive biosynthesis (e.g., fatty acids) and antioxidant defense.", "MEDIUM", "Textbook", "Pentose phosphate pathway"),
    q("A deficiency of Glucose-6-Phosphate Dehydrogenase (G6PD) predominantly affects:", "Red blood cells", "Hepatocytes", "Neurons", "Skeletal muscle", "A", "RBCs rely exclusively on the PPP to generate NADPH to protect against oxidative stress.", "HARD", "Textbook", "PPP defects"),
    q("Galactosemia is most commonly caused by a deficiency in:", "Galactose-1-phosphate uridyltransferase (GALT)", "Galactokinase", "Aldolase B", "Fructokinase", "A", "Classic galactosemia leads to accumulation of toxic galactose-1-phosphate.", "HARD", "Textbook", "Galactose metabolism")
  ]],
  ["Lipid Metabolism", [
    q("Beta-oxidation of fatty acids primarily occurs in the:", "Mitochondrial matrix", "Cytosol", "Smooth endoplasmic reticulum", "Peroxisomes", "A", "Long-chain fatty acids are transported into the mitochondria for breakdown.", "EASY", "Textbook", "Beta-oxidation"),
    q("Transport of long-chain fatty acids into the mitochondria requires:", "Carnitine", "Biotin", "Coenzyme Q", "Pyridoxal phosphate", "A", "The carnitine shuttle (CPT-I and II) translocates fatty acyl-CoAs.", "MEDIUM", "Textbook", "Carnitine shuttle"),
    q("The rate-limiting enzyme in fatty acid synthesis is:", "Acetyl-CoA carboxylase", "Fatty acid synthase", "HMG-CoA reductase", "Lipoprotein lipase", "A", "Acetyl-CoA carboxylase forms malonyl-CoA and requires biotin.", "MEDIUM", "Textbook", "Fatty acid synthesis"),
    q("Ketone bodies are synthesized primarily in the:", "Liver mitochondria", "Muscle mitochondria", "Liver cytosol", "Brain cytosol", "A", "The liver produces ketone bodies from acetyl-CoA when CHO is scarce.", "MEDIUM", "Textbook", "Ketogenesis"),
    q("Which of the following is NOT a ketone body?", "Acetate", "Acetoacetate", "Beta-hydroxybutyrate", "Acetone", "A", "The three ketone bodies are acetoacetate, beta-hydroxybutyrate, and acetone.", "EASY", "Textbook", "Ketone bodies"),
    q("The key regulatory enzyme of cholesterol biosynthesis is:", "HMG-CoA reductase", "HMG-CoA synthase", "Mevalonate kinase", "Squalene epoxidase", "A", "HMG-CoA reductase converts HMG-CoA to mevalonate and is the target of statins.", "EASY", "Textbook", "Cholesterol synthesis"),
    q("Chylomicrons are synthesized in the:", "Intestinal mucosal cells", "Hepatocytes", "Adipocytes", "Skeletal muscle", "A", "Chylomicrons transport dietary (exogenous) lipids from the intestine.", "MEDIUM", "Textbook", "Lipoproteins"),
    q("Familial Hypercholesterolemia (Type IIa pattern) is typically due to a defect in:", "LDL receptors", "Lipoprotein lipase", "ApoE", "ApoC-II", "A", "Defective LDL receptors prevent LDL clearance, causing very high serum cholesterol.", "HARD", "Textbook", "Dyslipidemias"),
    q("Hormone-sensitive lipase (HSL) in adipose tissue is activated by:", "Phosphorylation via cAMP-dependent protein kinase", "Dephosphorylation by insulin", "Allosteric binding of ATP", "Cleavage by trypsin", "A", "Epinephrine/Glucagon raise cAMP, activating PKA, which phosphorylates and activates HSL.", "HARD", "Textbook", "Lipid mobilization"),
    q("Sphingolipidoses, such as Tay-Sachs disease, result from defects in:", "Lysosomal hydrolases", "Mitochondrial beta-oxidation", "Peroxisomal enzymes", "ER synthesis", "A", "These diseases are lysosomal storage disorders causing accumulation of sphingolipids.", "MEDIUM", "Textbook", "Sphingolipidoses")
  ]],
  ["Amino Acid Metabolism", [
    q("The primary mechanism for removing the alpha-amino group from amino acids is:", "Transamination", "Deamination", "Decarboxylation", "Hydroxylation", "A", "Transaminases (aminotransferases) transfer the amino group to alpha-ketoglutarate, forming glutamate.", "MEDIUM", "Textbook", "Amino acid degradation"),
    q("Transamination reactions require which vitamin derivative as a coenzyme?", "Pyridoxal phosphate (Vitamin B6)", "Thiamine pyrophosphate (B1)", "Cobalamin (B12)", "Folic acid", "A", "PLP is the essential prosthetic group for all aminotransferases.", "MEDIUM", "Textbook", "Vitamins"),
    q("The urea cycle takes place exclusively in the:", "Liver", "Kidney", "Brain", "Muscle", "A", "The complete set of urea cycle enzymes is found only in hepatocytes.", "EASY", "Textbook", "Urea cycle"),
    q("The rate-limiting enzyme of the urea cycle is:", "Carbamoyl phosphate synthetase I (CPS I)", "Ornithine transcarbamylase (OTC)", "Arginase", "Argininosuccinate lyase", "A", "CPS I is allosterically activated by N-acetylglutamate (NAG).", "HARD", "Textbook", "Urea cycle regulation"),
    q("Which pair of amino acids is exclusively ketogenic?", "Leucine and Lysine", "Alanine and Glycine", "Valine and Isoleucine", "Tryptophan and Tyrosine", "A", "Leucine and Lysine cannot be converted to glucose; they yield Acetyl-CoA/Acetoacetate.", "MEDIUM", "Textbook", "Glucogenic/Ketogenic"),
    q("Phenylketonuria (PKU) is most commonly caused by a deficiency in:", "Phenylalanine hydroxylase", "Tyrosine hydroxylase", "Homogentisate oxidase", "Branched-chain ketoacid dehydrogenase", "A", "PAH deficiency prevents conversion of phenylalanine to tyrosine.", "EASY", "Textbook", "Inborn errors of metabolism"),
    q("Alkaptonuria is characterized by dark urine and involves a deficiency in:", "Homogentisate oxidase", "Phenylalanine hydroxylase", "Tyrosinase", "Fumarylacetoacetate hydrolase", "A", "Homogentisic acid accumulates, oxidizes, and polymerizes to form a black pigment.", "MEDIUM", "Textbook", "Inborn errors of metabolism"),
    q("Serotonin is synthesized from the amino acid:", "Tryptophan", "Tyrosine", "Histidine", "Glutamate", "A", "Tryptophan is hydroxylated and then decarboxylated to form serotonin (5-HT).", "MEDIUM", "Textbook", "Amino acid derivatives"),
    q("Nitric oxide (NO) is synthesized in endothelial cells from which amino acid?", "Arginine", "Citrulline", "Ornithine", "Glutamine", "A", "Nitric Oxide Synthase (NOS) oxidizes arginine to NO and citrulline.", "MEDIUM", "Textbook", "Amino acid derivatives"),
    q("Maple syrup urine disease (MSUD) involves defective metabolism of:", "Branched-chain amino acids (Leucine, Isoleucine, Valine)", "Aromatic amino acids", "Sulfur-containing amino acids", "Basic amino acids", "A", "A defect in branched-chain alpha-keto acid dehydrogenase complex causes MSUD.", "HARD", "Textbook", "Inborn errors of metabolism")
  ]],
  ["Nucleotide Metabolism", [
    q("Which of the following amino acids is required for purine ring synthesis?", "Glycine, Glutamine, Aspartate", "Alanine, Serine, Threonine", "Valine, Leucine, Isoleucine", "Phenylalanine, Tyrosine, Tryptophan", "A", "Gag: Glycine, Aspartate, Glutamine contribute atoms to the purine ring.", "HARD", "Textbook", "Purine synthesis"),
    q("The committed step in de novo purine biosynthesis is catalyzed by:", "PRPP glutamyl amidotransferase", "PRPP synthetase", "Thymidylate synthase", "Ribonucleotide reductase", "A", "Transfer of the amide group from glutamine to PRPP is the committed step.", "HARD", "Textbook", "Purine synthesis"),
    q("The end product of purine catabolism in humans is:", "Uric acid", "Urea", "Allantoin", "Ammonia", "A", "Xanthine oxidase converts hypoxanthine and xanthine to uric acid.", "EASY", "Textbook", "Purine degradation"),
    q("Lesch-Nyhan syndrome is due to a complete deficiency of:", "HGPRT (Hypoxanthine-guanine phosphoribosyltransferase)", "Xanthine oxidase", "Adenosine deaminase (ADA)", "PRPP synthetase", "A", "Defective purine salvage leads to excessive uric acid and self-mutilation.", "MEDIUM", "Textbook", "Purine salvage"),
    q("Severe Combined Immunodeficiency (SCID) is classically caused by a deficiency of:", "Adenosine deaminase (ADA)", "HGPRT", "Xanthine oxidase", "Orotate phosphoribosyltransferase", "A", "ADA deficiency causes accumulation of dATP, which is toxic to lymphocytes.", "MEDIUM", "Textbook", "Purine degradation"),
    q("The rate-limiting enzyme in de novo pyrimidine synthesis in mammals is:", "Carbamoyl phosphate synthetase II (CPS II)", "Aspartate transcarbamoylase", "Dihydroorotate dehydrogenase", "Thymidylate synthase", "A", "CPS II is cytosolic and synthesizes carbamoyl phosphate for pyrimidines.", "HARD", "Textbook", "Pyrimidine synthesis"),
    q("Methotrexate acts as an antineoplastic agent by competitively inhibiting:", "Dihydrofolate reductase (DHFR)", "Thymidylate synthase", "Ribonucleotide reductase", "Xanthine oxidase", "A", "DHFR inhibition blocks the regeneration of tetrahydrofolate, halting thymidine synthesis.", "MEDIUM", "Textbook", "Chemotherapy pharmacology"),
    q("Fluorouracil (5-FU) directly inhibits which enzyme?", "Thymidylate synthase", "Dihydrofolate reductase", "Ribonucleotide reductase", "HGPRT", "A", "5-FU acts as a suicide inhibitor of thymidylate synthase.", "MEDIUM", "Textbook", "Chemotherapy pharmacology"),
    q("Orotic aciduria (Type 1) is caused by a deficiency of the bifunctional enzyme UMP synthase. It presents with:", "Megaloblastic anemia unresponsive to B12/Folate", "Hyperuricemia", "Self-mutilation", "Severe combined immunodeficiency", "A", "Defective pyrimidine synthesis blocks cell division (anemia) and causes orotic acid in urine.", "HARD", "Textbook", "Pyrimidine synthesis defects"),
    q("Ribonucleotide reductase, the enzyme that converts ribose to deoxyribose, requires which protein cofactor?", "Thioredoxin", "Biotin", "Tetrahydrofolate", "Coenzyme B12", "A", "Thioredoxin serves as the hydrogen donor to reduce the ribose sugar.", "HARD", "Textbook", "Deoxynucleotide synthesis")
  ]],
  ["Molecular Biology", [
    q("The mechanism of DNA replication is described as:", "Semiconservative", "Conservative", "Dispersive", "Random", "A", "Each new DNA double helix contains one parental strand and one newly synthesized strand.", "EASY", "Textbook", "DNA replication"),
    q("DNA polymerase synthesizes DNA in which direction?", "5' to 3' only", "3' to 5' only", "Both 5' to 3' and 3' to 5'", "It depends on the leading or lagging strand", "A", "Nucleotides are always added to the 3' hydroxyl end of the growing chain.", "EASY", "Textbook", "DNA replication"),
    q("Okazaki fragments are formed during the synthesis of the:", "Lagging strand", "Leading strand", "RNA primer", "Telomere", "A", "The lagging strand is synthesized discontinuously as Okazaki fragments.", "EASY", "Textbook", "DNA replication"),
    q("Which enzyme is responsible for removing the RNA primer and replacing it with DNA in prokaryotes?", "DNA Polymerase I", "DNA Polymerase III", "DNA Ligase", "Helicase", "A", "DNA Pol I possesses 5' to 3' exonuclease activity to remove primers.", "MEDIUM", "Textbook", "DNA replication"),
    q("The promoter region in eukaryotes typically contains which consensus sequence?", "TATA box", "Pribnow box", "Shine-Dalgarno sequence", "Poly-A tail", "A", "The TATA box (Hogness box) is found ~25 base pairs upstream of the transcription start site.", "MEDIUM", "Textbook", "Transcription"),
    q("Post-transcriptional modifications of eukaryotic mRNA include all of the following EXCEPT:", "Addition of a poly-A tail", "5' Capping with 7-methylguanosine", "Splicing of introns", "Removal of exons", "A", "Exons are retained and spliced together to form the mature mRNA; introns are removed.", "EASY", "Textbook", "RNA processing"),
    q("The Shine-Dalgarno sequence in prokaryotic mRNA functions to:", "Bind to the 16S rRNA of the small ribosomal subunit", "Signal termination of transcription", "Protect mRNA from degradation", "Serve as the start codon", "A", "It aligns the ribosome correctly so that translation begins at the AUG start codon.", "HARD", "Textbook", "Translation"),
    q("Which site on the ribosome accepts the incoming aminoacyl-tRNA?", "A site", "P site", "E site", "Catalytic site", "A", "The Acceptor (A) site binds the incoming loaded tRNA.", "MEDIUM", "Textbook", "Translation"),
    q("Restriction endonucleases typically recognize and cut DNA at:", "Palindromic sequences", "Telomere repeats", "Promoter regions", "Intron-exon junctions", "A", "Type II restriction enzymes recognize specific short palindromic sequences (e.g., GAATTC).", "MEDIUM", "Textbook", "Recombinant DNA"),
    q("Polymerase Chain Reaction (PCR) involves three step cycles. What is the correct order?", "Denaturation, Annealing, Extension", "Annealing, Denaturation, Extension", "Extension, Annealing, Denaturation", "Denaturation, Extension, Annealing", "A", "Heat denatures DNA, cool down to anneal primers, then synthesize (extend) DNA.", "EASY", "Textbook", "PCR")
  ]],
  ["Vitamins and Minerals", [
    q("Which vitamin deficiency causes night blindness and xerophthalmia?", "Vitamin A", "Vitamin C", "Vitamin D", "Vitamin B12", "A", "Retinal (Vitamin A) is a component of rhodopsin in rod cells.", "EASY", "Textbook", "Fat-soluble vitamins"),
    q("Wernicke-Korsakoff syndrome is seen in chronic alcoholics due to a deficiency of:", "Thiamine (Vitamin B1)", "Riboflavin (Vitamin B2)", "Niacin (Vitamin B3)", "Pyridoxine (Vitamin B6)", "A", "Thiamine deficiency impairs transketolase and PDH complex in the brain.", "MEDIUM", "Textbook", "Water-soluble vitamins"),
    q("Pellagra is characterized by the '3 Ds' (Dermatitis, Diarrhea, Dementia) and is caused by deficiency of:", "Niacin (Vitamin B3)", "Thiamine (Vitamin B1)", "Folic acid", "Vitamin C", "A", "Niacin deficiency causes Pellagra. Niacin can be synthesized from tryptophan.", "EASY", "Textbook", "Water-soluble vitamins"),
    q("Which vitamin is required as a cofactor for the hydroxylation of proline and lysine in collagen synthesis?", "Vitamin C (Ascorbic acid)", "Vitamin K", "Vitamin A", "Vitamin E", "A", "Scurvy results from vitamin C deficiency, leading to weak collagen and bleeding gums.", "MEDIUM", "Textbook", "Water-soluble vitamins"),
    q("Pernicious anemia is caused by impaired absorption of which vitamin due to lack of intrinsic factor?", "Cobalamin (Vitamin B12)", "Folic acid", "Pyridoxine (Vitamin B6)", "Riboflavin (Vitamin B2)", "A", "Autoimmune destruction of parietal cells leads to a lack of intrinsic factor.", "EASY", "Textbook", "Water-soluble vitamins"),
    q("Which vitamin functions as a lipid-soluble antioxidant in cell membranes?", "Vitamin E", "Vitamin A", "Vitamin D", "Vitamin K", "A", "Vitamin E (Tocopherol) protects polyunsaturated fatty acids from oxidative damage.", "EASY", "Textbook", "Fat-soluble vitamins"),
    q("Folic acid deficiency during early pregnancy is strongly associated with:", "Neural tube defects", "Congenital heart defects", "Cretinism", "Phocomelia", "A", "Folate is required for nucleotide synthesis during rapid cell division in the embryo.", "EASY", "Textbook", "Water-soluble vitamins"),
    q("Which mineral is a critical component of glutathione peroxidase, an antioxidant enzyme?", "Selenium", "Zinc", "Copper", "Iron", "A", "Selenium is incorporated as selenocysteine in glutathione peroxidase.", "HARD", "Textbook", "Trace minerals"),
    q("Wilson's disease involves the toxic accumulation of which mineral in the liver and brain?", "Copper", "Iron", "Zinc", "Manganese", "A", "Defect in the ATP7B gene impairs biliary copper excretion.", "MEDIUM", "Textbook", "Trace minerals"),
    q("Hemochromatosis is an inherited disorder characterized by excessive intestinal absorption of:", "Iron", "Calcium", "Magnesium", "Copper", "A", "Excessive iron deposits in tissues (liver, heart, pancreas) causing damage.", "EASY", "Textbook", "Minerals")
  ]]
];

writeSubject("Biochemistry", chapters, "biochemistry.json");
