const { q, writeSubject } = require('./qgen_helper');

const chapters = [
  ["Concepts of Health and Disease", [
    q("The WHO definition of health (1948) describes it as a 'state of complete physical, mental, and social well-being and not merely the absence of disease or infirmity'. This concept is:", "Holistic", "Biomedical", "Ecological", "Psychosocial", "A", "It incorporates physical, mental, and social dimensions, rejecting the purely biomedical view.", "EASY", "Textbook", "Health Definitions"),
    q("The 'Epidemiological Triad' model of disease causation includes:", "Agent, Host, and Environment", "Agent, Vector, and Host", "Environment, Vector, and Genetic susceptibility", "Host, Behavior, and Environment", "A", "Disease results from complex interactions among these three core elements.", "EASY", "Textbook", "Disease Causation"),
    q("The period between the entry of an infectious agent into the host and the appearance of the first clinical signs/symptoms is called the:", "Incubation period", "Latent period", "Generation time", "Communicability period", "A", "During this time, the pathogen is multiplying but has not yet reached the threshold for symptoms.", "EASY", "Textbook", "Infectious Disease"),
    q("Primary prevention of a disease involves:", "Actions taken prior to the onset of disease, which remove the possibility that the disease will ever occur", "Early diagnosis and prompt treatment to halt disease progress", "Limiting disability after the disease is clinically manifest", "Rehabilitation to maximize functional capacity", "A", "Immunization, sanitation, and health education are classic examples of primary prevention.", "EASY", "Textbook", "Prevention Levels"),
    q("Screening for cervical cancer using Pap smears is an example of which level of prevention?", "Secondary", "Primary", "Tertiary", "Primordial", "A", "Screening aims to detect and treat early, asymptomatic disease (Secondary prevention).", "MEDIUM", "Textbook", "Prevention Levels"),
    q("Primordial prevention, a relatively new concept, focuses on:", "Preventing the emergence or development of risk factors in population groups in which they have not yet appeared", "Specific protection against a known pathogen", "Early diagnosis of non-communicable diseases", "Rehabilitation of stroke patients", "A", "Example: National policies/education to discourage children from ever starting to smoke.", "MEDIUM", "Textbook", "Prevention Levels"),
    q("The constant presence of a disease or infectious agent within a given geographic area or population group is termed:", "Endemic", "Epidemic", "Pandemic", "Sporadic", "A", "Malaria is endemic in many parts of sub-Saharan Africa.", "EASY", "Textbook", "Epidemiology Basics"),
    q("An outbreak (epidemic) that affects a large proportion of the population over a wide geographic area (e.g., across continents) is a:", "Pandemic", "Endemic", "Hyperendemic", "Epizootic", "A", "The COVID-19 pandemic is a classic example of widespread global transmission.", "EASY", "Textbook", "Epidemiology Basics"),
    q("A 'carrier' of a disease is an infected person or animal that:", "Harbors a specific infectious agent in the absence of discernible clinical disease, serving as a potential source of infection", "Is currently suffering from the acute clinical symptoms of the disease", "Only transmits the disease through a biological vector (like a mosquito)", "Is immune to the disease and cannot transmit it", "A", "Carriers (like Typhoid Mary) are critical in the transmission of many diseases.", "EASY", "Textbook", "Infectious Disease"),
    q("Herd immunity refers to the:", "Resistance of a group to invasion and spread of an infectious agent, based on the immunity of a high proportion of individual members", "Innate genetic resistance of a specific ethnic group to a particular disease", "Short-term protection provided by the injection of pre-formed immunoglobulins", "Temporary immunity a newborn receives through maternal antibodies", "A", "When enough people are immune (e.g., via vaccines), transmission chains are broken, protecting the unimmunized.", "MEDIUM", "Textbook", "Immunization")
  ]],
  ["Epidemiology and Biostatistics", [
    q("The 'Incidence' of a disease is defined as the:", "Number of NEW cases of a specific disease occurring during a certain period in a population at risk", "Total number of ALL cases (old and new) of a specific disease existing at a given point in time", "Number of deaths caused by the disease in a year", "Proportion of people with the disease who die from it", "A", "Incidence measures the rate of occurrence of new cases (a measure of risk).", "EASY", "Textbook", "Measures of Morbidity"),
    q("The 'Prevalence' of a disease is defined as the:", "Total number of ALL cases (old and new) of a specific disease existing at a given point in time in a defined population", "Number of NEW cases of a specific disease occurring during a certain period", "Rate at which a disease spreads through a population", "Number of deaths per 1000 population per year", "A", "Prevalence measures the burden of disease in a population at a specific 'snapshot' moment.", "EASY", "Textbook", "Measures of Morbidity"),
    q("In an epidemiological study, the measure of the strength of the association between a risk factor and a disease is typically the:", "Relative Risk (Risk Ratio)", "Incidence Density", "Prevalence Rate", "Case Fatality Rate", "A", "RR = Incidence in exposed / Incidence in non-exposed. RR > 1 indicates increased risk.", "MEDIUM", "Textbook", "Measures of Association"),
    q("Which study design is considered the 'gold standard' for evaluating the efficacy and safety of a new therapeutic intervention (e.g., a new drug)?", "Randomized Controlled Trial (RCT)", "Cohort Study", "Case-Control Study", "Cross-Sectional Survey", "A", "Randomization minimizes confounding bias, providing the strongest evidence of causality.", "EASY", "Textbook", "Study Designs"),
    q("A Case-Control study is best suited for investigating:", "Rare diseases or diseases with long latent periods", "The incidence rate of a common infectious disease", "The prevalence of a condition in a snapshot of time", "The natural history of a newly discovered virus", "A", "By starting with cases, researchers can efficiently look backward for exposures without waiting years.", "MEDIUM", "Textbook", "Study Designs"),
    q("A Cohort study typically starts by selecting groups based on their:", "Exposure status (exposed vs. unexposed) and follows them over time to measure disease incidence", "Disease status (cases vs. controls) and looks backward for past exposure", "Randomization to a treatment or placebo group", "Geographic location only to measure current prevalence", "A", "Cohorts are followed prospectively (usually) to see who develops the outcome of interest.", "MEDIUM", "Textbook", "Study Designs"),
    q("The 'Odds Ratio' is the primary measure of association calculated in which type of epidemiological study?", "Case-Control Study", "Cohort Study", "Randomized Controlled Trial", "Cross-Sectional Study", "A", "Case-control studies cannot calculate true incidence, so they use the odds of exposure among cases vs. controls.", "MEDIUM", "Textbook", "Measures of Association"),
    q("In biostatistics, the 'p-value' represents the probability that:", "The observed difference (or a more extreme one) occurred by random chance, assuming the null hypothesis is true", "The alternative hypothesis is true", "The study results are clinically significant", "The sample size was large enough to detect a difference", "A", "A small p-value (typically <0.05) leads to rejecting the null hypothesis.", "MEDIUM", "Textbook", "Hypothesis Testing"),
    q("Which measure of central tendency is most appropriate for a highly skewed (asymmetrical) dataset (e.g., household incomes)?", "Median", "Mean", "Mode", "Standard Deviation", "A", "The median is robust against extreme outliers that heavily pull the mean.", "EASY", "Textbook", "Descriptive Statistics"),
    q("The Standard Deviation of a dataset is a measure of:", "The dispersion or spread of values around the mean", "The central or average value of the dataset", "The difference between the highest and lowest values", "The probability of a false positive result", "A", "A larger standard deviation indicates greater variability in the data points.", "EASY", "Textbook", "Descriptive Statistics")
  ]]
];

writeSubject("PSM", chapters, "psm.json");
