const { q, writeSubject } = require('./qgen_helper');

const chapters = [
  ["General Pharmacology", [
    q("Pharmacodynamics is defined as the study of:", "What the drug does to the body", "What the body does to the drug", "Absorption and distribution of drugs", "Metabolism and excretion of drugs", "A", "Pharmacokinetics is what the body does to the drug (ADME).", "EASY", "Textbook", "Basic principles"),
    q("The bioavailability of a drug administered intravenously is by definition:", "100%", "50%", "75%", "Variable depending on the drug", "A", "IV drugs enter the systemic circulation directly, bypassing absorption barriers.", "EASY", "Textbook", "Bioavailability"),
    q("The therapeutic index (TI) of a drug is a measure of its:", "Safety", "Efficacy", "Potency", "Half-life", "A", "TI is the ratio of Toxic Dose (TD50) to Effective Dose (ED50). Higher TI = safer drug.", "EASY", "Textbook", "Therapeutic index"),
    q("First-pass metabolism primarily occurs in the:", "Liver", "Kidneys", "Lungs", "Brain", "A", "Orally administered drugs pass through the portal circulation and liver before reaching systemic circulation.", "EASY", "Textbook", "Metabolism"),
    q("Which of the following describes a 'Prodrug'?", "An inactive precursor rapidly converted to the active form in the body", "A drug that produces only side effects", "A drug that inhibits its own metabolism", "A fully active compound that is not metabolized", "A", "E.g., Enalapril is converted to the active enalaprilat in the liver.", "MEDIUM", "Textbook", "Metabolism"),
    q("A competitive antagonist affects the dose-response curve of an agonist by:", "Shifting it to the right with no change in maximal effect (Emax)", "Shifting it to the right and decreasing the maximal effect", "Shifting it to the left", "Decreasing the maximal effect only", "A", "High doses of agonist can overcome competitive antagonism, preserving Vmax/Emax.", "MEDIUM", "Textbook", "Receptor theory"),
    q("The half-life (t1/2) of a drug exhibiting first-order kinetics is:", "Constant and independent of the drug concentration", "Directly proportional to the drug concentration", "Inversely proportional to the volume of distribution", "Dependent strictly on kidney function", "A", "First-order kinetics eliminate a constant fraction (percentage) per unit time.", "HARD", "Textbook", "Pharmacokinetics"),
    q("Cytochrome P450 (CYP) enzymes are primarily involved in which phase of drug metabolism?", "Phase I (Oxidation/Reduction/Hydrolysis)", "Phase II (Conjugation)", "Absorption", "Excretion", "A", "CYP enzymes introduce or unmask polar functional groups.", "MEDIUM", "Textbook", "Metabolism"),
    q("Glucuronidation is the most common reaction in which phase of drug metabolism?", "Phase II", "Phase I", "Distribution", "Elimination", "A", "Phase II synthetic reactions conjugate the drug to a large, polar molecule for easier excretion.", "MEDIUM", "Textbook", "Metabolism"),
    q("Tolerance to a drug means that:", "Higher doses are required to produce the same pharmacological effect over time", "The drug is rapidly metabolized on the first pass", "The patient developed an allergic reaction", "The drug causes opposite effects to those intended", "A", "Receptor downregulation or increased metabolism often mediates tolerance.", "EASY", "Textbook", "Basic principles")
  ]],
  ["Autonomic Nervous System", [
    q("Which receptor type mediates the slowing of the heart rate by the vagus nerve?", "Muscarinic (M2)", "Nicotinic", "Alpha-1 adrenergic", "Beta-1 adrenergic", "A", "M2 receptors are abundant in the SA and AV nodes. Activation by Acetylcholine decreases HR.", "MEDIUM", "Textbook", "Cholinergic pharmacology"),
    q("The primary neurotransmitter released by postganglionic sympathetic neurons to most target organs is:", "Norepinephrine", "Acetylcholine", "Epinephrine", "Dopamine", "A", "Exception: Sweat glands, which are sympathetically innervated but use acetylcholine.", "EASY", "Textbook", "Adrenergic pharmacology"),
    q("Atropine is a competitive antagonist at which type of receptor?", "Muscarinic cholinergic", "Nicotinic cholinergic", "Alpha-adrenergic", "Beta-adrenergic", "A", "Atropine blocks parasympathetic activity (e.g., dilates pupils, dry mouth, tachy).", "EASY", "Textbook", "Anticholinergics"),
    q("Which pure beta-1 selective blocker is most appropriate for a patient with asthma and angina?", "Metoprolol", "Propranolol", "Nadolol", "Carvedilol", "A", "Cardioselective beta-1 blockers avoid bronchoconstriction mediated by beta-2 block.", "MEDIUM", "Textbook", "Beta blockers"),
    q("Prazosin lowers blood pressure primarily by blocking:", "Alpha-1 receptors on vascular smooth muscle", "Alpha-2 receptors centrally", "Beta-1 receptors in the heart", "Muscarinic receptors", "A", "Prazosin is a selective competitive alpha-1 antagonist, causing vasodilation.", "MEDIUM", "Textbook", "Alpha blockers"),
    q("Activation of Beta-2 adrenergic receptors typically causes:", "Bronchodilation and vasodilation of skeletal muscle beds", "Bronchoconstriction", "Increased heart rate and contractility", "Pupillary constriction (miosis)", "A", "Beta-2 agonists (e.g., Albuterol) are used largely for asthma relief.", "EASY", "Textbook", "Sympathomimetics"),
    q("Physostigmine is an indirect-acting cholinomimetic that works by:", "Reversibly inhibiting acetylcholinesterase", "Directly stimulating muscarinic receptors", "Releasing acetylcholine from nerve terminals", "Blocking the synthesis of acetylcholine", "A", "This increases synaptic acetylcholine levels. It crosses the BBB to treat atropine poisoning.", "HARD", "Textbook", "Cholinesterase inhibitors"),
    q("An organophosphate poisoning patient is treated with Atropine and Pralidoxime (PAM). PAM works by:", "Regenerating active acetylcholinesterase before it 'ages'", "Acting as a central muscarinic antagonist", "Directly degrading the organophosphate in the blood", "Downregulating nicotinic receptors", "A", "PAM binds the phosphorylated enzyme and removes the phosphate group.", "HARD", "Textbook", "Toxicity treatment"),
    q("Which sympathomimetic amine is the drug of choice for anaphylactic shock?", "Epinephrine", "Norepinephrine", "Dopamine", "Isoproterenol", "A", "Epinephrine strongly activates alpha-1 (vasoconstriction) and beta-2 (bronchodilation) to reverse shock.", "EASY", "Textbook", "Sympathomimetics"),
    q("Clonidine acts primarily as a(n):", "Central Alpha-2 agonist", "Peripheral Alpha-1 antagonist", "Beta-2 agonist", "Muscarinic antagonist", "A", "Stimulation of central presynaptic alpha-2 receptors decreases sympathetic outflow, lowering BP.", "MEDIUM", "Textbook", "Centrally acting agents")
  ]],
  ["Cardiovascular Pharmacology", [
    q("The primary mechanism of action of Thiazide diuretics (e.g., Hydrochlorothiazide) is:", "Inhibition of the Na+/Cl- cotransporter in the distal convoluted tubule", "Inhibition of the Na+/K+/2Cl- cotransporter in the Loop of Henle", "Aldosterone antagonism in the collecting duct", "Carbonic anhydrase inhibition in the proximal tubule", "A", "They are first-line for uncomplicated essential hypertension.", "MEDIUM", "Textbook", "Diuretics"),
    q("Which diuretic is most appropriate for rapid relief of acute pulmonary edema in heart failure?", "Furosemide (Loop diuretic)", "Spironolactone (Potassium-sparing)", "Hydrochlorothiazide", "Acetazolamide", "A", "Loop diuretics have profound and rapid diuretic effects ('high ceiling').", "EASY", "Textbook", "Diuretics"),
    q("ACE inhibitors (e.g., Lisinopril) lower blood pressure and predictably cause which common side effect due to bradykinin accumulation?", "Dry, hacking cough", "Severe hypokalemia", "Reflex tachycardia", "Peripheral edema", "A", "ACE degrades bradykinin; its inhibition leads to bradykinin accumulation in the lungs.", "EASY", "Textbook", "Antihypertensives"),
    q("Calcium channel blockers (e.g., Amlodipine, Verapamil) primarily block which type of calcium channel?", "L-type voltage-gated calcium channels", "T-type calcium channels", "N-type calcium channels", "Intracellular ryanodine receptors", "A", "They relax vascular smooth muscle (dihydropyridines) and slow cardiac conduction (non-dihydropyridines).", "MEDIUM", "Textbook", "Antihypertensives"),
    q("Digoxin increases myocardial contractility (positive inotropy) by inhibiting the:", "Na+/K+ ATPase pump", "Ca2+ ATPase pump", "Na+/Ca2+ exchanger directly", "Beta-1 adrenergic receptor", "A", "Inhibition raises intracellular Na+, which reverses the Na+/Ca2+ exchanger, increasing intracellular Ca2+.", "HARD", "Textbook", "Heart Failure Drugs"),
    q("Nitroglycerin relieves angina primarily by:", "Releasing Nitric Oxide (NO) which causes profound venodilation and reduces preload", "Blocking beta-1 receptors to slow the heart rate", "Directly dilating severely atherosclerotic coronary arteries", "Increasing cardiac contractility", "A", "Venodilation pools blood, decreasing returning volume (preload) and myocardial oxygen demand.", "MEDIUM", "Textbook", "Antianginal Drugs"),
    q("Which class of antiarrhythmic drugs primarily blocks fast sodium channels (Phase 0)?", "Class I (e.g., Lidocaine, Flecainide)", "Class II (Beta blockers)", "Class III (e.g., Amiodarone)", "Class IV (Calcium channel blockers)", "A", "Class I agents define their action by slowing the upstroke of the action potential.", "EASY", "Textbook", "Antiarrhythmics"),
    q("Amiodarone is a highly effective Class III antiarrhythmic but has significant long-term side effects including:", "Pulmonary fibrosis, thyroid dysfunction, and corneal microdeposits", "Systemic lupus erythematosus (SLE) like syndrome", "Severe hypokalemia", "Gingival hyperplasia", "A", "Amiodarone contains iodine (thyroid effects) and is highly lipophilic with long half-life tissue accumulation.", "HARD", "Textbook", "Antiarrhythmics"),
    q("Statins (e.g., Atorvastatin) lower serum cholesterol primarily by inhibiting:", "HMG-CoA reductase", "Lipoprotein lipase", "Intestinal cholesterol absorption", "Bile acid reabsorption", "A", "By inhibiting endogenous cholesterol synthesis in the liver, they upregulate LDL receptors.", "EASY", "Textbook", "Lipid-lowering Drugs"),
    q("Which lipid-lowering agent powerfully reduces triglycerides and can cause flushing and pruritus (preventable with aspirin)?", "Niacin (Vitamin B3)", "Ezetimibe", "Cholestyramine", "Gemfibrozil", "A", "Niacin inhibits lipolysis in adipose tissue and reduces VLDL synthesis in the liver.", "MEDIUM", "Textbook", "Lipid-lowering Drugs")
  ]],
  ["Chemotherapy (Antimicrobials & Oncology)", [
    q("The mechanism of action of Penicillins and Cephalosporins involves:", "Inhibition of bacterial cell wall synthesis by binding to Penicillin-Binding Proteins (PBPs)", "Inhibition of the 30S ribosomal subunit", "Inhibition of DNA gyrase", "Interference with folic acid synthesis", "A", "Beta-lactams are bactericidal, disrupting the cross-linking of peptidoglycan.", "EASY", "Textbook", "Antibacterial Drugs"),
    q("Which class of antibiotics inhibits protein synthesis by binding to the 50S ribosomal subunit?", "Macrolides (e.g., Azithromycin, Erythromycin)", "Tetracyclines", "Aminoglycosides", "Fluoroquinolones", "A", "Macrolides, Clindamycin, and Linezolid bind 50S (buy AT 30, CCEL at 50).", "MEDIUM", "Textbook", "Antibacterial Drugs"),
    q("Aminoglycosides (e.g., Gentamicin) exhibit notable serious toxicities affecting the:", "Kidneys (Nephrotoxicity) and Ears (Ototoxicity)", "Liver (Hepatotoxicity) and Heart", "Bone Marrow (Aplastic anemia)", "Tendons (Rupture)", "A", "Irreversible hearing loss and acute tubular necrosis are major risks.", "EASY", "Textbook", "Antibacterial Drugs"),
    q("Which antibiotic classically causes 'Red Man Syndrome' (histamine release) when infused intravenously too rapidly?", "Vancomycin", "Linezolid", "Ceftriaxone", "Daptomycin", "A", "Vancomycin requires slow infusion to prevent this non-allergic histamine release.", "EASY", "Textbook", "Antibacterial Drugs"),
    q("Fluoroquinolones (e.g., Ciprofloxacin) exert their bactericidal effect by inhibiting:", "DNA Gyrase (Topoisomerase II) and Topoisomerase IV", "RNA Polymerase", "Folic acid synthesis", "Cell wall cross-linking", "A", "This prevents DNA supercoiling and uncoiling necessary for replication.", "MEDIUM", "Textbook", "Antibacterial Drugs"),
    q("The combination of Sulfamethoxazole and Trimethoprim (Cotrimoxazole) is deeply synergistic because they:", "Sequentially block sequential steps in bacterial folic acid synthesis", "Both destroy the cell wall simultaneously", "Prevent protein synthesis at 30S and 50S subunits", "Increase one another's renal excretion half-life", "A", "Sulfa drugs inhibit dihydropteroate synthase; Trimethoprim inhibits dihydrofolate reductase.", "MEDIUM", "Textbook", "Antibacterial Drugs"),
    q("Isoniazid (INH), a first-line antitubercular drug, requires co-administration of which vitamin to prevent peripheral neuropathy?", "Pyridoxine (Vitamin B6)", "Thiamine (Vitamin B1)", "Folic acid", "Cobalamin (Vitamin B12)", "A", "INH competitively inhibits Vitamin B6 utilization.", "EASY", "Textbook", "Antimycobacterial Drugs"),
    q("Amphotericin B, a potent systemic antifungal, binds to the fungal cell membrane by interacting with:", "Ergosterol", "Cholesterol", "Peptidoglycan", "Beta-glucan", "A", "This forms artificial pores that cause lethal leakage of intracellular ions.", "HARD", "Textbook", "Antifungal Drugs"),
    q("Acyclovir is a guanosine analog specifically useful against Herpes Simplex Virus because it requires activation by the viral enzyme:", "Thymidine kinase", "Reverse transcriptase", "Protease", "DNA polymerase", "A", "Only infected cells with viral thymidine kinase can efficiently phosphorylate and trap acyclovir.", "MEDIUM", "Textbook", "Antiviral Drugs"),
    q("Methotrexate acts as a chemotherapeutic agent by competitively inhibiting:", "Dihydrofolate reductase (DHFR)", "Thymidylate synthase", "Ribonucleotide reductase", "DNA polymerase alpha", "A", "This deprives the rapidly dividing cell of tetrahydrofolate needed for purine/thymidine synthesis.", "MEDIUM", "Textbook", "Anticancer Drugs")
  ]]
];

writeSubject("Pharmacology", chapters, "pharmacology.json");
