const { q, writeSubject } = require('./qgen_helper');

const chapters = [
  ["General Surgery", [
    q("The most common cause of acute abdomen requiring surgical intervention in the western world is:", "Acute Appendicitis", "Acute Cholecystitis", "Perforated Peptic Ulcer", "Intestinal Obstruction", "A", "Appendicitis peaks in young adults and is the leading cause for emergent laparotomy.", "EASY", "Textbook", "Acute Abdomen"),
    q("In an older patient presenting with painless, massive lower GI bleeding, the most likely source is:", "Diverticulosis", "Colorectal Carcinoma", "Angiodysplasia", "Hemorrhoids", "A", "Bleeding from a diverticulum is characteristically abrupt, painless, and voluminous.", "MEDIUM", "Textbook", "GI Bleeding"),
    q("An otherwise healthy 25-year-old male presents with a tender, irreducible mass in the right groin. The mass originated above the inguinal ligament and passed through the superficial ring into the scrotum. This is a(n):", "Indirect Inguinal Hernia", "Direct Inguinal Hernia", "Femoral Hernia", "Hydrocele", "A", "Indirect hernias pass through the deep ring, often descending into the scrotum, and are the most common type.", "EASY", "Textbook", "Hernias"),
    q("Which type of hernia is most prone to incarceration and strangulation due to the narrow, rigid unyielding neck?", "Femoral Hernia", "Direct Inguinal Hernia", "Umbilical Hernia", "Hiatal Hernia", "A", "Femoral hernias pass through the narrow femoral ring and have a very high complication rate.", "MEDIUM", "Textbook", "Hernias"),
    q("The classical triad of an acute mechanical small bowel obstruction includes:", "Colicky abdominal pain, bilious vomiting, and obstipation", "Continuous pain, fever, and massive melena", "Painless jaundice, weight loss, and palpable gallbladder", "Right lower quadrant pain, anorexia, and rebound tenderness", "A", "These three symptoms point strongly to an obstruction requiring decompression.", "EASY", "Textbook", "Bowel Obstruction"),
    q("The most common cause of mechanical small bowel obstruction in adults with a history of prior abdominal surgery is:", "Intra-abdominal Adhesions", "Incarcerated Hernia", "Volvulus", "Intussusception", "A", "Post-operative adhesions are the leading cause. Hernias are second.", "EASY", "Textbook", "Bowel Obstruction"),
    q("A 'bird's beak' sign on barium enema or CT is pathognomonic for:", "Sigmoid Volvulus", "Achalasia", "Intussusception", "Crohn's Disease", "A", "The twisting of the distended sigmoid colon tapers symmetrically.", "MEDIUM", "Textbook", "Colorectal Surgery"),
    q("The most common breast mass in women under 30 is a:", "Fibroadenoma", "Fibrocystic change", "Intraductal papilloma", "Invasive ductal carcinoma", "A", "Fibroadenomas are benign, firm, highly mobile 'breast mice'.", "EASY", "Textbook", "Breast Surgery"),
    q("A 40-year-old female presents with a bloody nipple discharge from one breast. The most likely benign cause is:", "Intraductal Papilloma", "Fibrocystic Change", "Fat Necrosis", "Galactocele", "A", "Usually benign, but must be evaluated to rule out papillary carcinoma.", "MEDIUM", "Textbook", "Breast Surgery"),
    q("The initial investigation of choice for a patient presenting with thyroid nodule is:", "Ultrasound and Fine Needle Aspiration (FNA)", "Radioiodine uptake scan", "CT scan of the neck", "Excisional biopsy", "A", "Ultrasound guides the FNA, which is the gold standard for diagnosing thyroid malignancy.", "EASY", "Textbook", "Endocrine Surgery")
  ]],
  ["Trauma", [
    q("The most common organ injured in blunt abdominal trauma (e.g., steering wheel injury in a motor vehicle collision) is the:", "Spleen", "Liver", "Small Bowel", "Kidney", "A", "The speen is highly vascular and friable, making it susceptible to blunt force.", "EASY", "Textbook", "Abdominal Trauma"),
    q("In penetrating abdominal trauma (e.g., a stab wound to the abdomen), the most commonly injured organ is the:", "Liver", "Small Bowel", "Colon", "Stomach", "A", "The liver is the largest solid organ in the abdomen, frequently extending across the upper quadrants.", "EASY", "Textbook", "Abdominal Trauma"),
    q("According to Advanced Trauma Life Support (ATLS) protocols, the first priority in the primary survey of a multi-trauma patient is:", "Airway maintenance with cervical spine restriction", "Breathing and ventilation support", "Circulation and hemorrhage control", "Disability (Neurological status)", "A", "The ABCDE sequence strictly prioritizes establishing a patent airway first while protecting the C-spine.", "EASY", "Textbook", "ATLS guidelines"),
    q("A trauma patient presents with profound hypotension, distended neck veins, and absent breath sounds on the right hemithorax. The immediate necessary intervention is:", "Needle decompression in the 2nd intercostal space mid-clavicular line", "Endotracheal intubation", "Pericardiocentesis", "Massive blood transfusion", "A", "This represents a tension pneumothorax causing obstructive shock, requiring immediate decompression before CXR.", "HARD", "Textbook", "Thoracic Trauma"),
    q("Becks triad (hypotension, distended neck veins, muffled heart sounds) in a chest trauma patient strongly suggests:", "Cardiac Tamponade", "Tension Pneumothorax", "Massive Hemothorax", "Flail Chest", "A", "Penetrating injury to the heart fills the pericardium, restricting filling. Treated definitively by pericardial window/thoracotomy.", "MEDIUM", "Textbook", "Thoracic Trauma"),
    q("The Glasgow Coma Scale (GCS) evaluates all of the following parameters EXCEPT:", "Pupillary Light Reflex", "Eye Opening", "Verbal Response", "Motor Response", "A", "GCS (score 3-15) assesses Eye (4), Verbal (5), and Motor (6) responses to gauge consciousness.", "EASY", "Textbook", "Neurotrauma"),
    q("A biconvex (lens-shaped) hyperdensity on a head CT immediately following a head injury with a history of a brief 'lucid interval' is characteristic of an:", "Epidural Hematoma", "Subdural Hematoma", "Subarachnoid Hemorrhage", "Intraparenchymal Hemorrhage", "A", "Typically caused by tearing of the middle meningeal artery under the temporal bone.", "EASY", "Textbook", "Neurotrauma"),
    q("A crescent-shaped hyperdensity on a head CT, often seen in the elderly or alcoholics following minor trauma, represents a:", "Subdural Hematoma", "Epidural Hematoma", "Subarachnoid Hemorrhage", "Diffuse Axonal Injury", "A", "Resulting from the tearing of bridging veins tracing from the cortex to the dural sinuses.", "EASY", "Textbook", "Neurotrauma"),
    q("Which class of hemorrhagic shock is characterized by a heart rate > 120, a drop in systolic blood pressure, and confusion?", "Class III (30-40% blood loss)", "Class I (<15% blood loss)", "Class II (15-30% blood loss)", "Class IV (>40% blood loss)", "A", "Class III is the first stage where systolic BP begins to drop, signifying decompensation.", "HARD", "Textbook", "Hemorrhagic Shock"),
    q("The definitive test to evaluate for intra-abdominal bleeding in an unstable blunt trauma patient in the emergency department is typically the:", "Focused Assessment with Sonography for Trauma (FAST) exam", "Diagnostic Peritoneal Lavage (DPL)", "CT scan of the abdomen and pelvis", "Exploratory Laparotomy", "A", "The FAST scan rapidly identifies free fluid (blood) in the pericardial, perihepatic, perisplenic, and pelvic spaces.", "MEDIUM", "Textbook", "ATLS imaging")
  ]],
  ["Orthopedics", [
    q("The most common definitive sign of a fractured bone on physical examination is:", "Crepitus", "Pain and tenderness", "Swelling", "Loss of function", "A", "Crepitus is the grating sensation felt or heard when bone ends rub together.", "EASY", "Textbook", "Fractures"),
    q("A 'Colles' fracture' is classically described as a fracture of the:", "Distal radius with dorsal (posterior) displacement of the distal fragment", "Distal radius with volar (anterior) displacement", "Proximal ulna with an associated radial head dislocation", "Distal fibula and medial malleolus", "A", "This 'dinner-fork' deformity typically occurs from a fall onto an outstretched hand (FOOSH).", "EASY", "Textbook", "Upper Limb Fractures"),
    q("A 'Smith's fracture' (reverse Colles') involves:", "Distal radius with volar (anterior) displacement of the distal fragment", "Distal radius with dorsal displacement", "Scaphoid bone fracture", "Clavicle fracture", "A", "Typically caused by a fall onto the back of a flexed wrist.", "MEDIUM", "Textbook", "Upper Limb Fractures"),
    q("The most frequently fractured carpal bone is the:", "Scaphoid", "Lunate", "Triquetrum", "Capitate", "A", "Scaphoid fractures (FOOSH) are notorious for avascular necrosis due to retrograde blood supply.", "EASY", "Textbook", "Upper Limb Fractures"),
    q("A fracture of the proximal third of the ulna with dislocation of the radial head is called a:", "Monteggia fracture-dislocation", "Galeazzi fracture-dislocation", "Colles' fracture", "Nightstick fracture", "A", "Monteggia = proximal ulna + radial head. Galeazzi = distal radius + DRUJ dislocation.", "HARD", "Textbook", "Upper Limb Fractures"),
    q("The most common form of joint dislocation is:", "Anterior dislocation of the shoulder", "Posterior dislocation of the shoulder", "Posterior dislocation of the hip", "Anterior dislocation of the hip", "A", "The glenohumeral joint's shallow socket makes it highly susceptible to anterior instability.", "EASY", "Textbook", "Dislocations"),
    q("A shortened, externally rotated leg in an elderly patient following a minor fall is classically indicative of a:", "Fracture of the neck of the femur", "Posterior dislocation of the hip", "Anterior dislocation of the hip", "Femoral shaft fracture", "A", "The powerful gluteal and short external rotator muscles pull the fractured femur.", "EASY", "Textbook", "Lower Limb Fractures"),
    q("In contrast, a posterior dislocation of the hip typically presents with the leg:", "Shortened, internally rotated, and adducted", "Shortened and externally rotated", "Lengthened and externally rotated", "Lengthened and internally rotated", "A", "Usually caused by a significant force, like a knee hitting the dashboard in an MVA.", "MEDIUM", "Textbook", "Dislocations"),
    q("Compression of the median nerve as it passes under the transverse carpal ligament produces which common entrapment neuropathy?", "Carpal Tunnel Syndrome", "Cubital Tunnel Syndrome", "Guyon's Canal Syndrome", "Thoracic Outlet Syndrome", "A", "Characterized by numbness and tingling in the thumb, index, and middle fingers.", "EASY", "Textbook", "Nerve Entrapment"),
    q("A child pulled suddenly by the hand resulting in radial head subluxation (Nursemaid's elbow) will typically hold the arm:", "Pronated and slightly flexed, refusing to use it", "Supinated and fully extended", "Abducted and externally rotated", "Tightly flexed against the chest", "A", "The annular ligament slips over the radial head. Easily reduced by supination/flexion.", "MEDIUM", "Textbook", "Pediatric Orthopedics")
  ]]
];

writeSubject("Surgery", chapters, "surgery.json");
