const { q, writeSubject } = require('./qgen_helper');

const chapters = [
  ["Obstetrics", [
    q("The most common definitive sign of pregnancy on ultrasound at 5-6 weeks gestation is the presence of a:", "Gestational sac with a yolk sac", "Fetal pole with cardiac activity", "Thickened endometrium", "Corpus luteum cyst", "A", "The yolk sac confirms an intrauterine pregnancy before the embryo is clearly visible.", "EASY", "Textbook", "Antenatal Care"),
    q("A 28-year-old primigravida at 32 weeks presents with a blood pressure of 150/100 mmHg and +2 proteinuria. The most likely diagnosis is:", "Preeclampsia", "Gestational Hypertension", "Chronic Hypertension", "Eclampsia", "A", "New-onset hypertension and proteinuria after 20 weeks define preeclampsia.", "EASY", "Textbook", "Hypertensive Disorders"),
    q("The definitive, life-saving treatment for severe preeclampsia/eclampsia is:", "Delivery of the fetus and placenta", "Intravenous Magnesium Sulfate", "Antihypertensive therapy (Labetalol)", "Strict bed rest", "A", "While MgSO4 prevents seizures and antihypertensives control BP, only delivery cures the condition.", "MEDIUM", "Textbook", "Hypertensive Disorders"),
    q("Which drug is the gold standard for the prevention and treatment of eclamptic seizures?", "Magnesium Sulfate", "Diazepam", "Phenytoin", "Levetiracetam", "A", "MgSO4 is superior to other anticonvulsants for eclampsia.", "EASY", "Textbook", "Hypertensive Disorders"),
    q("A pregnant woman presents with sudden, dark red vaginal bleeding and severe, constant abdominal pain. The uterus is woody hard and tender. Diagnosis?", "Abruptio Placentae (Placental Abruption)", "Placenta Previa", "Vasa Previa", "Uterine Rupture", "A", "Premature separation of the placenta causes painful bleeding and a hypertonic uterus.", "EASY", "Textbook", "Antepartum Hemorrhage"),
    q("Painless, bright red vaginal bleeding in the third trimester is the classic presentation of:", "Placenta Previa", "Abruptio Placentae", "Vasa Previa", "Bloody show (normal labor)", "A", "The placenta implants over or near the internal cervical os, bleeding when the cervix dilates.", "EASY", "Textbook", "Antepartum Hemorrhage"),
    q("The most common cause of postpartum hemorrhage (PPH) is:", "Uterine Atony", "Retained placental fragments", "Genital tract lacerations", "Coagulation disorders", "A", "Failure of the uterus to contract ('boggy uterus') accounts for 70-80% of PPH.", "EASY", "Textbook", "Postpartum Hemorrhage"),
    q("Which uterotonic agent is contraindicated in a patient with severe asthma and postpartum hemorrhage?", "Carboprost (Hemabate - 15-methyl PGF2a)", "Oxytocin", "Methylergonovine (Methergine)", "Misoprostol", "A", "Prostaglandin F2 alpha causes severe bronchoconstriction.", "HARD", "Textbook", "Postpartum Hemorrhage"),
    q("A pregnant woman at 28 weeks has a 1-hour 50g oral glucose tolerance test (OGTT) result of 180 mg/dL. What is the next best step?", "3-hour 100g oral glucose tolerance test", "Start insulin therapy immediately", "Advise dietary modifications and retest in 4 weeks", "Diagnose Gestational Diabetes Mellitus directly", "A", "A failed 1-hour screen requires the definitive 3-hour diagnostic OGTT.", "MEDIUM", "Textbook", "Medical Disorders in Pregnancy"),
    q("The most common presentation of a twin gestation is:", "Cephalic-Cephalic", "Cephalic-Breech", "Breech-Cephalic", "Breech-Breech", "A", "Both fetuses presenting vertex is the most common and safest for vaginal delivery.", "MEDIUM", "Textbook", "Multiple Gestation")
  ]],
  ["Gynecology", [
    q("The most common benign tumor of the uterus, which grows in response to estrogen, is a:", "Leiomyoma (Fibroid)", "Endometrial polyp", "Cervical polyp", "Adenomyoma", "A", "Fibroids are extremely common and often present with heavy menstrual bleeding.", "EASY", "Textbook", "Uterine Fibroids"),
    q("A 35-year-old female presents with severe dysmenorrhea, deep dyspareunia, and chronic pelvic pain. The most likely diagnosis is:", "Endometriosis", "Pelvic Inflammatory Disease (PID)", "Polycystic Ovary Syndrome (PCOS)", "Uterine Fibroids", "A", "These are the hallmark '3 Ds' of endometriosis (plus dyschezia and infertility).", "EASY", "Textbook", "Endometriosis"),
    q("The gold standard for the definitive diagnosis of endometriosis is:", "Laparoscopy with histological confirmation", "Transvaginal Ultrasound", "CA-125 level", "MRI of the pelvis", "A", "Visualizing characteristic lesions ('powder-burn') and biopsy are required for formal diagnosis.", "MEDIUM", "Textbook", "Endometriosis"),
    q("Polycystic Ovary Syndrome (PCOS) is classically diagnosed using the Rotterdam Criteria, which requires two of three findings: hyperandrogenism, polycystic ovaries on ultrasound, and:", "Oligo- or Anovulation", "Insulin Resistance", "Obesity", "Elevated LH:FSH ratio", "A", "Irregular menses due to oligo/anovulation is a core component.", "EASY", "Textbook", "PCOS"),
    q("The most common cause of cervical cancer is persistent infection with high-risk types of which virus?", "Human Papillomavirus (HPV)", "Herpes Simplex Virus (HSV)", "Epstein-Barr Virus (EBV)", "Cytomegalovirus (CMV)", "A", "HPV types 16 and 18 cause the vast majority of cervical carcinomas.", "EASY", "Textbook", "Cervical Cancer"),
    q("Which Papanicolaou (Pap) smear finding indicates the highest risk for developing invasive cervical squamous cell carcinoma?", "High-grade Squamous Intraepithelial Lesion (HSIL)", "Atypical Squamous Cells of Undetermined Significance (ASC-US)", "Low-grade Squamous Intraepithelial Lesion (LSIL)", "Atypical Glandular Cells (AGC)", "A", "HSIL corresponds to CIN 2 or CIN 3, representing true dysplasia.", "MEDIUM", "Textbook", "Cervical Screening"),
    q("The classic presentation of a ruptured ectopic pregnancy includes amenorrhea, vaginal bleeding, and:", "Severe lower abdominal pain with rigid abdomen and shock", "Painless bright red vaginal bleeding", "High fever and purulent vaginal discharge", "Sudden increase in uterine size", "A", "Rupture causes intra-abdominal hemorrhage leading to peritonitis and hypovolemic shock.", "EASY", "Textbook", "Ectopic Pregnancy"),
    q("A 60-year-old postmenopausal woman presents with vaginal bleeding. The most critical diagnosis to rule out is:", "Endometrial Carcinoma", "Atrophic vaginitis", "Endometrial polyp", "Cervical cancer", "A", "Postmenopausal bleeding must be considered endometrial cancer until proven otherwise.", "EASY", "Textbook", "Endometrial Cancer"),
    q("Which serum tumor marker is typically elevated and used to track the progression or recurrence of Epithelial Ovarian Cancer?", "CA-125", "CEA", "AFP", "Beta-hCG", "A", "CA-125 is highly sensitive for serous ovarian carcinomas.", "EASY", "Textbook", "Ovarian Cancer"),
    q("Pelvic Inflammatory Disease (PID) is most commonly caused by ascending infection of:", "Chlamydia trachomatis and Neisseria gonorrhoeae", "Escherichia coli and Enterococcus", "Candida albicans and Trichomonas vaginalis", "Human Papillomavirus", "A", "These STIs ascend from the cervix to cause endometritis, salpingitis, and tubo-ovarian abscesses.", "EASY", "Textbook", "Pelvic Infections")
  ]]
];

writeSubject("OBGYN", chapters, "obgyn.json");
