const { q, writeSubject } = require('./qgen_helper');

const chapters = [
  ["General Microbiology", [
    q("Which of the following bacterial cell structures is primarily responsible for preventing osmotic lysis?", "Peptidoglycan cell wall", "Plasma membrane", "Capsule", "Lipopolysaccharide (LPS)", "A", "The rigid peptidoglycan layer protects bacteria from osmotic pressure.", "EASY", "Textbook", "Bacterial structure"),
    q("Gram-positive bacteria differ from Gram-negative bacteria in that they have:", "A thicker peptidoglycan layer and teichoic acids", "An outer membrane containing LPS", "A periplasmic space", "Porin channels", "A", "Gram-positive cell walls are thick peptidoglycan with embedded teichoic acids.", "EASY", "Textbook", "Gram stain"),
    q("Endospores in bacteria are highly resistant primarily due to the presence of:", "Calcium dipicolinate", "Mycolic acid", "Teichoic acid", "Ergosterol", "A", "Dipicolinic acid complexed with calcium dehydrates and protects the spore.", "MEDIUM", "Textbook", "Spores"),
    q("Which bacterial appendage allows for the transfer of DNA between cells (conjugation)?", "Sex pilus", "Flagellum", "Fimbriae", "Capsule", "A", "The sex pilus connects a donor and recipient cell for plasmid transfer.", "EASY", "Textbook", "Bacterial genetics"),
    q("In bacterial growth curves, secondary metabolites like antibiotics are typically produced during the:", "Stationary phase", "Lag phase", "Logarithmic (exponential) phase", "Death phase", "A", "Production of secondary metabolites occurs when nutrients deplete in stationary phase.", "MEDIUM", "Textbook", "Bacterial growth"),
    q("Plasmids are best described as:", "Extrachromosomal, circular, double-stranded DNA molecules", "Single-stranded RNA genomes", "Essential genes for basic survival", "Proteinaceous infectious particles", "A", "Plasmids replicate independently and often carry accessory genes (e.g., resistance).", "EASY", "Textbook", "Bacterial genetics"),
    q("An organism that requires oxygen to grow but is killed by atmospheric levels (~21% O2) is called a:", "Microaerophile", "Facultative anaerobe", "Obligate aerobe", "Aerotolerant anaerobe", "A", "Microaerophiles need O2 at lower concentrations (e.g., Campylobacter, Helicobacter).", "MEDIUM", "Textbook", "Oxygen requirements"),
    q("The transfer of bacterial DNA from one cell to another via a bacteriophage is termed:", "Transduction", "Transformation", "Conjugation", "Transfection", "A", "Transduction involves a viral vector (phage) moving host bacterial DNA.", "MEDIUM", "Textbook", "Bacterial genetics"),
    q("Which of the following sterilization methods reliably destroys bacterial endospores?", "Autoclaving (121°C for 15 mins at 15 psi)", "Boiling water for 10 minutes", "Pasteurization", "70% Isopropyl alcohol", "A", "Moist heat under pressure is required to kill highly resistant spores.", "EASY", "Textbook", "Sterilization"),
    q("Endotoxin (Lipopolysaccharide, LPS) is an integral component of the cell wall of:", "Gram-negative bacteria only", "Gram-positive bacteria only", "Both Gram-positive and Gram-negative bacteria", "Fungi", "A", "LPS is located in the outer leaflet of the Gram-negative outer membrane.", "EASY", "Textbook", "Bacterial toxins")
  ]],
  ["Immunology", [
    q("Which immunoglobulin class is the first to be produced in a primary immune response?", "IgM", "IgG", "IgA", "IgE", "A", "IgM is the initial antibody produced, circulating as a pentamer.", "EASY", "Textbook", "Antibodies"),
    q("The most abundant immunoglobulin in serum, responsible for providing passive immunity to the fetus, is:", "IgG", "IgA", "IgM", "IgE", "A", "IgG is the only isotype that crosses the placenta.", "EASY", "Textbook", "Antibodies"),
    q("Which of the following cells is a 'professional' antigen-presenting cell (APC) that activates naive T cells?", "Dendritic cell", "Neutrophil", "Natural Killer (NK) cell", "Mast cell", "A", "Dendritic cells are the most potent APCs for initiating primary T cell responses.", "MEDIUM", "Textbook", "Cellular immunity"),
    q("MHC Class I molecules present endogenous antigens to:", "CD8+ Cytotoxic T cells", "CD4+ Helper T cells", "B cells", "Macrophages", "A", "MHC I is found on all nucleated cells and presents peptides to CD8+ cells (Rule of 8: 1x8=8).", "MEDIUM", "Textbook", "MHC"),
    q("Which complement pathway is activated by antigen-antibody complexes (IgG or IgM)?", "Classical pathway", "Alternative pathway", "Lectin pathway", "Properdin pathway", "A", "The classical pathway starts with C1q binding to the Fc portion of bound antibodies.", "EASY", "Textbook", "Complement system"),
    q("The membrane attack complex (MAC) of the complement system consists of:", "C5b, C6, C7, C8, C9", "C1, C4, C2, C3", "C3b, Bb, Properdin", "C3a, C4a, C5a", "A", "The MAC forms a pore in the target cell membrane, causing lysis.", "MEDIUM", "Textbook", "Complement system"),
    q("Which cytokine is a potent stimulator of macrophages and is primarily produced by Th1 cells?", "Interferon-gamma (IFN-y)", "Interleukin-4 (IL-4)", "Interleukin-10 (IL-10)", "TGF-beta", "A", "IFN-gamma is the defining signature cytokine of the Th1 subset.", "HARD", "Textbook", "Cytokines"),
    q("Negative selection in the thymus involves:", "Apoptosis of T cells that bind too strongly to self-MHC/self-peptides", "Survival of T cells that recognize self-MHC", "Activation of regulatory T cells", "Class switching of B cells", "A", "Negative selection eliminates autoreactive T cells to establish central tolerance.", "HARD", "Textbook", "T cell development"),
    q("Natural Killer (NK) cells target and destroy virus-infected or tumor cells that generally:", "Downregulate or lack MHC Class I expression", "Express high levels of MHC Class II", "Are coated with IgE antibodies", "Express bacterial LPS", "A", "NK cells kill 'missing-self' targets when inhibitory signals from MHC I are absent.", "MEDIUM", "Textbook", "Innate immunity"),
    q("Which immunoglobulin is prominently found in mucosal secretions, tears, and breast milk?", "Secretory IgA", "IgE", "IgG", "IgD", "A", "IgA as a dimer with a secretory component protects mucosal surfaces.", "EASY", "Textbook", "Antibodies")
  ]],
  ["Bacteriology General", [
    q("Which bacterial genus is characterized by a cell wall containing large amounts of lipid (mycolic acid) and does not stain well with Gram stain?", "Mycobacterium", "Mycoplasma", "Staphylococcus", "Escherichia", "A", "Mycobacteria are acid-fast because of their waxy, lipid-rich cell envelope.", "EASY", "Textbook", "Bacterial characteristics"),
    q("Which of the following bacteria completely lacks a cell wall?", "Mycoplasma pneumoniae", "Mycobacterium tuberculosis", "Chlamydia trachomatis", "Treponema pallidum", "A", "Mycoplasma species lack a rigid peptidoglycan cell wall and thus are pleomorphic and PCN-resistant.", "MEDIUM", "Textbook", "Atypical bacteria"),
    q("The Quellung reaction is used to identify bacteria that possess a:", "Capsule", "Flagellum", "Spore", "Fimbriae", "A", "The Quellung reaction ('swelling' of the capsule) uses type-specific antiserum to identify capsulated bacteria like Strep pyogenes/pneumoniae.", "MEDIUM", "Textbook", "Diagnostic microbiology"),
    q("Which group of bacteria obligately reside inside host cells to replicate because they cannot synthesize their own ATP?", "Chlamydia and Rickettsia", "Mycoplasma", "Pseudomonas and Acinetobacter", "Clostridium", "A", "They are obligate intracellular parasites.", "MEDIUM", "Textbook", "Intracellular bacteria"),
    q("Which toxic byproduct of oxygen metabolism is detoxified by the enzyme catalase?", "Hydrogen peroxide (H2O2)", "Superoxide radical (O2-)", "Hydroxyl radical (OH-)", "Ozone", "A", "Catalase converts 2H2O2 into 2H2O and O2. Strict anaerobes lack catalase.", "MEDIUM", "Textbook", "Bacterial metabolism"),
    q("Endotoxins are characterized by being:", "Heat-stable lipopolysaccharides", "Heat-labile proteins", "Secreted continuously by living cells", "Highly immunogenic and easily converted to toxoids", "A", "Endotoxins (LPS, specifically Lipid A) are heat stable and intrinsic to the Gram-negative outer membrane.", "MEDIUM", "Textbook", "Bacterial pathogenesis"),
    q("An A-B exotoxin works primarily by:", "The B subunit binding to a host receptor, allowing the A subunit to enter and exhibit activity", "Forming pores directly in the target cell membrane", "Acting as a superantigen on T-cells", "Inducing a massive release of IL-1 and TNF", "A", "B=Binding, A=Action (usually ADP-ribosylation of a target protein).", "HARD", "Textbook", "Exotoxins"),
    q("Koch's postulates are used to:", "Establish a causal relationship between a microbe and a disease", "Determine the minimum inhibitory concentration of an antibiotic", "Classify bacteria based on their rRNA sequences", "Identify the structural components of viruses", "A", "The postulates remain the historical standard for proving infectious etiology.", "EASY", "Textbook", "Principles of microbiology"),
    q("The mechanism of action of Penicillins is?", "Inhibition of transpeptidation (cross-linking) in cell wall synthesis", "Binding to the 30S ribosomal subunit", "Inhibition of DNA gyrase", "Inhibition of RNA polymerase", "A", "Beta-lactams bind Penicillin-Binding Proteins (PBPs), disrupting peptidoglycan synthesis.", "EASY", "Textbook", "Antimicrobials"),
    q("Chocolate agar is specifically used for the isolation of fastidious organisms such as:", "Neisseria and Haemophilus", "Escherichia and Klebsiella", "Staphylococcus and Streptococcus", "Salmonella and Shigella", "A", "Heating blood releases factor X (hemin) and factor V (NAD) needed for these organisms.", "MEDIUM", "Textbook", "Culture media")
  ]],
  ["Gram Positive Cocci", [
    q("Which test is primarily used to differentiate Staphylococcus species from Streptococcus species?", "Catalase test", "Coagulase test", "Oxidase test", "Gram stain", "A", "Staphylococci are catalase-positive; Streptococci are catalase-negative.", "EASY", "Textbook", "Diagnostic microbiology"),
    q("Staphylococcus aureus is uniquely identified among Staphylococci by a positive:", "Coagulase test", "Catalase test", "Urease test", "Novobiocin susceptibility", "A", "S. aureus produces coagulase, converting fibrinogen to fibrin.", "EASY", "Textbook", "Diagnostic microbiology"),
    q("Protein A is an important virulence factor of S. aureus because it:", "Binds the Fc portion of IgG, preventing opsonization and phagocytosis", "Lyses red blood cells", "Degrades host hyaluronic acid", "Causes massive, widespread T-cell activation", "A", "By binding IgG backward, it hides from phagocytic cells.", "HARD", "Textbook", "Virulence factors"),
    q("Rheumatic fever is a post-infectious, non-suppurative complication of infection with:", "Streptococcus pyogenes (Group A Strep)", "Streptococcus pneumoniae", "Staphylococcus aureus", "Enterococcus faecalis", "A", "Follows Group A streptococcal pharyngitis due to molecular mimicry.", "EASY", "Textbook", "Streptococcus"),
    q("The most common cause of community-acquired pneumonia and adult bacterial meningitis is:", "Streptococcus pneumoniae", "Staphylococcus aureus", "Neisseria meningitidis", "Haemophilus influenzae", "A", "S. pneumoniae (pneumococcus) is a lancet-shaped, gram-positive diplococcus.", "MEDIUM", "Textbook", "Clinical microbiology"),
    q("Which organism is the most common cause of subacute infective endocarditis following dental procedures?", "Viridans group streptococci", "Staphylococcus aureus", "Streptococcus pyogenes", "Enterococcus faecalis", "A", "Viridans strep are normal oral flora that can seed diseased heart valves.", "MEDIUM", "Textbook", "Clinical microbiology"),
    q("Streptococcus agalactiae (Group B Strep) is most notable for causing:", "Neonatal meningitis and sepsis", "Adult pharyngitis", "Toxic shock syndrome", "Erysipelas", "A", "GBS is a major cause of morbidity in newborns passing through a colonized birth canal.", "EASY", "Textbook", "Clinical microbiology"),
    q("Which mechanism confers resistance to methicillin in MRSA?", "Alteration of penicillin-binding protein (PBP-2a) encoded by the mecA gene", "Production of beta-lactamase", "Efflux pumps", "Mutation in DNA gyrase", "A", "The altered target (PBP-2a) has low affinity for all beta-lactam antibiotics.", "HARD", "Textbook", "Antimicrobial resistance"),
    q("Enterococci are intrinsically resistant to:", "Cephalosporins", "Vancomycin only", "Linezolid", "Ampicillin", "A", "Enterocci have natural resistance to all cephalosporins.", "HARD", "Textbook", "Enterococcus"),
    q("A young woman presents with a sudden onset of high fever, rash, desquamation, and hypotension. Which toxin is likely responsible?", "Toxic Shock Syndrome Toxin-1 (TSST-1) from S. aureus", "Erythrogenic toxin from S. pyogenes", "Alpha-toxin from C. perfringens", "Enterotoxin from S. aureus", "A", "TSST-1 functions as a superantigen, causing a massive cytokine storm.", "MEDIUM", "Textbook", "Bacterial toxins")
  ]],
  ["Gram Negative Bacilli", [
    q("Which of the following organisms is the most common cause of uncomplicated urinary tract infections (UTIs)?", "Escherichia coli", "Pseudomonas aeruginosa", "Klebsiella pneumoniae", "Proteus mirabilis", "A", "Uropathogenic E. coli (UPEC) causes >80% of community-acquired UTIs.", "EASY", "Textbook", "Clinical microbiology"),
    q("Hemolytic Uremic Syndrome (HUS), characterized by microangiopathic hemolytic anemia, thrombocytopenia, and acute kidney injury, is typically caused by:", "Enterohemorrhagic E. coli (EHEC), primarily O157:H7", "Enterotoxigenic E. coli (ETEC)", "Salmonella Typhi", "Vibrio cholerae", "A", "EHEC produces Shiga-like toxins that damage endothelial cells.", "MEDIUM", "Textbook", "Clinical microbiology"),
    q("Which organism causes typhoid fever and presents with 'rose spots' on the abdomen?", "Salmonella Typhi", "Shigella dysenteriae", "Campylobacter jejuni", "Yersinia enterocolitica", "A", "S. Typhi causes systemic enteric fever and establishes a carrier state in the gallbladder.", "EASY", "Textbook", "Salmonella"),
    q("A non-lactose fermenting, oxidase-negative, highly motile gram-negative rod that produces H2S is most likely:", "Salmonella species", "Shigella species", "Escherichia coli", "Pseudomonas aeruginosa", "A", "Salmonella is motile and H2S positive; Shigella is non-motile and H2S negative.", "MEDIUM", "Textbook", "Enterobacteriaceae"),
    q("Vibrio cholerae causes massive watery 'rice-water' diarrhea through a toxin mechanism that:", "Permanently activates Gs, increasing intracellular cAMP", "Inhibits protein synthesis by inactivating the 60S ribosome", "Permanently activates Gi, decreasing cAMP", "Forms pores in the intestinal epithelial membrane", "A", "Cholera toxin ADP-ribosylates the Gs alpha subunit, leading to fluid hypersecretion.", "HARD", "Textbook", "Bacterial toxins"),
    q("An oxidase-positive, non-lactose fermenting gram-negative rod that produces a sweet, grape-like odor and green-blue pigment is:", "Pseudomonas aeruginosa", "Klebsiella pneumoniae", "Proteus mirabilis", "Serratia marcescens", "A", "P. aeruginosa is notable for pyocyanin (blue) and pyoverdine (fluorescent green) pigments.", "EASY", "Textbook", "Pseudomonas"),
    q("Which organism is the major cause of gastritis and most peptic ulcers, and produces copious amounts of urease?", "Helicobacter pylori", "Campylobacter jejuni", "Vibrio cholerae", "Salmonella Enteritidis", "A", "H. pylori uses urease to create an alkaline microenvironment in the acidic stomach.", "EASY", "Textbook", "H. pylori"),
    q("A curved, 'seagull-shaped', microaerophilic gram-negative rod that is a leading cause of bacterial gastroenteritis in developed countries is:", "Campylobacter jejuni", "Vibrio vulnificus", "Helicobacter pylori", "Shigella sonnei", "A", "C. jejuni grows well at 42°C and is frequently acquired from undercooked poultry.", "MEDIUM", "Textbook", "Campylobacter"),
    q("Which bacteria demonstrates 'swarming' motility on an agar plate and produces urease, strongly predisposing to struvite kidney stones?", "Proteus mirabilis", "Klebsiella pneumoniae", "Pseudomonas aeruginosa", "Escherichia coli", "A", "Urease splits urea to ammonia, raising urine pH and precipitating Mg-ammonium-phosphate stones.", "MEDIUM", "Textbook", "Proteus"),
    q("Klebsiella pneumoniae is characterized by:", "A large polysaccharide capsule giving mucoid colonies and 'currant jelly' sputum", "A flagellum giving highly active swarming motility", "Absolute requirement for Factor X and V to grow", "Intracellular replication within macrophages", "A", "The prominent capsule prevents phagocytosis and causes explosive, necrotizing lobar pneumonia.", "MEDIUM", "Textbook", "Klebsiella")
  ]],
  ["Mycobacteria", [
    q("Mycobacteria are difficult to stain with standard Gram stain due to the high concentration of which substance in their cell walls?", "Mycolic acid", "Peptidoglycan", "Teichoic acid", "Lipopolysaccharide", "A", "The waxy mycolic acid requires acid-fast staining (Ziehl-Neelsen).", "EASY", "Textbook", "Bacterial structure"),
    q("The primary lung lesion of initial Mycobacterium tuberculosis infection, usually located in the lower lobes and associated with a hilar lymph node, is the:", "Ghon complex", "Simon focus", "Aspergilloma", "Cavitary lesion", "A", "The Ghon complex is a calcified parenchymal lesion and calcified hilar node.", "MEDIUM", "Textbook", "Tuberculosis pathogenesis"),
    q("Which component of M. tuberculosis stimulates the delayed-type hypersensitivity (Type IV) response measured in the PPD test?", "Purified protein derivatives (tuberculin)", "Cord factor", "Sulfatides", "Mycolic acid", "A", "T cells sensitized to these proteins respond by causing local induration.", "MEDIUM", "Textbook", "Diagnostic testing"),
    q("Multidrug-resistant Tuberculosis (MDR-TB) is defined as resistance to at least:", "Isoniazid and Rifampin", "Streptomycin and Ethambutol", "Pyrazinamide and Isoniazid", "Fluoroquinolones and Injectables", "A", "INH and RIF are the two most potent first-line anti-TB drugs.", "HARD", "Textbook", "Antimicrobial resistance"),
    q("The virulence of M. tuberculosis is strongly correlated with its ability to grow in 'serpentine cords'. This is mediated by:", "Cord factor (Trehalose dimycolate)", "Sulfatides", "Tuberculin surface protein", "Catalase-peroxidase", "A", "Cord factor inhibits macrophage maturation and induces TNF-alpha release.", "HARD", "Textbook", "Virulence factors"),
    q("Leprosy (Hansen's disease) is caused by Mycobacterium leprae. Which form represents a weak cell-mediated (Th1) immune response and high bacterial burden?", "Lepromatous leprosy", "Tuberculoid leprosy", "Borderline tuberculoid leprosy", "Indeterminate leprosy", "A", "Lepromatous leprosy (Th2 dominant) involves widespread, lion-like facial deformities and high infectivity.", "MEDIUM", "Textbook", "Leprosy"),
    q("M. leprae preferentially replicates in:", "Cooler regions of the body (skin and peripheral nerves)", "The apices of the lungs", "Hepatocytes", "The central nervous system", "A", "The bacteria thrive at roughly 30°C, leading to peripheral nerve damage and anesthesia.", "MEDIUM", "Textbook", "Leprosy"),
    q("Which of the following is considered 'Atypical Mycobacteria' or Non-Tuberculous Mycobacteria (NTM) that frequently causes disseminated disease in late-stage AIDS patients?", "Mycobacterium avium complex (MAC)", "Mycobacterium bovis", "Mycobacterium leprae", "Mycobacterium africanum", "A", "MAC causes severe, widespread infection when CD4 counts drop below 50.", "EASY", "Textbook", "NTM"),
    q("Which vaccine, used to prevent severe forms of childhood TB, involves a live-attenuated strain of Mycobacterium bovis?", "BCG (Bacille Calmette-Guerin) vaccine", "DTP vaccine", "HiB vaccine", "Pneumococcal conjugate vaccine", "A", "BCG gives variable protection but prevents TB meningitis in kids.", "EASY", "Textbook", "Vaccines"),
    q("A positive IGRA (Interferon-Gamma Release Assay) indicates:", "Prior exposure to M. tuberculosis (latent or active infection)", "Successful BCG vaccination", "Active infectious state requiring immediate isolation", "Immunity to subsequent TB infection", "A", "IGRA measures T-cell release of IFN-y but cannot distinguish latent from active TB. It is not confounded by BCG.", "MEDIUM", "Textbook", "Diagnostic testing")
  ]],
  ["Virology General", [
    q("Viruses are defined as obligate intracellular parasites because they:", "Lack the metabolic machinery (e.g., ribosomes) to synthesize proteins", "Cannot survive outside a host for more than a few minutes", "Do not possess a genome of their own", "Always integrate into host DNA", "A", "They must hijack the host's ribosomes, ATP, and enzymes to replicate.", "EASY", "Textbook", "Viral properties"),
    q("The protein coat that surrounds and protects the viral nucleic acid genome is the:", "Capsid", "Envelope", "Peplomer", "Matrix", "A", "The capsid plus the enclosed genome form the nucleocapsid.", "EASY", "Textbook", "Viral structure"),
    q("A viral envelope is typically acquired when the virus:", "Buds through a host cell membrane (plasma, ER, or Golgi)", "Synthesizes lipids de novo inside the cytoplasm", "Absorbs lipids from the extracellular environment", "Lyses the host cell", "A", "Enveloped viruses acquire their lipid bilayer from the host during assembly and egress.", "MEDIUM", "Textbook", "Viral structure"),
    q("Naked (non-enveloped) viruses tend to be:", "More resistant to harsh environmental conditions (e.g., acid, detergents)", "More susceptible to destruction by alcohol or detergents", "Unable to infect animal cells", "Larger than enveloped viruses", "A", "Lacking a fragile lipid envelope, naked viruses (like enteroviruses) survive better on surfaces and in the GI tract.", "MEDIUM", "Textbook", "Viral properties"),
    q("In terms of genome type, all known viruses use:", "Either DNA or RNA, but not both concurrently as their genome", "Only double-stranded DNA", "Only single-stranded RNA", "Both DNA and RNA simultaneously", "A", "Viruses are broadly classified as DNA viruses or RNA viruses.", "EASY", "Textbook", "Viral genomes"),
    q("Which RNA virus genome can be immediately translated by host ribosomes upon entry into the cell?", "Positive-sense (+) straight-stranded RNA", "Negative-sense (-) single-stranded RNA", "Double-stranded RNA", "Retroviral RNA", "A", "(+) ssRNA functions just like cellular mRNA.", "HARD", "Textbook", "Viral genetics"),
    q("Negative-sense (-) RNA viruses must carry which functional enzyme within their virion to begin replication?", "RNA-dependent RNA polymerase", "Reverse transcriptase", "DNA-dependent DNA polymerase", "RNA-dependent DNA polymerase", "A", "The host lacks the enzyme to synthesize (+) RNA from a (-) RNA template.", "HARD", "Textbook", "Viral replication"),
    q("Antigenic shift in influenza viruses occurs due to:", "Reassortment of genomic segments when two distinct strains co-infect a cell", "Accumulation of point mutations in the hemagglutinin gene over time", "Integration into the host chromosome", "A phase variation switch", "A", "Segmented genome reassortment leads to sudden, major changes (pandemics). Point mutations cause 'drift'.", "MEDIUM", "Textbook", "Viral genetics"),
    q("Prions are unique infectious agents because they are composed solely of:", "An abnormally folded protein with no nucleic acid", "A naked circular RNA molecule", "A piece of DNA without a capsid", "A lipopolysaccharide toxin", "A", "Prions cause transmissible spongiform encephalopathies (e.g., Creutzfeldt-Jakob Disease) purely by protein misfolding.", "MEDIUM", "Textbook", "Atypical agents"),
    q("Viral tropism (the specificity a virus has for a particular host tissue) is determined primarily by:", "Specific interactions between viral surface proteins and host cell receptors", "The type of nucleic acid the virus possesses", "The size of the virion", "The host's body temperature", "A", "Example: HIV gp120 binding specifically to host CD4.", "EASY", "Textbook", "Pathogenesis")
  ]],
  ["DNA Viruses", [
    q("Which DNA virus is NOT double-stranded?", "Parvovirus (e.g., B19)", "Adenovirus", "Herpes simplex virus", "Hepatitis B virus", "A", "Parvoviridae are unique among clinically relevant DNA viruses in having a single-stranded genome.", "HARD", "Textbook", "Viral genomes"),
    q("Which DNA virus replicates predominantly in the cytoplasm rather than the nucleus?", "Poxvirus (e.g., Smallpox, Molluscum contagiosum)", "Papillomavirus", "CMV", "Epstein-Barr Virus", "A", "Poxviruses are very large and carry their own DNA-dependent RNA polymerase to complete the cycle in the cytoplasm.", "HARD", "Textbook", "Viral replication"),
    q("A child presents with a 'slapped cheek' rash and lacy eruption on the trunk. This 'Fifth disease' (Erythema infectiosum) is caused by:", "Parvovirus B19", "Human Herpesvirus 6 (HHV-6)", "Varicella-Zoster Virus (VZV)", "Measles virus", "A", "Parvovirus B19 also infects erythroid precursors, causing transient aplastic crisis in sickle cell patients.", "EASY", "Textbook", "Clinical virology"),
    q("Which virus establishes lifelong latency in sensory nerve ganglia (like the trigeminal ganglion)?", "Herpes Simplex Virus Type 1 (HSV-1)", "Cytomegalovirus (CMV)", "Epstein-Barr Virus (EBV)", "Human Papillomavirus (HPV)", "A", "Alphaherpesviruses (HSV-1, HSV-2, VZV) become latent in sensory neuraxis.", "EASY", "Textbook", "Herpesviruses"),
    q("Varicella-Zoster Virus (VZV) primary infection causes chickenpox. Reactivation of the latent virus causes:", "Herpes zoster (Shingles)", "Infectious mononucleosis", "Erythema multiforme", "Kaposi sarcoma", "A", "Shingles presents as a painful, unilateral vesicular rash in a dermatomal distribution.", "EASY", "Textbook", "Herpesviruses"),
    q("The atypical, reactive lymphocytes seen on a blood smear in infectious mononucleosis (caused by EBV) are actually:", "CD8+ Cytotoxic T cells reacting to infected cells", "The EBV-infected B cells themselves", "Natural Killer cells", "Activated neutrophils", "A", "EBV infects B cells (via CD21), but the marked cellular proliferation is a massive CD8+ T-cell response.", "HARD", "Textbook", "EBV"),
    q("Human Papillomavirus (HPV) types 16 and 18 are strongly associated with the development of:", "Cervical carcinoma and oropharyngeal cancer", "Hepatocellular carcinoma", "Burkitt lymphoma", "Kaposi sarcoma", "A", "HPV E6 inhibits p53 and E7 inhibits Rb, leading to unchecked cellular proliferation.", "EASY", "Textbook", "Oncogenic viruses"),
    q("The 'owl's eye' intranuclear inclusion body represents a classic histological finding in infection by:", "Cytomegalovirus (CMV)", "Rabies virus", "Herpes Simplex Virus", "Papillomavirus", "A", "CMV causes massively enlarged cells (cytomegaly) with characteristic large basophilic inclusions.", "MEDIUM", "Textbook", "CMV"),
    q("Which virus causes Kaposi Sarcoma, an angioproliferative tumor common in AIDS patients?", "Human Herpesvirus 8 (HHV-8)", "Human T-lymphotropic virus (HTLV-1)", "Hepatitis C Virus", "Cytomegalovirus (CMV)", "A", "HHV-8 (KSHV) also causes primary effusion lymphoma.", "MEDIUM", "Textbook", "Herpesviruses"),
    q("Hepatitis B virus (HBV) replicates via a unique mechanism for a DNA virus that involves:", "Reverse transcription of an RNA intermediate", "Integration into the host genome to produce progeny", "Rolling circle DNA replication entirely by host enzymes", "Assembly within the rough endoplasmic reticulum lumen", "A", "HBV packages a reverse transcriptase to convert a pregenomic mRNA back into its relaxed-circular DNA.", "HARD", "Textbook", "HBV replication")
  ]],
  ["RNA Viruses", [
    q("All of the following RNA viruses replicate in the cytoplasm EXCEPT:", "Orthomyxovirus (Influenza) and Retroviruses (HIV)", "Picornaviruses (Polio)", "Paramyxoviruses (Measles)", "Flaviviruses (HCV)", "A", "Influenza viruses and Retroviruses must enter the host nucleus during their replication cycle.", "HARD", "Textbook", "Viral replication"),
    q("Which family of RNA viruses has a segmented genome?", "Orthomyxoviridae (e.g., Influenza) and Reoviridae (e.g., Rotavirus)", "Paramyxoviridae (e.g., Mumps)", "Coronaviridae (e.g., SARS-CoV-2)", "Picornaviridae (e.g., Rhinovirus)", "A", "Segmented genomes (BOAR: Bunyavirus, Orthomyxovirus, Arenavirus, Reovirus) allow for genetic reassortment.", "HARD", "Textbook", "Viral genomes"),
    q("The most common viral cause of severe, dehydrating acute gastroenteritis in infants and young children worldwide (prior to vaccination) is:", "Rotavirus", "Norovirus", "Adenovirus", "Astrovirus", "A", "Rotavirus (a Reovirus) causes villous atrophy and produces an enterotoxin (NSP4).", "MEDIUM", "Textbook", "Clinical virology"),
    q("Rabies virus typically features which pathognomonic finding on brain biopsy?", "Negri bodies (eosinophilic cytoplasmic inclusions)", "Cowdry A bodies", "Guarnieri bodies", "Koilocytes", "A", "Negri bodies are classical findings, typically found in Purkinje cells of the cerebellum or pyramidal cells.", "MEDIUM", "Textbook", "Rabies"),
    q("The leading cause of lower respiratory tract disease (bronchiolitis and pneumonia) in infants worldwide is:", "Respiratory Syncytial Virus (RSV)", "Parainfluenza virus", "Rhinovirus", "Influenza A", "A", "RSV (a paramyxovirus) is highly contagious and uniquely lacks hemagglutinin and neuraminidase.", "EASY", "Textbook", "Clinical virology"),
    q("Koplik spots (small white spots with blue-white centers on buccal mucosa) are a pathognomonic early sign of:", "Measles (Rubeola)", "Mumps", "Rubella (German measles)", "Coxsackievirus infection", "A", "Measles initially presents with Cough, Coryza, Conjunctivitis, and Koplik spots.", "EASY", "Textbook", "Paramyxoviruses"),
    q("Which mosquito-borne RNA virus is a flavivirus that causes a hemorrhagic fever associated with severe \"break-bone\" joint and muscle pain?", "Dengue virus", "Yellow fever virus", "Chikungunya virus", "Zika virus", "A", "Dengue classically presents with high fever, rash, and severe myalgias ('break-bone fever').", "MEDIUM", "Textbook", "Arboviruses"),
    q("The HIV targets CD4 T-cells but requires a co-receptor for viral entry. The primary co-receptors are:", "CCR5 or CXCR4", "CD8 or CD21", "CD28 or CTLA-4", "ICAM-1 or LFA-1", "A", "CCR5 is typically the early macrophage-tropic co-receptor, and HIV later shifts to CXCR4.", "MEDIUM", "Textbook", "HIV"),
    q("Which retroviral enzyme integrates the reverse-transcribed viral DNA into the host cell chromosome?", "Integrase", "Protease", "Reverse Transcriptase", "RNase H", "A", "Integrase inserts the proviral DNA into the host, establishing lifelong infection.", "EASY", "Textbook", "HIV"),
    q("The characteristic 'seal-bark' cough and inspiratory stridor characterizing Croup (laryngotracheobronchitis) is most often caused by:", "Parainfluenza viruses", "Rhinovirus", "Respiratory syncytial virus", "Influenza B", "A", "Parainfluenza virus (Type 1 or 2) is the classical cause of pediatric croup.", "MEDIUM", "Textbook", "Paramyxoviruses")
  ]],
  ["Mycology and Parasitology", [
    q("Which fungal organism is dimorphic, presenting as a mold in the cold (environment) and a yeast in the heat (tissues)?", "Histoplasma capsulatum", "Candida albicans", "Cryptococcus neoformans", "Aspergillus fumigatus", "A", "'Mold in the cold, Yeast in the beast' applies to Histoplasma, Blastomyces, Coccidioides, etc.", "MEDIUM", "Textbook", "Fungal properties"),
    q("A heavily encapsulated yeast identified using an India ink preparation of CSF, typically causing meningitis in AIDS patients, is:", "Cryptococcus neoformans", "Candida albicans", "Pneumocystis jirovecii", "Sporothrix schenckii", "A", "C. neoformans is found in pigeon droppings and has a very thick polysaccharide capsule.", "MEDIUM", "Textbook", "Clinical mycology"),
    q("Rose gardener's disease, presenting as local pustules extending along lymphatic drainage tracks, is caused by:", "Sporothrix schenckii", "Aspergillus fumigatus", "Trichophyton rubrum", "Coccidioides immitis", "A", "Sporothrix is a subcutaneous dimorphic fungus introduced by thorny plant trauma.", "EASY", "Textbook", "Clinical mycology"),
    q("Which ubiquitous mold creates a 'fungus ball' (aspergilloma) inside pre-existing lung cavities (e.g., from old TB)?", "Aspergillus fumigatus", "Histoplasma capsulatum", "Mucor species", "Pneumocystis jirovecii", "A", "Aspergillus fungi branch at acute (45 degree) angles and are highly prevalent in the environment.", "EASY", "Textbook", "Clinical mycology"),
    q("The most severe form of malaria, causing cerebral malaria and exhibiting 'banana-shaped' gametocytes on a blood smear, is caused by:", "Plasmodium falciparum", "Plasmodium vivax", "Plasmodium ovale", "Plasmodium malariae", "A", "P. falciparum is the most deadly and does not have a dormant liver phase (hypnozoite).", "EASY", "Textbook", "Parasitology"),
    q("Which protozoan causes a sexually transmitted infection leading to a frothy, foul-smelling, greenish vaginal discharge and 'strawberry cervix'?", "Trichomonas vaginalis", "Gardnerella vaginalis", "Toxoplasma gondii", "Giardia lamblia", "A", "T. vaginalis is a flagellated, motile trophozoite without a cyst stage.", "MEDIUM", "Textbook", "Parasitology"),
    q("Chagas disease (American trypanosomiasis), which causes megacolon, megaesophagus, and cardiomyopathy, is caused by:", "Trypanosoma cruzi", "Trypanosoma brucei", "Leishmania donovani", "Entamoeba histolytica", "A", "T. cruzi is transmitted by the reduviid ('kissing') bug in the Americas.", "EASY", "Textbook", "Parasitology"),
    q("Infection with which helminth (obtained by ingesting undercooked pork/bear meat) causes severe muscle pain and periorbital edema as larvae encyst in striated muscle?", "Trichinella spiralis", "Taenia solium", "Ascaris lumbricoides", "Enterobius vermicularis", "A", "Trichinosis classically presents with intense myalgia, fever, and extreme eosinophilia.", "HARD", "Textbook", "Parasitology"),
    q("The 'Scotch tape test' is used to identify the characteristic eggs of which common intestinal nematode that causes intense perianal pruritus in children?", "Enterobius vermicularis (Pinworm)", "Ascaris lumbricoides", "Trichuris trichiura", "Necator americanus", "A", "Pinworms emerge at night to lay eggs on the perianal folds.", "EASY", "Textbook", "Parasitology"),
    q("Hydatid cyst disease in the liver, which can cause fatal anaphylaxis if the cysts rupture, is caused by the dog tapeworm:", "Echinococcus granulosus", "Taenia saginata", "Diphyllobothrium latum", "Schistosoma mansoni", "A", "Humans are accidental intermediate hosts upon ingestion of eggs from canine feces.", "MEDIUM", "Textbook", "Parasitology")
  ]]
];

writeSubject("Microbiology", chapters, "microbiology.json");
