const { q, writeSubject } = require('./qgen_helper');

const chapters = [
  ["Cell Injury and Adaptation", [
    q("Hyperplasia is defined as an increase in the:", "Number of cells in an organ or tissue", "Size of individual cells", "Number of abnormal cells", "Conversion of one adult cell type to another", "A", "Hyperplasia refers to an increased number of cells (e.g., hormonal hyperplasia in pregnancy).", "EASY", "Textbook", "Cellular adaptations"),
    q("Barrett's esophagus is an example of which type of cellular adaptation?", "Metaplasia", "Dysplasia", "Hypertrophy", "Atrophy", "A", "Squamous epithelium of the esophagus changes to columnar epithelium due to chronic acid reflux.", "EASY", "Textbook", "Metaplasia"),
    q("Coagulative necrosis is classically seen in all ischemic infarctions EXCEPT in the:", "Brain", "Heart", "Kidney", "Spleen", "A", "Ischemic injury in the brain leads to liquefactive necrosis, not coagulative.", "MEDIUM", "Textbook", "Necrosis"),
    q("Caseous necrosis is most characteristic of which infectious disease?", "Tuberculosis", "Syphilis", "Staphylococcal abscess", "Amebiasis", "A", "Caseous ('cheese-like') necrosis is the hallmark of tuberculous granulomas.", "EASY", "Textbook", "Necrosis"),
    q("The earliest ultrastructural change visible in reversible cell injury is:", "Mitochondrial swelling", "Nuclear pyknosis", "Phospholipid myelin figures", "Plasma membrane blebbing", "A", "Mitochondrial swelling and ER dilation (cellular swelling) occur early due to ATP depletion.", "HARD", "Textbook", "Cell injury mechanisms"),
    q("Which of the following describes nuclear fragmentation into small dust-like particles during cell death?", "Karyorrhexis", "Pyknosis", "Karyolysis", "Apoptosis", "A", "Karyorrhexis is the destructive fragmentation of the nucleus of a dying cell.", "MEDIUM", "Textbook", "Necrosis morphology"),
    q("Fat necrosis is most commonly associated with severe inflammatory disease of the:", "Pancreas", "Liver", "Breast", "Kidney", "A", "Pancreatic lipases release fatty acids which combine with calcium (saponification).", "MEDIUM", "Textbook", "Fat necrosis"),
    q("Lipofuscin pigment is best described as a sign of:", "Free radical injury and 'wear and tear'", "Iron overload", "Melanin overproduction", "Bilirubin accumulation", "A", "Lipofuscin represents complexes of lipid and protein from free-radical catalyzed peroxidation.", "MEDIUM", "Textbook", "Intracellular accumulations"),
    q("Dystrophic calcification occurs primarily in:", "Dead or degenerating tissues with normal serum calcium", "Normal tissues with hypercalcemia", "The kidneys due to hyperparathyroidism", "The lungs due to sarcoidosis", "A", "Dystrophic calcification occurs locally in abnormal tissue, independently of absolute calcium levels.", "EASY", "Textbook", "Calcification"),
    q("Which of the following is an anti-apoptotic gene?", "Bcl-2", "Bax", "Bak", "p53", "A", "Bcl-2 is the prototype anti-apoptotic protein that prevents cytochrome c release.", "MEDIUM", "Textbook", "Apoptosis pathways")
  ]],
  ["Inflammation", [
    q("The first vascular response to an acute injury is:", "Transient vasoconstriction", "Vasodilation", "Increased vascular permeability", "Stasis of blood flow", "A", "Brief neurogenic vasoconstriction is immediately followed by characteristic vasodilation.", "MEDIUM", "Textbook", "Vascular changes"),
    q("The predominant inflammatory cell in the first 6-24 hours of acute inflammation is the:", "Neutrophil", "Macrophage", "Lymphocyte", "Eosinophil", "A", "Neutrophils are the first responders, later replaced by monocytes/macrophages.", "EASY", "Textbook", "Cellular events"),
    q("Which mediator is primarily responsible for the pain of acute inflammation?", "Bradykinin & Prostaglandins", "Histamine & Serotonin", "Leukotriene B4", "Complement C3a & C5a", "A", "Bradykinin and PGE2 sensitive nerve endings to cause pain.", "MEDIUM", "Textbook", "Chemical mediators"),
    q("Opsonization of bacteria to enhance phagocytosis is primarily mediated by:", "C3b and IgG", "C5a and LTB4", "Histamine and Bradykinin", "IL-1 and TNF-alpha", "A", "C3b and IgG act as powerful opsonins.", "MEDIUM", "Textbook", "Phagocytosis"),
    q("Which selectin is expressed on endothelial cells and mediates early leukocyte rolling?", "E-selectin", "L-selectin", "Integrin MAC-1", "ICAM-1", "A", "Endothelial (E) and Platelet (P) selectins mediate leukocyte rolling.", "EASY", "Textbook", "Leukocyte adhesion"),
    q("Firm adhesion of leukocytes to the endothelium is mediated primarily by:", "Integrins binding to ICAM-1", "Selectins binding to Sialyl-Lewis X", "PECAM-1 (CD31)", "Chemokines", "A", "Integrins (LFA-1, MAC-1) strongly bind ICAMs during firm adhesion.", "MEDIUM", "Textbook", "Leukocyte adhesion"),
    q("The hallmark histological feature of granulomatous inflammation is the presence of:", "Epithelioid macrophages", "Abundant neutrophils", "Extensive fibrosis", "Liquefactive necrosis", "A", "Aggregates of activated macrophages resembling epithelial cells are required for the diagnosis of a granuloma.", "EASY", "Textbook", "Chronic inflammation"),
    q("Which cytokine is crucial for maintaining granuloma formation in tuberculosis?", "Interferon-gamma (IFN-y)", "Interleukin-8 (IL-8)", "Leukotriene B4", "Histamine", "A", "Th1 cells secrete IFN-y to continuously activate macrophages.", "HARD", "Textbook", "Granuloma"),
    q("A scar formed from excessive accumulation of collagen that grows beyond the boundaries of the original wound is a:", "Keloid", "Hypertrophic scar", "Granulation tissue", "Contracture", "A", "Unlike hypertrophic scars, keloids do not regress and expand beyond the injury site.", "EASY", "Textbook", "Tissue repair"),
    q("Type I collagen is replacing Type III collagen during which phase of wound healing?", "Remodeling", "Inflammation", "Proliferation", "Hemostasis", "A", "Matrix metalloproteinases degrade Type III to be replaced by stronger Type I during remodeling.", "MEDIUM", "Textbook", "Wound healing")
  ]],
  ["Hemodynamic Disorders", [
    q("Anasarca is best defined as:", "Severe generalized edema", "Accumulation of fluid in the peritoneal cavity", "A localized collection of blood outside blood vessels", "Fluid transudation in the pleural space", "A", "Anasarca is generalized massive edema of subcutaneous tissues.", "EASY", "Textbook", "Edema"),
    q("Which of the following promotes the formation of a transudate rather than an exudate?", "Decreased plasma oncotic pressure", "Increased capillary permeability", "Inflammation", "Endothelial injury", "A", "Transudates occur due to hydrostatic or oncotic pressure imbalances without increased permeability.", "EASY", "Textbook", "Edema"),
    q("Heart failure cells in the lungs are:", "Hemosiderin-laden macrophages", "Hypertrophied type II pneumocytes", "Degenerating cardiac myocytes", "Neutrophils containing bacteria", "A", "Chronic passive congestion of the lungs leads to RBC extravasation, phagocytosed by macrophages.", "MEDIUM", "Textbook", "Hyperemia and Congestion"),
    q("The lines of Zahn are characteristic finding in:", "Arterial or cardiac thrombi", "Postmortem clots", "Venous thrombi in stagnant flow", "Disseminated intravascular coagulation", "A", "Alternating pale and dark layers demonstrate thrombosis occurring in flowing blood.", "MEDIUM", "Textbook", "Thrombosis"),
    q("Virchow's triad includes all of the following EXCEPT:", "Hypercholesterolemia", "Endothelial injury", "Stasis of blood flow", "Hypercoagulability", "A", "Endothelial injury, abnormal blood flow (stasis), and hypercoagulability make up the triad.", "EASY", "Textbook", "Thrombosis"),
    q("The most common source of pulmonary emboli is:", "Deep veins of the lower extremities", "Atherosclerotic plaques in the aorta", "Right atrial appendage", "Pelvic veins", "A", "More than 95% of pulmonary emboli arise from DVT above the knee.", "EASY", "Textbook", "Embolism"),
    q("Paradoxical emboli characteristically pass through the:", "Patent foramen ovale", "Ductus arteriosus", "Ventricular septal defect", "Aortic valve", "A", "Venous emboli can enter the systemic circulation bypassing the lungs via an ASD/PFO.", "MEDIUM", "Textbook", "Embolism"),
    q("A wedge-shaped, pale (white) infarct is typically seen in the:", "Kidney", "Lungs", "Small intestine", "Liver", "A", "Solid organs with end-arterial circulations (kidney, heart, spleen) develop pale infarcts.", "MEDIUM", "Textbook", "Infarction"),
    q("Red (hemorrhagic) infarcts typically occur in tissues with:", "Dual blood supply (e.g., lungs)", "End-arterial circulation", "High tissue density", "Low metabolic rates", "A", "Lungs and dual-circulation organs suffer red infarcts due to bleeding into the necrotic area.", "EASY", "Textbook", "Infarction"),
    q("The primary pathophysiological mechanism in septic shock is:", "Massive systemic vasodilation and increased vascular permeability", "Decreased myocardial contractility primarily", "Loss of blood volume", "Obstruction to blood flow", "A", "Endotoxins/Cytokines cause systemic vasodilation resulting in profound hypotension.", "MEDIUM", "Textbook", "Shock")
  ]],
  ["Neoplasia", [
    q("A benign tumor of glandular epithelium is called an:", "Adenoma", "Adenocarcinoma", "Papilloma", "Sarcoma", "A", "Adenoma denotes a benign epithelial neoplasm from glands.", "EASY", "Textbook", "Nomenclature"),
    q("Which of the following is the most reliable morphologic criterion distinguishing a malignant tumor from a benign one?", "Metastasis", "Pleomorphism", "Increased mitotic figures", "Necrosis", "A", "Metastasis is the absolute hallmark of malignancy.", "EASY", "Textbook", "Benign vs Malignant"),
    q("Carcinoma in situ is defined as:", "Dysplasia involving the full thickness of the epithelium without breaching the basement membrane", "Invasion of tumor cells into the underlying stroma", "A benign tumor with a high risk of malignant transformation", "Metastasis to regional lymph nodes", "A", "CIS has all cytological features of malignancy but lacks invasion.", "MEDIUM", "Textbook", "Dysplasia"),
    q("The p53 gene product functions primarily to:", "Arrest the cell cycle in G1 to allow for DNA repair", "Stimulate angiogenesis", "Promote progression from G2 to M phase", "Inhibit apoptosis", "A", "p53 'guardian of the genome' halts cell cycle to repair DNA, or triggers apoptosis if unrepairable.", "MEDIUM", "Textbook", "Tumor suppressor genes"),
    q("A classical example of a chemical carcinogen causing hepatocellular carcinoma is:", "Aflatoxin B1", "Asbestos", "Benzene", "Vinyl chloride", "A", "Aflatoxins produced by Aspergillus contaminate grains and peanuts, causing HCC.", "MEDIUM", "Textbook", "Carcinogens"),
    q("Which virus is causally associated with Burkitt lymphoma?", "Epstein-Barr virus (EBV)", "Human papillomavirus (HPV)", "Hepatitis C virus", "Human T-cell leukemia virus type 1 (HTLV-1)", "A", "EBV is strongly associated with endemic Burkitt lymphoma.", "EASY", "Textbook", "Viral carcinogenesis"),
    q("Rb (Retinoblastoma gene) strictly regulates the cell cycle transition from:", "G1 to S phase", "S to G2 phase", "G2 to M phase", "M to G1 phase", "A", "Hypophosphorylated Rb binds and inhibits E2F, blocking G1 to S progression.", "HARD", "Textbook", "Tumor suppressor genes"),
    q("The grading of a cancer is based on:", "The degree of cellular differentiation and mitotic activity", "The size of the primary tumor", "The extent of spread to lymph nodes", "The presence of distant metastases", "A", "Grading is histological (how abnormal the cells look). Staging is clinical/pathological (extent of spread).", "EASY", "Textbook", "Grading and Staging"),
    q("Which tumor marker is most useful for monitoring recurrence of colon cancer?", "Carcinoembryonic antigen (CEA)", "Alpha-fetoprotein (AFP)", "Prostate-specific antigen (PSA)", "CA-125", "A", "CEA is elevated in colorectal carcinoma.", "EASY", "Textbook", "Tumor markers"),
    q("Tumor cells often shift their metabolism to aerobic glycolysis (Warburg effect) to:", "Provide metabolic intermediates for cellular biosynthesis", "Maximize ATP production per glucose molecule", "Increase oxygen consumption", "Prevent lactic acidosis", "A", "The Warburg effect allows tumor cells to use carbon from glucose for rapid biomass synthesis.", "HARD", "Textbook", "Cancer biology")
  ]],
  ["Immunopathology", [
    q("Anaphylaxis is a classic example of which type of hypersensitivity reaction?", "Type I", "Type II", "Type III", "Type IV", "A", "IgE-mediated mast cell degranulation causes Type I hypersensitivity.", "EASY", "Textbook", "Hypersensitivity"),
    q("Goodpasture syndrome represents which type of hypersensitivity?", "Type II", "Type I", "Type III", "Type IV", "A", "Antibodies directed against fixed basement membrane (anti-GBM) is Type II.", "MEDIUM", "Textbook", "Hypersensitivity"),
    q("Serum sickness and systemic lupus erythematosus (SLE) primarily involve which hypersensitivity mechanism?", "Type III", "Type I", "Type II", "Type IV", "A", "Deposition of circulating immune complexes causes Type III hypersensitivity.", "MEDIUM", "Textbook", "Hypersensitivity"),
    q("The tuberculin (PPD) skin test reaction is mediated by:", "Th1 cells and macrophages", "IgE antibodies", "Cytotoxic T cells (CD8+)", "Immune complexes", "A", "It is a classical Delayed-Type Hypersensitivity (Type IV) response.", "EASY", "Textbook", "Hypersensitivity"),
    q("Which autoantibody is highly specific (but not sensitive) for Systemic Lupus Erythematosus (SLE)?", "Anti-dsDNA and Anti-Sm", "Antinuclear antibody (ANA)", "Rheumatoid Factor", "Anti-centromere antibody", "A", "Anti-dsDNA and Anti-Smith are highly specific markers for SLE.", "MEDIUM", "Textbook", "Autoimmune diseases"),
    q("Sjogren syndrome is characterized by the destruction of:", "Lacrimal and salivary glands", "Thyroid gland", "Synovial joints", "Glomerular basement membrane", "A", "Lymphocytic infiltration destroys exocrine glands causing dry eyes and dry mouth.", "EASY", "Textbook", "Autoimmune diseases"),
    q("The primary target of the Human Immunodeficiency Virus (HIV) is the:", "CD4+ T lymphocyte", "CD8+ T lymphocyte", "B lymphocyte", "Neutrophil", "A", "HIV uses the CD4 molecule as its primary receptor to infect helper T cells.", "EASY", "Textbook", "Immunodeficiency"),
    q("A defining opportunistic infection in AIDS that presents as severe pneumonia is caused by:", "Pneumocystis jirovecii", "Streptococcus pneumoniae", "Staphylococcus aureus", "Mycoplasma pneumoniae", "A", "Pneumocystis pneumonia (PCP) is a classic AIDS-defining illness.", "MEDIUM", "Textbook", "HIV/AIDS"),
    q("Which condition is characterized by amyloid deposition composed of AL protein?", "Primary amyloidosis (Multiple Myeloma)", "Secondary amyloidosis (Chronic inflammation)", "Alzheimer disease", "Familial Mediterranean Fever", "A", "AL amyloid consists of immunoglobulin light chains produced by plasma cell dyscrasias.", "HARD", "Textbook", "Amyloidosis"),
    q("Hyperacute transplant rejection is mediated by:", "Preformed host antibodies against donor antigens", "Host CD8+ T cells", "Host macrophages", "Donor T cells attacking host tissues", "A", "Pre-existing antibodies cause immediate thrombosis and graft necrosis.", "MEDIUM", "Textbook", "Transplant rejection")
  ]],
  ["Hematopathology", [
    q("The hallmark of iron deficiency anemia in a peripheral blood smear is:", "Microcytic, hypochromic red blood cells", "Macrocytic, hyperchromic red blood cells", "Normocytic, normochromic red blood cells", "Schistocytes", "A", "Lack of iron impairs hemoglobin synthesis, producing small, pale RBCs.", "EASY", "Textbook", "Anemias"),
    q("Megaloblastic anemia is most commonly caused by a deficiency of:", "Vitamin B12 or Folic acid", "Iron", "Vitamin B6", "Vitamin C", "A", "Impaired DNA synthesis leads to large, immature RBC precursors (megaloblasts).", "EASY", "Textbook", "Anemias"),
    q("The finding of Heinz bodies and bite cells in a peripheral smear is characteristic of:", "G6PD deficiency", "Sickle cell anemia", "Hereditary spherocytosis", "Thalassemia", "A", "Oxidized, denatured hemoglobin forms Heinz bodies, which are 'bitten' out by splenic macrophages.", "MEDIUM", "Textbook", "Hemolytic anemias"),
    q("A substitution of valine for glutamic acid at the 6th position of the beta-globin chain results in:", "Sickle cell disease (HbS)", "Hemoglobin C disease (HbC)", "Beta-thalassemia major", "Hemoglobin Barts", "A", "This point mutation leads to polymerization of deoxygenated HbS.", "EASY", "Textbook", "Hemoglobinopathies"),
    q("Reed-Sternberg cells are the pathognomonic finding in:", "Hodgkin lymphoma", "Non-Hodgkin lymphoma", "Multiple myeloma", "Chronic Myeloid Leukemia", "A", "These are large, binucleated 'owl-eye' cells characteristic of Classic Hodgkin lymphoma.", "EASY", "Textbook", "Lymphomas"),
    q("The Philadelphia chromosome [t(9;22)] forming the BCR-ABL fusion gene is the hallmark of:", "Chronic Myeloid Leukemia (CML)", "Acute Myeloblastic Leukemia (AML)", "Chronic Lymphocytic Leukemia (CLL)", "Acute Lymphoblastic Leukemia (ALL)", "A", "The BCR-ABL fusion protein has constitutive tyrosine kinase activity.", "MEDIUM", "Textbook", "Leukemias"),
    q("Auer rods are cytoplasmic inclusions typically found in the blast cells of:", "Acute Myeloid Leukemia (AML)", "Acute Lymphoblastic Leukemia (ALL)", "Chronic Lymphocytic Leukemia (CLL)", "Hodgkin lymphoma", "A", "Auer rods represent fused lysosomes/granules, highly specific for AML.", "MEDIUM", "Textbook", "Leukemias"),
    q("Bence Jones proteinuria is classically associated with:", "Multiple Myeloma", "Hodgkin lymphoma", "Burkitt lymphoma", "Waldenstrom macroglobulinemia", "A", "Bence Jones proteins are free immunoglobulin light chains excreted in urine.", "EASY", "Textbook", "Plasma cell dyscrasias"),
    q("The characteristic translocation in Burkitt lymphoma is:", "t(8;14) c-myc overexpression", "t(14;18) bcl-2 overexpression", "t(11;14) cyclin D1 overexpression", "t(15;17) PML-RARA", "A", "Translocation of c-myc directly behind the Ig heavy chain promoter drives proliferation.", "HARD", "Textbook", "Lymphomas"),
    q("Which coagulation test is characteristically prolonged in Hemophilia A?", "Activated partial thromboplastin time (aPTT)", "Prothrombin time (PT)", "Bleeding time", "Thrombin time", "A", "Hemophilia A (Factor VIII deficiency) affects the intrinsic pathway, tested by aPTT.", "MEDIUM", "Textbook", "Bleeding disorders")
  ]],
  ["Cardiovascular Pathology", [
    q("The most common cause of right-sided heart failure is:", "Left-sided heart failure", "Cor pulmonale", "Tricuspid valve stenosis", "Pulmonary embolism", "A", "Left heart failure increases pulmonary venous pressure, leading to right heart failure.", "EASY", "Textbook", "Heart failure"),
    q("Stable angina pectoris is typically caused by:", "Atherosclerotic plaque obstructing >70% of a coronary artery", "Plaque rupture with complete thrombus occlusion", "Coronary artery vasospasm", "Aortic stenosis", "A", "Fixed strictures cannot increase blood flow during exertion, causing reversible ischemia.", "MEDIUM", "Textbook", "Ischemic heart disease"),
    q("The most specific and sensitive serum biomarker for acute myocardial infarction is:", "Cardiac Troponin I or T", "Creatine kinase-MB (CK-MB)", "Myoglobin", "Lactate dehydrogenase", "A", "Troponins are highly sensitive and specific for myocardial damage.", "EASY", "Textbook", "Myocardial infarction"),
    q("What is the most common complication and cause of death in the first few hours following an acute myocardial infarction?", "Cardiac arrhythmias (e.g., ventricular fibrillation)", "Cardiogenic shock", "Ventricular free wall rupture", "Papillary muscle rupture", "A", "Electrical instability surrounding the ischemic area leads to fatal arrhythmias.", "MEDIUM", "Textbook", "Myocardial infarction"),
    q("Fibrinous pericarditis (a 'bread and butter' appearance) is a classic finding in:", "Acute rheumatic fever and uremia", "Viral pericarditis", "Constrictive pericarditis", "Tuberculous pericarditis", "A", "Fibrin-rich exudate causes a shaggy surface on the pericardium.", "HARD", "Textbook", "Pericarditis"),
    q("Rheumatic fever is a consequence of pharyngeal infection by which organism?", "Group A beta-hemolytic Streptococcus", "Staphylococcus aureus", "Streptococcus pneumoniae", "Viridans group streptococci", "A", "Antibodies against M-protein cross-react with cardiac tissue (molecular mimicry).", "EASY", "Textbook", "Rheumatic heart disease"),
    q("The classic histological finding in acute rheumatic carditis is the:", "Aschoff body", "Nutmeg liver", "Vegetations on the aortic valve", "Concentric left ventricular hypertrophy", "A", "Aschoff bodies are granulomatous lesions containing Anitschkow cells (caterpillar cells).", "MEDIUM", "Textbook", "Rheumatic heart disease"),
    q("The most common cause of infective endocarditis in intravenous drug abusers is:", "Staphylococcus aureus involving the tricuspid valve", "Viridans streptococci involving the mitral valve", "Enterococcus involving the aortic valve", "Candida albicans involving the pulmonary valve", "A", "S. aureus aggressively attacks the first valve it reaches from systemic venous entry.", "MEDIUM", "Textbook", "Infective endocarditis"),
    q("Hypertrophic cardiomyopathy (HCM) is most often caused by mutations in genes encoding:", "Sarcomeric proteins (e.g., beta-myosin heavy chain)", "Cytoskeletal proteins (e.g., dystrophin)", "Desmosomal proteins", "Ion channels (e.g., K+ channels)", "A", "HCM is an autosomal dominant disorder of sarcomere proteins.", "HARD", "Textbook", "Cardiomyopathies"),
    q("A 'tear' in the aortic intima with blood tracking into the media constitutes:", "Aortic dissection", "True abdominal aortic aneurysm", "Syphilitic aortitis", "Mycotic aneurysm", "A", "This dissection creates a false lumen, often presenting with sudden 'tearing' chest pain.", "EASY", "Textbook", "Vascular pathology")
  ]],
  ["Respiratory Pathology", [
    q("Which of the following is characteristic of Centriacinar emphysema?", "Strong association with smoking and involvement of the upper lobes", "Association with alpha-1 antitrypsin deficiency", "Involvement of the lower lobes predominantly", "Fibrosis of the alveolar walls", "A", "Smoke accumulates in the upper lobes, destroying the respiratory bronchioles.", "MEDIUM", "Textbook", "COPD"),
    q("A 65-year-old male with a long smoking history presents with a chronic productive cough for 3 months in 2 consecutive years. The most likely diagnosis is:", "Chronic bronchitis", "Emphysema", "Bronchiectasis", "Asthma", "A", "The clinical definition of chronic bronchitis requires this specific history.", "EASY", "Textbook", "COPD"),
    q("Curschmann spirals and Charcot-Leyden crystals in sputum are pathognomonic for:", "Bronchial asthma", "Chronic bronchitis", "Lobar pneumonia", "Bronchiectasis", "A", "Curschmann spirals are mucus plugs; Charcot-Leyden crystals are from breakdown of eosinophils.", "MEDIUM", "Textbook", "Asthma"),
    q("Permanent abnormal dilation of bronchi and bronchioles caused by destruction of muscle and elastic tissue is termed:", "Bronchiectasis", "Emphysema", "Asthma", "Atelectasis", "A", "Usually secondary to severe or chronic necrotizing infections.", "EASY", "Textbook", "Obstructive lung disease"),
    q("Pneumoconiosis caused by inhalation of silica dust typically results in:", "Nodular fibrosis with 'eggshell' calcification in hilar lymph nodes", "Diffused interstitial fibrosis with mesothelioma", "Noncaseating granulomas resembling sarcoidosis", "Lower lobe predominant fibrosis", "A", "Silicosis profoundly increases susceptibility to tuberculosis.", "HARD", "Textbook", "Restrictive lung disease"),
    q("Bilateral hilar lymphadenopathy and non-caseating granulomas are the hallmark of:", "Sarcoidosis", "Tuberculosis", "Histoplasmosis", "Silicosis", "A", "Sarcoidosis is a systemic disease of unknown etiology characterized by these findings.", "MEDIUM", "Textbook", "Restrictive lung disease"),
    q("The most common type of primary lung cancer is:", "Adenocarcinoma", "Squamous cell carcinoma", "Small cell carcinoma", "Large cell carcinoma", "A", "Adenocarcinoma is the most common lung cancer overall, particularly in women and non-smokers.", "EASY", "Textbook", "Lung tumors"),
    q("Which lung cancer is centrally located, strongly associated with smoking, and may produce parathyroid hormone-related peptide (PTHrP)?", "Squamous cell carcinoma", "Small cell carcinoma", "Adenocarcinoma", "Carcinoid tumor", "A", "Squamous cell carcinoma leads to hypercalcemia through PTHrP production.", "MEDIUM", "Textbook", "Lung tumors"),
    q("Small cell carcinoma of the lung typically presents with:", "Early early metastasis and paraneoplastic syndromes (e.g., ADH, ACTH)", "A large peripheral mass with cavitation", "A favorable response to surgical resection", "Apical location causing Horner syndrome", "A", "It is an aggressive neuroendocrine tumor rarely treated with surgery.", "MEDIUM", "Textbook", "Lung tumors"),
    q("The classic four stages of lobar pneumonia (pneumococcal) are sequentially:", "Congestion, Red Hepatization, Gray Hepatization, Resolution", "Exudation, Fibrosis, Cavitation, Resolution", "Congestion, Liquefaction, Granulation, Resolution", "Hemolysis, Suppuration, Caseation, Scarring", "A", "This defines the classic lobar pattern of Streptococcus pneumoniae.", "HARD", "Textbook", "Pulmonary infections")
  ]],
  ["GI Pathology", [
    q("The most common site for a peptic ulcer is the:", "First part of the duodenum", "Lesser curvature of the stomach", "Cardia of the stomach", "Esophagus", "A", "Duodenal ulcers are the most common type and are highly associated with H. pylori.", "EASY", "Textbook", "Peptic ulcer disease"),
    q("A defining histological feature of Celiac disease (Gluten-sensitive enteropathy) is:", "Villous atrophy and intraepithelial lymphocytosis", "Crypt branching and distortion", "Non-caseating granulomas", "Pseudomembranes", "A", "Immune reaction to gliadin results in destruction of the absorptive villi.", "MEDIUM", "Textbook", "Malabsorption"),
    q("Crohn's disease classically involves:", "Transmural inflammation and skip lesions", "Mucosal inflammation beginning in the rectum", "Continuous involvement of the left colon", "Crypt abscesses solely", "A", "Transmural inflammation leads to strictures, fistulas, and a 'cobblestone' mucosa.", "EASY", "Textbook", "Inflammatory bowel disease"),
    q("Ulcerative Colitis always involves the:", "Rectum", "Terminal ileum", "Stomach", "Esophagus", "A", "UC starts in the rectum and spreads continuously proximally, limited to the mucosa/submucosa.", "EASY", "Textbook", "Inflammatory bowel disease"),
    q("A key complication of chronic Ulcerative Colitis is a high risk for developing:", "Colorectal adenocarcinoma", "Gastric lymphoma", "Fistulas to other organs", "Malabsorption syndrome", "A", "Long-standing UC has a significantly increased risk of dysplasia and colon cancer.", "MEDIUM", "Textbook", "Inflammatory bowel disease"),
    q("Hirschsprung disease (Congenital aganglionic megacolon) is caused by a failure of:", "Neural crest cells to migrate into the distal bowel", "Vascular supply to the colon", "Rotation of the midgut", "Smooth muscle development", "A", "Absence of Meissner's and Auerbach's plexuses causes a functional obstruction.", "MEDIUM", "Textbook", "Congenital anomalies"),
    q("The most common precursor lesion to colorectal cancer is the:", "Adenomatous polyp", "Hyperplastic polyp", "Inflammatory polyp", "Hamartomatous polyp", "A", "Most colorectal carcinomas arise from adenomas via the adenoma-carcinoma sequence.", "EASY", "Textbook", "Colorectal polyps"),
    q("Familial Adenomatous Polyposis (FAP) is caused by a mutation in the:", "APC tumor suppressor gene", "p53 gene", "KRAS oncogene", "MLH1 mismatch repair gene", "A", "FAP patients develop hundreds of polyps; malignant transformation is 100%.", "MEDIUM", "Textbook", "Polyposis syndromes"),
    q("A characteristic finding in Acute Appendicitis is:", "Neutrophilic infiltration of the muscularis propria", "Vascular congestion only", "Lymphoid hyperplasia without crypt injury", "Fibrotic stricture", "A", "Diagnosis requires transmural neutrophilic inflammation.", "MEDIUM", "Textbook", "Appendicitis"),
    q("Zollinger-Ellison syndrome is caused by a Gastrin-secreting tumor, most often located in the:", "Pancreas or duodenum", "Stomach", "Liver", "Colon", "A", "Gastrinomas cause massive acid hypersecretion leading to refractory peptic ulcers.", "HARD", "Textbook", "Endocrine tumors of GI")
  ]],
  ["Renal Pathology", [
    q("The classic presentation of Nephrotic Syndrome includes all EXCEPT:", "Hematuria", "Massive proteinuria (>3.5g/day)", "Hypoalbuminemia", "Generalized edema", "A", "Hematuria is characteristic of Nephritic syndrome, not Nephrotic syndrome.", "EASY", "Textbook", "Glomerular diseases"),
    q("Red blood cell casts in the urine are highly indicative of:", "Glomerulonephritis", "Acute tubular necrosis", "Pyelonephritis", "Nephrolithiasis", "A", "RBC casts mean the RBCs were molded in the renal tubules, a sign of glomerular bleeding.", "MEDIUM", "Textbook", "Urinalysis"),
    q("The most common cause of Nephrotic syndrome in children is:", "Minimal Change Disease", "Focal Segmental Glomerulosclerosis", "Membranous Nephropathy", "Post-streptococcal Glomerulonephritis", "A", "MCD responds well to steroids and shows only effacement of podocyte foot processes on EM.", "EASY", "Textbook", "Glomerular diseases"),
    q("A subepithelial 'lumpy-bumpy' deposit pattern on electron microscopy is typical for:", "Post-infectious (post-streptococcal) glomerulonephritis", "Membranous nephropathy", "IgA nephropathy", "Goodpasture syndrome", "A", "Caused by subepithelial immune complex deposition 2-4 weeks after a strep infection.", "HARD", "Textbook", "Glomerulonephritis"),
    q("Kimmelstiel-Wilson nodules in the glomerulus are virtually pathognomonic for:", "Diabetic nephropathy", "Lupus nephritis", "Amyloidosis", "IgA nephropathy", "A", "These nodular glomerulosclerotic lesions are classic for diabetic kidney disease.", "MEDIUM", "Textbook", "Renal pathology"),
    q("Acute Tubular Necrosis (ATN) is most commonly caused by:", "Ischemia or nephrotoxins", "Autoimmune glomerular injury", "Infection ascending from the bladder", "Obstruction of the ureters", "A", "ATN is the most common cause of intrinsic acute kidney injury.", "EASY", "Textbook", "Tubular diseases"),
    q("The presence of 'muddy brown' granular casts in the urine is highly suggestive of:", "Acute Tubular Necrosis", "Acute Interstitial Nephritis", "Chronic Pyelonephritis", "Glomerulonephritis", "A", "The sloughing of necrotic tubular epithelial cells forms these casts.", "MEDIUM", "Textbook", "Urinalysis"),
    q("White blood cell casts in the urine are a hallmark of:", "Acute Pyelonephritis", "Acute Cystitis", "Glomerulonephritis", "Nephrolithiasis", "A", "WBC casts indicate inflammation in the kidney itself, differentiating pyelonephritis from lower UTI.", "MEDIUM", "Textbook", "Infectious renal disease"),
    q("The most common type of renal stone is composed of:", "Calcium oxalate", "Uric acid", "Struvite (Magnesium ammonium phosphate)", "Cystine", "A", "Calcium stones (mostly oxalate) account for ~80% of kidney stones.", "EASY", "Textbook", "Nephrolithiasis"),
    q("Clear cell Renal Cell Carcinoma is often associated with the loss of which tumor suppressor gene?", "VHL (Von Hippel-Lindau)", "WT1 (Wilms tumor 1)", "p53", "APC", "A", "VHL mutation leads to increased HIF-1 expression and highly vascular tumors.", "HARD", "Textbook", "Renal tumors")
  ]],
  ["Hepatobiliary Pathology", [
    q("Which hepatitis virus is a DNA virus?", "Hepatitis B", "Hepatitis A", "Hepatitis C", "Hepatitis E", "A", "HBV is a partially double-stranded DNA hepadnavirus. The others are RNA viruses.", "EASY", "Textbook", "Viral hepatitis"),
    q("The hallmark histological sign of severe acute viral hepatitis is:", "Ballooning degeneration and apoptosis (Councilman bodies)", "Steatosis (fatty change)", "Bridging fibrosis", "Mallory-Denk bodies", "A", "Councilman bodies are intensely eosinophilic, apoptotic hepatocytes.", "MEDIUM", "Textbook", "Liver pathology"),
    q("Liver cirrhosis is characterized by:", "Bridging fibrous septa and regenerative hepatocyte nodules", "Massive hepatic necrosis without fibrosis", "Fatty infiltration without inflammation", "Granulomatous inflammation", "A", "Fibrosis and disrupted architecture defined by regenerative nodules equal cirrhosis.", "EASY", "Textbook", "Cirrhosis"),
    q("Mallory-Denk bodies (Mallory hyaline) are characteristic, though not pathognomonic, of:", "Alcoholic steatohepatitis", "Viral hepatitis A", "Hemochromatosis", "Primary biliary cholangitis", "A", "These eosinophilic cytoplasmic inclusions consist of tangled intermediate cytokeratin filaments.", "MEDIUM", "Textbook", "Alcoholic liver disease"),
    q("A key mechanism of liver injury in hemochromatosis is:", "Iron-catalyzed free radical damage (Fenton reaction)", "Autoimmune destruction of hepatocytes", "Copper accumulation in lysosomes", "Alpha-1 antitrypsin misfolding", "A", "Excess iron generates reactive oxygen species leading to lipid peroxidation and fibrosis.", "MEDIUM", "Textbook", "Metabolic liver disease"),
    q("Primary Biliary Cholangitis (PBC) is strongly associated with which autoantibody?", "Antimitochondrial antibody (AMA)", "Smooth muscle antibody (SMA)", "Antinuclear antibody (ANA)", "Anti-LKM1 antibody", "A", "AMA is present in >90% of patients with PBC, attacking intrahepatic bile ducts.", "HARD", "Textbook", "Biliary disease"),
    q("Primary Sclerosing Cholangitis (PSC) is strongly associated with which other disease?", "Ulcerative Colitis", "Crohn's Disease", "Rheumatoid Arthritis", "Sjogren Syndrome", "A", "There is a strong clinical link between PSC and Ulcerative Colitis.", "MEDIUM", "Textbook", "Biliary disease"),
    q("Which primary liver tumor is most common in patients with underlying cirrhosis and chronic HBV/HCV?", "Hepatocellular carcinoma (HCC)", "Cholangiocarcinoma", "Hepatic adenoma", "Fibrolamellar carcinoma", "A", "HCC primarily arises in the setting of chronic liver disease/cirrhosis.", "EASY", "Textbook", "Hepatic tumors"),
    q("A 35-year-old female on oral contraceptives presents with an incidentally found solitary liver mass. It may rupture and bleed. The likely diagnosis is:", "Hepatic adenoma", "Focal nodular hyperplasia", "Hemangioma", "Hepatocellular carcinoma", "A", "Hepatic adenomas are strongly associated with OCP use and carry a risk of rupture.", "MEDIUM", "Textbook", "Hepatic tumors"),
    q("Gallstones composed primarily of cholesterol are most strongly associated with:", "Obesity, female gender, and multiparity ('Female, Fat, Forty, Fertile')", "Chronic hemolysis", "Biliary tract infections", "Alcoholic cirrhosis", "A", "These are classic risk factors for cholesterol stone formation.", "EASY", "Textbook", "Cholelithiasis")
  ]],
  ["Endocrine Pathology", [
    q("The most common cause of hyperthyroidism (thyrotoxicosis) is:", "Graves' disease", "Toxic multinodular goiter", "Toxic adenoma", "De Quervain thyroiditis", "A", "Graves' disease is an autoimmune condition caused by stimulating TSI antibodies.", "EASY", "Textbook", "Thyroid disease"),
    q("Hashimoto thyroiditis is histologically characterized by:", "Extensive lymphocytic infiltrate with germinal centers and Hurthle cells", "Granulomatous inflammation with giant cells", "Papillary projections and Orphan Annie eye nuclei", "Fibrosis extending into surrounding tissues", "A", "The destruction of the thyroid gland is marked by prominent lymphoid aggregates.", "MEDIUM", "Textbook", "Thyroiditis"),
    q("The most common type of thyroid carcinoma is:", "Papillary carcinoma", "Follicular carcinoma", "Medullary carcinoma", "Anaplastic carcinoma", "A", "Papillary carcinoma accounts for about 80% of all thyroid cancers and has an excellent prognosis.", "EASY", "Textbook", "Thyroid tumors"),
    q("Medullary thyroid carcinoma arises from which cell type?", "Parafollicular C cells", "Follicular epithelium", "Lymphocytes", "Parathyroid chief cells", "A", "Medullary carcinomas secrete calcitonin and may present as part of MEN 2 syndromes.", "MEDIUM", "Textbook", "Thyroid tumors"),
    q("Primary hyperparathyroidism is most often caused by a:", "Parathyroid adenoma", "Parathyroid hyperplasia", "Parathyroid carcinoma", "Chronic renal failure", "A", "A solitary benign parathyroid adenoma is responsible for >80% of cases.", "EASY", "Textbook", "Parathyroid disease"),
    q("Cushing syndrome caused specifically by an ACTH-secreting pituitary adenoma is called:", "Cushing disease", "Addison disease", "Nelson syndrome", "Conn syndrome", "A", "Cushing *disease* specifically refers to a pituitary origin for the hypercortisolism.", "MEDIUM", "Textbook", "Adrenal disease"),
    q("Primary chronic adrenocortical insufficiency is known as:", "Addison disease", "Conn syndrome", "Cushing syndrome", "Waterhouse-Friderichsen syndrome", "A", "Addison disease involves autoimmune destruction of the entire adrenal cortex.", "EASY", "Textbook", "Adrenal disease"),
    q("Pheochromocytomas are tumors of the adrenal medulla that secrete:", "Catecholamines (Epinephrine/Norepinephrine)", "Aldosterone", "Cortisol", "Renin", "A", "They cause episodic hypertension, palpitations, and sweating.", "EASY", "Textbook", "Adrenal medulla disorders"),
    q("Type 1 Diabetes Mellitus is primarily caused by:", "Autoimmune destruction of pancreatic beta cells", "Peripheral insulin resistance", "Amyloid deposition in the islets", "Chronic pancreatitis", "A", "Absolute insulin deficiency occurs due to T-cell mediated destruction of beta cells.", "EASY", "Textbook", "Diabetes mellitus"),
    q("Multiple Endocrine Neoplasia type 1 (MEN 1 - Wermer syndrome) involves tumors of the '3 Ps':", "Pituitary, Parathyroid, and Pancreas", "Pheochromocytoma, Parathyroid, and Pituitary", "Pancreas, Pheochromocytoma, and Paraganglioma", "Parathyroid, Pineal, and Pituitary", "A", "These are the classic sites for tumors in the MEN 1 syndrome.", "HARD", "Textbook", "MEN syndromes")
  ]]
];

writeSubject("Pathology", chapters, "pathology.json");
