const { q, writeSubject } = require('./qgen_helper');

const chapters = [
  ["General Forensic Medicine", [
    q("In India, an 'Inquest' into an unnatural or suspicious death is most commonly conducted by:", "A Police Officer (under section 174 CrPC)", "A Magistrate", "A Coroner", "A Doctor", "A", "Police inquest is the most common form in India for suicides, accidents, etc.", "EASY", "Textbook", "Legal Procedures"),
    q("Evidence given by a doctor based on their examination of a patient/body is an example of:", "Oral evidence", "Documentary evidence", "Direct evidence", "Circumstantial evidence", "A", "Oral evidence refers to the testimony given by a witness under oath.", "EASY", "Textbook", "Evidence"),
    q("Which section of the IPC deals with giving false evidence in court (Perjury)?", "Section 191 IPC", "Section 302 IPC", "Section 376 IPC", "Section 320 IPC", "A", "Perjury is defined under Section 191 of the Indian Penal Code.", "MEDIUM", "Textbook", "IPC Sections"),
    q("A 'Dying Declaration' represents a statement made by a person who is:", "Conscious and believes death is imminent regarding the cause of their impending death", "Under oath in a court of law", "Admitted to a hospital for any serious illness", "Making their last will and testament", "A", "It is an exception to the hearsay rule, based on the belief that a dying person will not lie.", "EASY", "Textbook", "Legal Procedures"),
    q("The minimum age of criminal responsibility in India under IPC Section 82 is:", "Under 7 years of age", "Under 12 years of age", "Under 16 years of age", "Under 18 years of age", "A", "Nothing is an offense which is done by a child under seven years of age (Doli incapax).", "EASY", "Textbook", "Criminal Responsibility"),
    q("Which of the following describes the legal doctrine of 'Res Ipsa Loquitur'?", "The thing speaks for itself", "Master is liable for the acts of the servant", "Let the buyer beware", "An act done in good faith", "A", "It is applied in medical negligence cases where the negligence is obvious (e.g., a sponge left inside the abdomen).", "MEDIUM", "Textbook", "Medical Jurisprudence"),
    q("Professional secrecy (confidentially) may legally be broken by a doctor in which of the following scenarios?", "To prevent the spread of a notifiable infectious disease to the public", "To inform a patient's employer about their medical history", "To discuss a fascinating case with friends in public", "At the request of the patient's distant relatives", "A", "Public safety overriding patient confidentiality is a valid exception (privileged communication).", "MEDIUM", "Textbook", "Medical Ethics"),
    q("The legal requirement to obtain informed consent before a surgical procedure is primarily based on the ethical principle of:", "Autonomy", "Beneficence", "Non-maleficence", "Justice", "A", "Autonomy respects the patient's right to control what happens to their own body.", "EASY", "Textbook", "Medical Ethics"),
    q("The Indian Medical Council (Professional Conduct, Etiquette and Ethics) Regulations, defining infamous conduct, were published in:", "2002", "1956", "1860", "1994", "A", "The MCI regulations of 2002 govern the professional conduct of registered medical practitioners.", "HARD", "Textbook", "Medical Ethics"),
    q("Issuing a false medical certificate is an offense punishable under which section of the IPC?", "Section 197 IPC", "Section 191 IPC", "Section 304A IPC", "Section 320 IPC", "A", "Issuing or signing a false certificate is addressed by Section 197 IPC.", "HARD", "Textbook", "IPC Sections")
  ]],
  ["Forensic Pathology", [
    q("Which of the following changes occurs *first* after somatic death?", "Primary relaxation (flaccidity) of muscles", "Algor mortis (cooling of the body)", "Rigor mortis (stiffening of muscles)", "Livor mortis (postmortem lividity)", "A", "Immediately following death, the muscles lose all tone and become completely flaccid.", "EASY", "Textbook", "Changes after death"),
    q("Rigor mortis first begins to appear in which muscle group?", "Involuntary muscles (e.g., heart) and muscles of the eyelids/face", "Lower limbs", "Upper limbs", "Abdominal muscles", "A", "Rigor mortis begins simultaneously in all muscles but is first apparent in small muscles.", "EASY", "Textbook", "Rigor mortis"),
    q("Postmortem lividity (Livor mortis) is typically fully developed and fixed within:", "6 to 8 hours after death", "1 to 2 hours after death", "24 to 36 hours after death", "48 to 72 hours after death", "A", "Lividity fixes around 6-8 hours, indicating the body position at the time of death.", "MEDIUM", "Textbook", "Livor mortis"),
    q("Cherry-red coloration of postmortem lividity is strongly indicative of poisoning by:", "Carbon monoxide", "Cyanide", "Phosphorus", "Arsenic", "A", "Carboxyhemoglobin imparts a classical cherry-red color to the skin and tissues.", "EASY", "Textbook", "Postmortem findings"),
    q("The primary mechanism responsible for putrefaction of a dead body is:", "Bacterial action (primarily Clostridium welchii)", "Autolysis by intracellular enzymes", "Evaporation of tissue fluids", "Coagulation of muscle proteins", "A", "Putrefaction is the decomposition of proteins, mainly by anaerobic bacteria from the bowel.", "EASY", "Textbook", "Decomposition"),
    q("Adipocere formation (saponification) occurs most commonly when a body is disposed of in:", "A moist, warm, anaerobic environment (e.g., water or damp soil)", "A dry, hot desert environment", "A completely frozen state", "A well-ventilated dry room", "A", "Hydrogenation of body fats converts them to a waxy, soap-like substance.", "MEDIUM", "Textbook", "Late postmortem changes"),
    q("Which bone is the most reliable for determining the sex of an adult skeleton?", "Pelvis", "Skull", "Femur", "Sternum", "A", "The pelvis exhibits the most pronounced sexual dimorphism related to childbirth.", "EASY", "Textbook", "Forensic Osteology"),
    q("The closure of the sagittal suture of the skull generally begins at approximately what age?", "25-30 years", "12-15 years", "18-20 years", "40-50 years", "A", "Cranial suture closure provides a rough estimate of age in adults.", "HARD", "Textbook", "Age estimation"),
    q("A 'Pugilistic attitude' (boxer's posture) in a dead body is characteristic of death due to:", "Burns (extensive heat exposure)", "Strychnine poisoning", "Hanging", "Drowning", "A", "Coagulation of muscle proteins causes flexion of limbs, resembling a boxer.", "MEDIUM", "Textbook", "Thermal injuries"),
    q("Abrasions are mechanical injuries primarily involving the:", "Epidermis (superficial layer of skin)", "Dermis and subcutaneous tissue", "Underlying muscle only", "Bones and joints", "A", "Abrasions are superficial injuries caused by friction against a rough surface.", "EASY", "Textbook", "Mechanical injuries")
  ]],
  ["Clinical Forensic Medicine", [
    q("Under Section 320 of the IPC, 'Grievous Hurt' includes all of the following EXCEPT:", "An injury causing pain for 10 days", "Emasculation", "Permanent privation of the sight of either eye", "Fracture or dislocation of a bone", "A", "To be grievous due to duration, it must cause severe pain or inability to follow ordinary pursuits for 20 days.", "EASY", "Textbook", "Mechanical injuries"),
    q("A bruise (contusion) typically changes its color to yellow at around what time following the injury?", "7 to 12 days", "1 to 3 days", "4 to 5 days", "14 to 20 days", "A", "Hemoglobin breakdown causes color changes: red -> blue/black -> green -> yellow.", "MEDIUM", "Textbook", "Mechanical injuries"),
    q("In a typical stab wound, the depth of the wound is:", "Greater than its length and width on the surface", "Lesser than its length on the surface", "Equal to its length but greater than the width", "Completely unmeasurable", "A", "A stab is a penetrating injury where depth > length.", "EASY", "Textbook", "Mechanical injuries"),
    q("A lacerated wound is characterized by:", "Irregular, torn, and ragged margins with tissue bridging", "Cleanly divided, sharp, straight margins", "Depth exceeding length on the skin surface", "Minimal bleeding and absence of bruising", "A", "Lacerations result from blunt force tearing the skin and underlying tissues.", "EASY", "Textbook", "Mechanical injuries"),
    q("A 'Hesitation cut' (tentative cut) is classically associated with:", "Suicidal incised wounds", "Homicidal stab wounds", "Accidental lacerations", "Defense wounds", "A", "Multiple superficial, parallel cuts near a fatal incised wound indicate suicidal intent.", "MEDIUM", "Textbook", "Mechanical injuries"),
    q("Which of the following is an absolute sign of entry in a firearm wound (gunshot)?", "Abrasion collar (ring of dirt/abrasion)", "Large, irregular, everted margins", "Heavy bleeding", "Stellate shape", "A", "The spinning bullet scrapes the skin margin during entry, leaving an abrasion collar.", "HARD", "Textbook", "Firearm injuries"),
    q("In typical Hanging, the knot of the ligature is most commonly situated:", "At the nape of the neck (occipital region)", "Under the chin", "On the right side of the neck", "On the left side of the neck", "A", "The knot is usually found at the nape in atypical or typical hanging scenarios.", "MEDIUM", "Textbook", "Asphyxial deaths"),
    q("The classic postmortem finding in death by strangulation (ligature or manual) compared to hanging is a higher incidence of:", "Fracture of the hyoid bone and thyroid cartilage", "Pale, white face", "Complete absence of petechial hemorrhages", "Saliva dribbling from the mouth", "A", "The inward force in strangulation frequently fractures the neck structures, especially in older adults.", "MEDIUM", "Textbook", "Asphyxial deaths"),
    q("The presence of fine, copious, persistent, white froth at the mouth and nostrils is characteristic of death by:", "Drowning", "Hanging", "Carbon monoxide poisoning", "Starvation", "A", "Water mixing with air and mucus/surfactant during agonal breathing creates the froth.", "EASY", "Textbook", "Asphyxial deaths"),
    q("Diatoms found in the bone marrow or brain of a dead body retrieved from water strongly suggests:", "Antemortem drowning", "Postmortem submersion of a dead body", "Death by massive myocardial infarction", "Contamination during autopsy", "A", "Diatoms cross the alveolar-capillary membrane only if the heart was beating while inhaling water.", "MEDIUM", "Textbook", "Asphyxial deaths")
  ]],
  ["Toxicology", [
    q("The 'Universal Antidote' is a mixture of:", "Activated charcoal, magnesium oxide, and tannic acid", "BAL, EDTA, and Penicillamine", "Naloxone, Flumazenil, and Atropine", "Sodium bicarbonate and gastric lavage fluid", "A", "It was historically used for unknown poisons, though activated charcoal alone is preferred today.", "MEDIUM", "Textbook", "General Toxicology"),
    q("Gastric lavage is strictly contraindicated in cases of poisoning by:", "Corrosives (strong acids or alkalis)", "Organophosphates", "Barbiturates", "Opioids", "A", "Lavage risks perforating the esophagus or stomach damaged by corrosives.", "EASY", "Textbook", "General Toxicology"),
    q("The mechanism of action of Organophosphate poisoning is the irreversible inhibition of:", "Acetylcholinesterase", "Cytochrome c oxidase", "Na+/K+ ATPase", "Monoamine oxidase", "A", "OPs phosphorylate the active site of AChE, causing massive acetylcholine accumulation.", "EASY", "Textbook", "Agrochemical poisons"),
    q("Pinpoint pupils (miosis), profound respiratory depression, and coma are the classic triad of poisoning by:", "Opiates/Opioids (e.g., Morphine)", "Cocaine", "Amphetamines", "Datura (Atropine)", "A", "This is the classic presentation of acute opioid overdose.", "EASY", "Textbook", "Drug abuse"),
    q("The specific antidote for acute opioid overdose is:", "Naloxone", "Flumazenil", "Atropine", "Pralidoxime (PAM)", "A", "Naloxone is a competitive opioid receptor antagonist that rapidly reverses respiratory depression.", "EASY", "Textbook", "Drug abuse"),
    q("Which heavy metal poisoning presents with 'Aldrich-Mees lines' (white transverse lines on fingernails), hyperkeratosis of palms/soles, and 'raindrop' pigmentation?", "Arsenic", "Lead", "Mercury", "Copper", "A", "Arsenic chronic toxicity classically impacts the skin and nails over time.", "HARD", "Textbook", "Heavy metals"),
    q("Burtonian line (a blue-black line on the gums), basophilic stippling of RBCs, and wrist drop/foot drop are characteristic of chronic poisoning by:", "Lead", "Arsenic", "Mercury", "Thallium", "A", "Lead poisoning causes a motor neuropathy and deposits lead sulfide in the gums.", "MEDIUM", "Textbook", "Heavy metals"),
    q("The active toxic principle in the seeds of Nux Vomica is:", "Strychnine", "Atropine", "Aconitine", "Ricinine", "A", "Strychnine acts as a competitive antagonist at glycine receptors in the spinal cord, causing severe convulsions.", "MEDIUM", "Textbook", "Plant poisons"),
    q("Which plant poison causes symptoms closely mimicking a severe exacerbation of acute gastroenteritis (cholera-like diarrhea)?", "Ricinus communis (Castor oil plant/Ricin)", "Datura stramonium", "Strychnos nux vomica", "Cannabis sativa", "A", "Ricin causes severe, hemorrhagic mucosal damage and profuse watery diarrhea.", "HARD", "Textbook", "Plant poisons"),
    q("A person presenting with dry mouth, dilated pupils, flushed hot skin, delirium, and tachycardia ('Hot as a hare, blind as a bat, dry as a bone, red as a beet, mad as a hatter') is likely poisoned by:", "Datura (Atropa belladonna / anticholinergic)", "Organophosphates", "Opioids", "Barbiturates", "A", "This is the classic toxidrome of anticholinergic poisoning (atropine).", "EASY", "Textbook", "Plant poisons")
  ]],
  ["Sexual Jurisprudence", [
    q("Under the IPC Section 375, the definition of Rape was significantly expanded to include non-peno-vaginal penetration following which amendment?", "Criminal Law (Amendment) Act, 2013 (Nirbhaya Act)", "Criminal Law (Amendment) Act, 1983", "Protection of Children from Sexual Offences (POCSO) Act, 2012", "Indian Evidence Act Amendment, 2002", "A", "The 2013 amendment expanded the definition of rape to include insertion of objects or other body parts.", "EASY", "Textbook", "Sexual Offenses"),
    q("Which of the following implies sexual intercourse with a woman without her consent or against her will?", "Rape", "Incest", "Adultery", "Sodomy", "A", "Rape is defined legally primarily by the absence of valid consent.", "EASY", "Textbook", "Sexual Offenses"),
    q("The 'Two-Finger Test' (per vaginam examination to assess laxity) in cases of sexual assault has been explicitly:", "Banned by the Supreme Court of India and ICMR guidelines as it is unscientific and violates dignity", "Mandated as essential evidence in all rape cases", "Used primarily to determine the psychiatric health of the victim", "Recommended only for married women", "A", "The test has no forensic value for proving rape and is highly traumatizing.", "EASY", "Textbook", "Medical Examination"),
    q("In an alleged case of rape, the presence of spermatozoa in the high vaginal swab proves:", "That sexual intercourse (penetration and ejaculation) has occurred recently", "Only that penetration took place, but not ejaculation", "That the sexual act was definitively without consent", "That the victim was previously a virgin", "A", "Sperm proves recent intercourse but does not by itself prove a lack of consent (which is a legal determination).", "MEDIUM", "Textbook", "Forensic Evidence"),
    q("Sodomy (unnatural sexual offenses) is punishable under which section of the IPC?", "Section 377 IPC", "Section 376 IPC", "Section 354 IPC", "Section 375 IPC", "A", "Section 377 covers 'unnatural offenses' (carnal intercourse against the order of nature).", "MEDIUM", "Textbook", "IPC Sections"),
    q("Tribadism refers to homosexual practices between:", "Females", "Males", "Adults and minors", "Humans and animals", "A", "Tribadism refers to sexual activity between women (lesbianism).", "HARD", "Textbook", "Sexual Deviations"),
    q("Bestiality is defined as sexual intercourse by a human being with:", "An animal", "A corpse", "A child", "A close blood relative", "A", "It is classified as an unnatural sexual offense.", "EASY", "Textbook", "Sexual Deviations"),
    q("Which paraphilia involves recurrent, intense sexual arousal from the exposure of one's genitals to an unsuspecting stranger?", "Exhibitionism", "Voyeurism", "Fetishism", "Froteurism", "A", "Exhibitionism is a legally punishable sexual deviation.", "MEDIUM", "Textbook", "Paraphilias"),
    q("The medical examination of an accused in a rape case must be conducted:", "Only with his informed written consent or by a magistrate's order (Sec 53A CrPC)", "Regardless of his consent, using police force", "By a female medical officer", "Within 1 hour of the alleged offense", "A", "Under 53A CrPC, a registered medical practitioner can examine the accused upon police request, requiring formal consent/order.", "MEDIUM", "Textbook", "Medical Examination"),
    q("Which Act provides specific procedures and stringent punishments for sexual offenses committed against children below 18 years of age?", "POCSO Act, 2012 (Protection of Children from Sexual Offences Act)", "Juvenile Justice Act, 2015", "Child Marriage Restraint Act, 1929", "Immoral Traffic (Prevention) Act, 1956", "A", "The POCSO Act is specific, gender-neutral legislation for child sexual abuse.", "EASY", "Textbook", "Legal Acts")
  ]]
];

writeSubject("Forensics", chapters, "forensics.json");
