const { q, writeSubject } = require('./qgen_helper');

const chapters = [
  ["Cardiovascular System", [
    q("The most common cause of sustained arrhythmia in adults, characterized by an irregularly irregular pulse and absent P waves on ECG, is:", "Atrial Fibrillation", "Ventricular Tachycardia", "Atrial Flutter", "Sinus Tachycardia", "A", "AFib is a major risk factor for embolic stroke and heart failure.", "EASY", "Textbook", "Arrhythmias"),
    q("A 65-year-old male presents with crushing substernal chest pain radiating to his left arm, diaphoresis, and ST-segment elevation in leads V2-V4. The most likely diagnosis is:", "Acute Anteroseptal Myocardial Infarction", "Acute Pericarditis", "Stable Angina Pectoris", "Aortic Dissection", "A", "STEMI requires immediate reperfusion therapy (PCI or thrombolytics).", "EASY", "Textbook", "Ischemic Heart Disease"),
    q("The triad of 'Beck's Triad' associated with Cardiac Tamponade includes:", "Hypotension, Muffled heart sounds, Jugular venous distention", "Hypertension, Bradycardia, Irregular respirations", "Fever, New heart murmur, Splinter hemorrhages", "Chest pain, Friction rub, Diffuse ST elevation", "A", "Fluid accumulation in the pericardial space restricts diastolic filling.", "MEDIUM", "Textbook", "Pericardial Disease"),
    q("Which valvular lesion is classically described as a harsh, crescendo-decrescendo systolic murmur heard best at the right upper sternal border with radiation to the carotids?", "Aortic Stenosis", "Mitral Regurgitation", "Aortic Regurgitation", "Mitral Stenosis", "A", "Often caused by age-related calcification or a bicuspid aortic valve.", "EASY", "Textbook", "Valvular Heart Disease"),
    q("A mid-diastolic rumbling murmur with an opening snap at the apex is characteristic of:", "Mitral Stenosis", "Aortic Stenosis", "Mitral Regurgitation", "Ventricular Septal Defect", "A", "Almost exclusively caused by rheumatic heart disease.", "EASY", "Textbook", "Valvular Heart Disease"),
    q("Which neurohormonal system is chronically activated in Heart Failure with Reduced Ejection Fraction (HFrEF) and must be antagonized (e.g., with ACEi/ARBs and Beta-blockers) to improve survival?", "Renin-Angiotensin-Aldosterone System (RAAS) and Sympathetic Nervous System (SNS)", "Parasympathetic Nervous System", "Thyroid Axis", "Natriuretic Peptide System", "A", "Chronic activation leads to maladaptive cardiac remodeling and progressive dysfunction.", "MEDIUM", "Textbook", "Heart Failure"),
    q("What is the initial medical treatment of choice for a patient presenting with an acute exacerbation of heart failure (pulmonary edema)?", "Intravenous Loop Diuretics (e.g., Furosemide)", "Oral Beta-blockers", "Intravenous Digoxin", "Oral Calcium Channel Blockers", "A", "Loop diuretics rapidly relieve volume overload and pulmonary congestion.", "MEDIUM", "Textbook", "Heart Failure"),
    q("A 'tearing' severe, sudden-onset chest pain radiating to the back in a hypertensive patient strongly suggests:", "Aortic Dissection", "Acute Myocardial Infarction", "Pulmonary Embolism", "Pneumothorax", "A", "An intimal tear creates a false lumen in the aorta wall. It's a surgical or intense medical emergency.", "EASY", "Textbook", "Aortic Disease"),
    q("Which clinical sign involves an inspiratory fall in systolic blood pressure greater than 10 mmHg, characteristically seen in cardiac tamponade and severe asthma?", "Pulsus Paradoxus", "Pulsus Alternans", "Water-hammer pulse", "Pulsus Bisferiens", "A", "Exaggerated inspiratory drop in BP due to ventricular interdependence.", "HARD", "Textbook", "Physical Examination"),
    q("The modified Duke criteria are used for the diagnosis of which infectious cardiac condition?", "Infective Endocarditis", "Rheumatic Fever", "Viral Myocarditis", "Tuberculous Pericarditis", "A", "Criteria include positive blood cultures for typical organisms and echocardiographic evidence of vegetation.", "EASY", "Textbook", "Infective Endocarditis")
  ]],
  ["Respiratory System", [
    q("A 25-year-old with a history of episodic wheezing, chest tightness, and a dry cough, especially worse at night or after exercise, most likely has:", "Asthma", "Chronic Bronchitis", "Pneumonia", "Cystic Fibrosis", "A", "Asthma is characterized by reversible airway obstruction and airway hyperresponsiveness.", "EASY", "Textbook", "Airway Diseases"),
    q("Which pulmonary function test (PFT) pattern is the hallmark of obstructive lung diseases like COPD and Asthma?", "Decreased FEV1/FVC ratio (< 0.70)", "Normal or Increased FEV1/FVC ratio", "Decreased Total Lung Capacity (TLC)", "Decreased Residual Volume (RV)", "A", "Obstruction significantly slows forced expiration, lowering the ratio.", "EASY", "Textbook", "PFTs"),
    q("A 'pink puffer' is a classic, though somewhat outdated, clinical descriptor for a patient with which phenotype of COPD?", "Emphysema-predominant", "Chronic Bronchitis-predominant", "Bronchiectasis", "Asthma", "A", "Patients often have severe dyspnea, maintain ABGs longer through hyperventilation, and lack severe cyanosis/edema.", "MEDIUM", "Textbook", "COPD"),
    q("The most common community-acquired bacterial cause of typical lobar pneumonia, presenting with rust-colored sputum and a sudden onset chill, is:", "Streptococcus pneumoniae", "Mycoplasma pneumoniae", "Haemophilus influenzae", "Legionella pneumophila", "A", "Pneumococcus remains the leading cause of typical CAP.", "EASY", "Textbook", "Pneumonia"),
    q("Atypical pneumonia (often called 'walking pneumonia'), presenting with a non-productive cough, low-grade fever, and prominent patchy interstitial infiltrates on X-ray, is most frequently caused by:", "Mycoplasma pneumoniae", "Staphylococcus aureus", "Klebsiella pneumoniae", "Streptococcus pneumoniae", "A", "Common in young adults/dorms; frequently treated with macrolides.", "EASY", "Textbook", "Pneumonia"),
    q("Pleural effusion fluid that is frankly pus is termed a(n):", "Empyema", "Transudate", "Chylothorax", "Hemothorax", "A", "An empyema is a localized collection of pus in the pleural space, requiring drainage.", "MEDIUM", "Textbook", "Pleural Disease"),
    q("According to Light's criteria, a pleural fluid is classified as an exudate if the ratio of pleural fluid protein to serum protein is greater than:", "0.5", "0.2", "0.8", "1.0", "A", "Exudates (e.g., from infection or malignancy) are protein-rich compared to transudates (from heart failure/cirrhosis).", "HARD", "Textbook", "Pleural Disease"),
    q("A tall, thin young man presents to the ER with sudden-onset unilateral pleuritic chest pain and dyspnea. Exam reveals hyperresonance and decreased breath sounds on the affected side. Diagnosis?", "Spontaneous pneumothorax", "Pulmonary embolism", "Acute asthma exacerbation", "Myocardial infarction", "A", "Rupture of a subpleural apical bleb causes a primary spontaneous pneumothorax.", "EASY", "Textbook", "Pleural Disease"),
    q("Which condition causes chronic restrictive lung disease characterized by non-caseating granulomas in multiple organs and bilateral hilar lymphadenopathy on CXR?", "Sarcoidosis", "Ideopathic Pulmonary Fibrosis", "Tuberculosis", "Coal Worker's Pneumoconiosis", "A", "Systemic inflammatory disease of unknown origin common in young adults.", "MEDIUM", "Textbook", "Interstitial Lung Disease"),
    q("The Wells Score is validated to assist in the clinical probability assessment of which acute condition?", "Pulmonary Embolism / DVT", "Community Acquired Pneumonia severity (CURB-65 is used for this)", "Asthma exacerbation severity", "Risk of stroke in Atrial Fibrillation (CHADS2-VASc)", "A", "It considers signs of DVT, alternative diagnoses, heart rate, immobilization, prior PE, hemoptysis, and cancer.", "MEDIUM", "Textbook", "Pulmonary Embolism")
  ]],
  ["Gastrointestinal System", [
    q("A 45-year-old female presents with severe pain in the right upper quadrant radiating to her right scapula, especially after eating fatty meals, accompanied by fever and a positive Murphy's sign. The likely diagnosis is:", "Acute Cholecystitis", "Acute Pancreatitis", "Peptic Ulcer Disease", "Acute Appendicitis", "A", "Murphy's sign (arrest of inspiration upon palpation of the gallbladder) is highly sensitive for cholecystitis.", "EASY", "Textbook", "Biliary Tract Disease"),
    q("The most frequent cause of acute pancreatitis worldwide is:", "Gallstones", "Alcohol abuse", "Hypertriglyceridemia", "ERCP complication", "A", "Gallstones passing into the common bile duct and obstructing the ampulla of Vater.", "EASY", "Textbook", "Pancreatic Disease"),
    q("A perforated duodenal ulcer typically allows air into the peritoneal cavity causing 'air under the diaphragm', which is best seen on which imaging study?", "Erect chest X-ray", "Supine abdominal X-ray", "Ultrasound of the abdomen", "Barium swallow", "A", "Free air rises to the highest point, visible just below the diaphragm on an upright plain film.", "EASY", "Textbook", "Peptic Ulcer Disease"),
    q("Helicobacter pylori eradication therapy typically consists of a Proton Pump Inhibitor (PPI) and which two antibiotics?", "Clarithromycin and Amoxicillin (or Metronidazole)", "Ciprofloxacin and Doxycycline", "Vancomycin and Gentamicin", "Ceftriaxone and Azithromycin", "A", "The 'triple therapy' is standard first-line treatment for H. pylori.", "MEDIUM", "Textbook", "Peptic Ulcer Disease"),
    q("A patient with long-standing gastroesophageal reflux disease (GERD) undergoes an endoscopy revealing 'salmon-colored mucosa' extending upward from the GE junction. Biopsy shows intestinal metaplasia. Diagnosis?", "Barrett's Esophagus", "Esophageal Varices", "Achalasia", "Mallory-Weiss Tear", "A", "Barrett's esophagus is a metaplastic change caused by chronic acid exposure, predisposing to adenocarcinoma.", "EASY", "Textbook", "Esophageal Disease"),
    q("Which condition is an inflammatory bowel disease characterized by 'skip lesions', transmural inflammation, non-caseating granulomas, and a predilection for the terminal ileum?", "Crohn's Disease", "Ulcerative Colitis", "Irritable Bowel Syndrome", "Celiac Sprue", "A", "Crohn's can affect the entire GI tract 'from mouth to anus'.", "EASY", "Textbook", "Inflammatory Bowel Disease"),
    q("The initial investigation of choice for a patient presenting with an acute lower gastrointestinal bleed (hematochezia) who is hemodynamically stable is:", "Colonoscopy", "Upper GI Endoscopy (EGD)", "Angiography", "Barium enema", "A", "Colonoscopy is diagnostic and therapeutic for the vast majority of lower GI bleeds.", "MEDIUM", "Textbook", "GI Bleeding"),
    q("A classic presentation of painless, large volume upper GI bleeding (hematemesis/melena) in a patient with known liver cirrhosis is most likely due to a ruptured:", "Esophageal Varix", "Peptic Ulcer", "Mallory-Weiss Tear", "Gastric carcinoma", "A", "Portal hypertension leads to the development of dilated collateral veins (varices) that rupture easily.", "EASY", "Textbook", "GI Bleeding"),
    q("What is the principal laboratory screening test for Celiac Disease (Gluten-sensitive enteropathy)?", "IgA anti-tissue transglutaminase (tTG) antibody", "Anti-Saccharomyces cerevisiae antibodies (ASCA)", "Antimitochondrial antibodies (AMA)", "Antinuclear antibodies (ANA)", "A", "IgA anti-tTG is highly sensitive and specific; confirmed by duodenal biopsy showing villous atrophy.", "MEDIUM", "Textbook", "Malabsorption"),
    q("A 20-year-old male with recurrent jaundice provoked only by stress, fasting, or exertion, with normal liver enzymes and isolated indirect hyperbilirubinemia, most likely has:", "Gilbert's Syndrome", "Crigler-Najjar Syndrome", "Acute Viral Hepatitis", "Autoimmune Hepatitis", "A", "Gilbert's is a common, benign inherited deficiency in glucuronyltransferase (UGT1A1) activity.", "MEDIUM", "Textbook", "Liver Disease")
  ]],
  ["Nephrology", [
    q("The most common cause of End-Stage Renal Disease (ESRD) requiring dialysis in developed countries is:", "Diabetic Nephropathy", "Hypertensive Nephrosclerosis", "Glomerulonephritis", "Polycystic Kidney Disease", "A", "Diabetes mellitus is the leading cause of chronic kidney failure.", "EASY", "Textbook", "Chronic Kidney Disease"),
    q("A clinical syndrome characterized by heavy proteinuria (>3.5 g/day), hypoalbuminemia, generalized edema, and hyperlipidemia is termed:", "Nephrotic Syndrome", "Nephritic Syndrome", "Acute Kidney Injury", "Uremic Syndrome", "A", "The loss of the glomerular filtration barrier to proteins defines the nephrotic syndrome.", "EASY", "Textbook", "Glomerular Disease"),
    q("Which condition presents classically with a 'Nephritic' picture (hematuria, RBC casts, hypertension, oliguria) 1-3 weeks after a group A streptococcal skin or throat infection?", "Post-streptococcal Glomerulonephritis (PSGN)", "IgA Nephropathy", "Minimal Change Disease", "Goodpasture Syndrome", "A", "PSGN is an immune-complex mediated GN common in children.", "EASY", "Textbook", "Glomerular Disease"),
    q("IgA Nephropathy (Berger's Disease) differs from PSGN primarily in that it classically presents:", "Concurrent with a mucosal respiratory or GI infection (synpharyngitic hematuria)", "1 to 3 weeks after a throat infection", "With massive nephrotic-range proteinuria", "Only in elderly patients", "A", "IgA nephropathy typically flares *during* a viral illness, not weeks later.", "MEDIUM", "Textbook", "Glomerular Disease"),
    q("The presence of muddy brown granular casts on urinalysis is the hallmark of:", "Acute Tubular Necrosis (ATN)", "Acute Interstitial Nephritis (AIN)", "Glomerulonephritis", "Urinary Tract Infection", "A", "Ischemia or nephrotoxins destroy the tubular epithelial cells, which slough off into casts.", "EASY", "Textbook", "Acute Kidney Injury"),
    q("Acute Interstitial Nephritis (AIN) most frequently develops as an allergic reaction to which class of drugs?", "Penicillins/Cephalosporins and NSAIDs", "ACE inhibitors", "Statins", "Beta-blockers", "A", "AIN presents with fever, rash, eosinophilia, and AKI shortly after starting a new medication.", "MEDIUM", "Textbook", "Acute Kidney Injury"),
    q("Which ECG change is the classic earliest sign of severe hyperkalemia?", "Tall, peaked T-waves", "U-waves", "ST-segment depression", "Prolonged QT interval", "A", "As K+ rises further, the QRS complex widens, eventually fusing with the T-wave (sine wave).", "EASY", "Textbook", "Electrolytes"),
    q("The definitive, most rapid-acting emergency treatment to stabilize the myocardium in severe hyperkalemia is:", "Intravenous Calcium (Gluconate or Chloride)", "Intravenous Insulin and Dextrose", "Inhaled Albuterol", "Intravenous Sodium Bicarbonate", "A", "Calcium antagonizes the membrane-depolarizing effects of high K+, preventing fatal arrhythmias.", "MEDIUM", "Textbook", "Electrolytes"),
    q("Autosomal Dominant Polycystic Kidney Disease (ADPKD) is frequently associated with which life-threatening extra-renal manifestation?", "Berry aneurysms in the Circle of Willis", "Hepatic cirrhosis", "Hypertrophic cardiomyopathy", "Pulmonary fibrosis", "A", "Rupture of a cerebral berry aneurysm causes a fatal subarachnoid hemorrhage.", "HARD", "Textbook", "Cystic Kidney Disease"),
    q("Which type of renal stone is radio-lucent (invisible on plain abdominal X-ray) but visible on CT?", "Uric acid stones", "Calcium oxalate stones", "Calcium phosphate stones", "Struvite stones", "A", "Uric acid and cystine stones are minimally or completely radio-lucent.", "MEDIUM", "Textbook", "Nephrolithiasis")
  ]]
];

writeSubject("Medicine", chapters, "medicine.json");
